.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....E
======================================================================
ERROR: test_write_csv_6 (ClassEval_26_0.CSVProcessorTestWriteCSV.test_write_csv_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_0.py", line 216, in test_write_csv_6
    self.assertEqual(0, csvProcessor.write_csv([], file_path))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_0.py", line 37, in write_csv
    with open(file_name, 'w', newline='') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.005s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
.....E
======================================================================
ERROR: test_write_csv_6 (ClassEval_26_1.CSVProcessorTestWriteCSV.test_write_csv_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_1.py", line 201, in test_write_csv_6
    self.assertEqual(0, csvProcessor.write_csv([], file_path))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_1.py", line 31, in write_csv
    with open(file_name, 'w', newline='') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.005s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....E
======================================================================
ERROR: test_write_csv_6 (ClassEval_26_2.CSVProcessorTestWriteCSV.test_write_csv_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_2.py", line 216, in test_write_csv_6
    self.assertEqual(0, csvProcessor.write_csv([], file_path))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_2.py", line 37, in write_csv
    with open(file_name, 'w', newline='') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.004s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....E
======================================================================
ERROR: test_write_csv_6 (ClassEval_26_3.CSVProcessorTestWriteCSV.test_write_csv_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_3.py", line 215, in test_write_csv_6
    self.assertEqual(0, csvProcessor.write_csv([], file_path))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_3.py", line 37, in write_csv
    with open(file_name, 'w', newline='') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.004s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....E
======================================================================
ERROR: test_write_csv_6 (ClassEval_26_4.CSVProcessorTestWriteCSV.test_write_csv_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_4.py", line 215, in test_write_csv_6
    self.assertEqual(0, csvProcessor.write_csv([], file_path))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_26_4.py", line 37, in write_csv
    with open(file_name, 'w', newline='') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.006s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.050s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.013s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.011s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.016s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.010s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.011s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.010s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.010s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.014s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.011s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.013s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.010s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.009s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
EEEEE
======================================================================
ERROR: test_process_file_1 (ClassEval_84_0.TextFileProcessorTestProcessFile.test_process_file_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 213, in test_process_file_1
    result = textFileProcessor.process_file()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 59, in process_file
    with open(self.file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

======================================================================
ERROR: test_process_file_2 (ClassEval_84_0.TextFileProcessorTestProcessFile.test_process_file_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 227, in test_process_file_2
    result = textFileProcessor.process_file()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 59, in process_file
    with open(self.file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

======================================================================
ERROR: test_process_file_3 (ClassEval_84_0.TextFileProcessorTestProcessFile.test_process_file_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 241, in test_process_file_3
    result = textFileProcessor.process_file()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 59, in process_file
    with open(self.file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

======================================================================
ERROR: test_process_file_4 (ClassEval_84_0.TextFileProcessorTestProcessFile.test_process_file_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 255, in test_process_file_4
    result = textFileProcessor.process_file()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 59, in process_file
    with open(self.file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

======================================================================
ERROR: test_process_file_5 (ClassEval_84_0.TextFileProcessorTestProcessFile.test_process_file_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 269, in test_process_file_5
    result = textFileProcessor.process_file()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_0.py", line 59, in process_file
    with open(self.file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

----------------------------------------------------------------------
Ran 5 tests in 0.005s

FAILED (errors=5)
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
FFFFF
======================================================================
FAIL: test_process_file_1 (ClassEval_84_1.TextFileProcessorTestProcessFile.test_process_file_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_1.py", line 214, in test_process_file_1
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloWorld'
- nametestage
+ HelloWorld


======================================================================
FAIL: test_process_file_2 (ClassEval_84_1.TextFileProcessorTestProcessFile.test_process_file_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_1.py", line 228, in test_process_file_2
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloabcWorld'
- nametestage
+ HelloabcWorld


======================================================================
FAIL: test_process_file_3 (ClassEval_84_1.TextFileProcessorTestProcessFile.test_process_file_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_1.py", line 242, in test_process_file_3
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != ''
- nametestage


======================================================================
FAIL: test_process_file_4 (ClassEval_84_1.TextFileProcessorTestProcessFile.test_process_file_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_1.py", line 256, in test_process_file_4
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloWorld'
- nametestage
+ HelloWorld


======================================================================
FAIL: test_process_file_5 (ClassEval_84_1.TextFileProcessorTestProcessFile.test_process_file_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_1.py", line 270, in test_process_file_5
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloaWorld'
- nametestage
+ HelloaWorld


----------------------------------------------------------------------
Ran 5 tests in 0.005s

FAILED (failures=5)
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
FFFFF
======================================================================
FAIL: test_process_file_1 (ClassEval_84_2.TextFileProcessorTestProcessFile.test_process_file_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_2.py", line 214, in test_process_file_1
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloWorld'
- nametestage
+ HelloWorld


======================================================================
FAIL: test_process_file_2 (ClassEval_84_2.TextFileProcessorTestProcessFile.test_process_file_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_2.py", line 228, in test_process_file_2
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloabcWorld'
- nametestage
+ HelloabcWorld


======================================================================
FAIL: test_process_file_3 (ClassEval_84_2.TextFileProcessorTestProcessFile.test_process_file_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_2.py", line 242, in test_process_file_3
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != ''
- nametestage


======================================================================
FAIL: test_process_file_4 (ClassEval_84_2.TextFileProcessorTestProcessFile.test_process_file_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_2.py", line 256, in test_process_file_4
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloWorld'
- nametestage
+ HelloWorld


======================================================================
FAIL: test_process_file_5 (ClassEval_84_2.TextFileProcessorTestProcessFile.test_process_file_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_2.py", line 270, in test_process_file_5
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloaWorld'
- nametestage
+ HelloaWorld


----------------------------------------------------------------------
Ran 5 tests in 0.007s

FAILED (failures=5)
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
FFFFF
======================================================================
FAIL: test_process_file_1 (ClassEval_84_3.TextFileProcessorTestProcessFile.test_process_file_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_3.py", line 222, in test_process_file_1
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloWorld'
- nametestage
+ HelloWorld


======================================================================
FAIL: test_process_file_2 (ClassEval_84_3.TextFileProcessorTestProcessFile.test_process_file_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_3.py", line 236, in test_process_file_2
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloabcWorld'
- nametestage
+ HelloabcWorld


======================================================================
FAIL: test_process_file_3 (ClassEval_84_3.TextFileProcessorTestProcessFile.test_process_file_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_3.py", line 250, in test_process_file_3
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != ''
- nametestage


======================================================================
FAIL: test_process_file_4 (ClassEval_84_3.TextFileProcessorTestProcessFile.test_process_file_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_3.py", line 264, in test_process_file_4
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloWorld'
- nametestage
+ HelloWorld


======================================================================
FAIL: test_process_file_5 (ClassEval_84_3.TextFileProcessorTestProcessFile.test_process_file_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_3.py", line 278, in test_process_file_5
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloaWorld'
- nametestage
+ HelloaWorld


----------------------------------------------------------------------
Ran 5 tests in 0.006s

FAILED (failures=5)
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
FFFFF
======================================================================
FAIL: test_process_file_1 (ClassEval_84_4.TextFileProcessorTestProcessFile.test_process_file_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_4.py", line 214, in test_process_file_1
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloWorld'
- nametestage
+ HelloWorld


======================================================================
FAIL: test_process_file_2 (ClassEval_84_4.TextFileProcessorTestProcessFile.test_process_file_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_4.py", line 228, in test_process_file_2
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloabcWorld'
- nametestage
+ HelloabcWorld


======================================================================
FAIL: test_process_file_3 (ClassEval_84_4.TextFileProcessorTestProcessFile.test_process_file_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_4.py", line 242, in test_process_file_3
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != ''
- nametestage


======================================================================
FAIL: test_process_file_4 (ClassEval_84_4.TextFileProcessorTestProcessFile.test_process_file_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_4.py", line 256, in test_process_file_4
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloWorld'
- nametestage
+ HelloWorld


======================================================================
FAIL: test_process_file_5 (ClassEval_84_4.TextFileProcessorTestProcessFile.test_process_file_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_84_4.py", line 270, in test_process_file_5
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloaWorld'
- nametestage
+ HelloaWorld


----------------------------------------------------------------------
Ran 5 tests in 0.007s

FAILED (failures=5)
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....E
======================================================================
ERROR: test_read_xml_6 (ClassEval_98_0.XMLProcessorTestReadXml.test_read_xml_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 167, in test_read_xml_6
    root = self.processor.read_xml()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 23, in read_xml
    tree = ET.parse(self.file_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 558, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.008s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.009s

OK
FFFFF
======================================================================
FAIL: test_process_xml_data_1 (ClassEval_98_0.XMLProcessorTestProcessXmlData.test_process_xml_data_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 320, in test_process_xml_data_1
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_2 (ClassEval_98_0.XMLProcessorTestProcessXmlData.test_process_xml_data_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 345, in test_process_xml_data_2
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_3 (ClassEval_98_0.XMLProcessorTestProcessXmlData.test_process_xml_data_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 369, in test_process_xml_data_3
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_4 (ClassEval_98_0.XMLProcessorTestProcessXmlData.test_process_xml_data_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 392, in test_process_xml_data_4
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_5 (ClassEval_98_0.XMLProcessorTestProcessXmlData.test_process_xml_data_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 416, in test_process_xml_data_5
    self.assertEqual(lst[0].text, 'AAA')
AssertionError: 'aaa' != 'AAA'
- aaa
+ AAA


----------------------------------------------------------------------
Ran 5 tests in 0.007s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
F
======================================================================
FAIL: test_XMLProcessor (ClassEval_98_0.XMLProcessorTest.test_XMLProcessor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_0.py", line 554, in test_XMLProcessor
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
.....E
======================================================================
ERROR: test_read_xml_6 (ClassEval_98_1.XMLProcessorTestReadXml.test_read_xml_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_1.py", line 178, in test_read_xml_6
    root = self.processor.read_xml()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_1.py", line 28, in read_xml
    tree = ET.parse(self.file_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 558, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.005s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.010s

OK
FFFFF
======================================================================
FAIL: test_process_xml_data_1 (ClassEval_98_1.XMLProcessorTestProcessXmlData.test_process_xml_data_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_1.py", line 331, in test_process_xml_data_1
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_2 (ClassEval_98_1.XMLProcessorTestProcessXmlData.test_process_xml_data_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_1.py", line 356, in test_process_xml_data_2
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_3 (ClassEval_98_1.XMLProcessorTestProcessXmlData.test_process_xml_data_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_1.py", line 380, in test_process_xml_data_3
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_4 (ClassEval_98_1.XMLProcessorTestProcessXmlData.test_process_xml_data_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_1.py", line 403, in test_process_xml_data_4
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_5 (ClassEval_98_1.XMLProcessorTestProcessXmlData.test_process_xml_data_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_1.py", line 427, in test_process_xml_data_5
    self.assertEqual(lst[0].text, 'AAA')
AssertionError: 'aaa' != 'AAA'
- aaa
+ AAA


----------------------------------------------------------------------
Ran 5 tests in 0.007s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
F
======================================================================
FAIL: test_XMLProcessor (ClassEval_98_1.XMLProcessorTest.test_XMLProcessor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_1.py", line 565, in test_XMLProcessor
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
.....E
======================================================================
ERROR: test_read_xml_6 (ClassEval_98_2.XMLProcessorTestReadXml.test_read_xml_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 170, in test_read_xml_6
    root = self.processor.read_xml()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 28, in read_xml
    tree = ET.parse(self.file_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 558, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.005s

FAILED (errors=1)
.....E
======================================================================
ERROR: test_write_xml_6 (ClassEval_98_2.XMLProcessorTestWriteXml.test_write_xml_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 743, in _get_writer
    write = file_or_filename.write
            ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 300, in test_write_xml_6
    result = self.processor.write_xml("")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 44, in write_xml
    tree.write(file_name)
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 717, in write
    with _get_writer(file_or_filename, encoding) as (write, declared_encoding):
  File "/opt/miniconda3/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 748, in _get_writer
    with open(file_or_filename, "w", encoding=encoding,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.008s

FAILED (errors=1)
FFFFF
======================================================================
FAIL: test_process_xml_data_1 (ClassEval_98_2.XMLProcessorTestProcessXmlData.test_process_xml_data_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 323, in test_process_xml_data_1
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_2 (ClassEval_98_2.XMLProcessorTestProcessXmlData.test_process_xml_data_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 348, in test_process_xml_data_2
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_3 (ClassEval_98_2.XMLProcessorTestProcessXmlData.test_process_xml_data_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 372, in test_process_xml_data_3
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_4 (ClassEval_98_2.XMLProcessorTestProcessXmlData.test_process_xml_data_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 395, in test_process_xml_data_4
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_5 (ClassEval_98_2.XMLProcessorTestProcessXmlData.test_process_xml_data_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 419, in test_process_xml_data_5
    self.assertEqual(lst[0].text, 'AAA')
AssertionError: 'aaa' != 'AAA'
- aaa
+ AAA


----------------------------------------------------------------------
Ran 5 tests in 0.006s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
F
======================================================================
FAIL: test_XMLProcessor (ClassEval_98_2.XMLProcessorTest.test_XMLProcessor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_2.py", line 557, in test_XMLProcessor
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
.....E
======================================================================
ERROR: test_read_xml_6 (ClassEval_98_3.XMLProcessorTestReadXml.test_read_xml_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_3.py", line 170, in test_read_xml_6
    root = self.processor.read_xml()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_3.py", line 23, in read_xml
    tree = ET.parse(self.file_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 558, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.005s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.006s

OK
FFFFF
======================================================================
FAIL: test_process_xml_data_1 (ClassEval_98_3.XMLProcessorTestProcessXmlData.test_process_xml_data_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_3.py", line 323, in test_process_xml_data_1
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_2 (ClassEval_98_3.XMLProcessorTestProcessXmlData.test_process_xml_data_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_3.py", line 348, in test_process_xml_data_2
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_3 (ClassEval_98_3.XMLProcessorTestProcessXmlData.test_process_xml_data_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_3.py", line 372, in test_process_xml_data_3
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_4 (ClassEval_98_3.XMLProcessorTestProcessXmlData.test_process_xml_data_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_3.py", line 395, in test_process_xml_data_4
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_5 (ClassEval_98_3.XMLProcessorTestProcessXmlData.test_process_xml_data_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_3.py", line 419, in test_process_xml_data_5
    self.assertEqual(lst[0].text, 'AAA')
AssertionError: 'aaa' != 'AAA'
- aaa
+ AAA


----------------------------------------------------------------------
Ran 5 tests in 0.009s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
F
======================================================================
FAIL: test_XMLProcessor (ClassEval_98_3.XMLProcessorTest.test_XMLProcessor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_3.py", line 557, in test_XMLProcessor
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
.....E
======================================================================
ERROR: test_read_xml_6 (ClassEval_98_4.XMLProcessorTestReadXml.test_read_xml_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_4.py", line 168, in test_read_xml_6
    root = self.processor.read_xml()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_4.py", line 23, in read_xml
    tree = ET.parse(self.file_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 1204, in parse
    tree.parse(source, parser)
  File "/opt/miniconda3/lib/python3.12/xml/etree/ElementTree.py", line 558, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.007s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.006s

OK
FFFFF
======================================================================
FAIL: test_process_xml_data_1 (ClassEval_98_4.XMLProcessorTestProcessXmlData.test_process_xml_data_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_4.py", line 321, in test_process_xml_data_1
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_2 (ClassEval_98_4.XMLProcessorTestProcessXmlData.test_process_xml_data_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_4.py", line 346, in test_process_xml_data_2
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_3 (ClassEval_98_4.XMLProcessorTestProcessXmlData.test_process_xml_data_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_4.py", line 370, in test_process_xml_data_3
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_4 (ClassEval_98_4.XMLProcessorTestProcessXmlData.test_process_xml_data_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_4.py", line 393, in test_process_xml_data_4
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_5 (ClassEval_98_4.XMLProcessorTestProcessXmlData.test_process_xml_data_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_4.py", line 417, in test_process_xml_data_5
    self.assertEqual(lst[0].text, 'AAA')
AssertionError: 'aaa' != 'AAA'
- aaa
+ AAA


----------------------------------------------------------------------
Ran 5 tests in 0.006s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
F
======================================================================
FAIL: test_XMLProcessor (ClassEval_98_4.XMLProcessorTest.test_XMLProcessor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_98_4.py", line 555, in test_XMLProcessor
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.013s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.013s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.010s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.010s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.008s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.010s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.010s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.013s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.009s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.010s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.010s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.047s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.008s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.011s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.012s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.010s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.008s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.012s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.012s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.016s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.....E
======================================================================
ERROR: test_write_csv_6 (ClassEval_26_0.CSVProcessorTestWriteCSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_26_0.py", line 216, in test_write_csv_6
    self.assertEqual(0, csvProcessor.write_csv([], file_path))
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_26_0.py", line 37, in write_csv
    with open(file_name, 'w', newline='') as file:
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.006s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
.....E
======================================================================
ERROR: test_write_csv_6 (ClassEval_26_1.CSVProcessorTestWriteCSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_26_1.py", line 201, in test_write_csv_6
    self.assertEqual(0, csvProcessor.write_csv([], file_path))
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_26_1.py", line 31, in write_csv
    with open(file_name, 'w', newline='') as file:
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.005s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
.....E
======================================================================
ERROR: test_write_csv_6 (ClassEval_26_2.CSVProcessorTestWriteCSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_26_2.py", line 216, in test_write_csv_6
    self.assertEqual(0, csvProcessor.write_csv([], file_path))
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_26_2.py", line 37, in write_csv
    with open(file_name, 'w', newline='') as file:
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.005s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....E
======================================================================
ERROR: test_write_csv_6 (ClassEval_26_3.CSVProcessorTestWriteCSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_26_3.py", line 215, in test_write_csv_6
    self.assertEqual(0, csvProcessor.write_csv([], file_path))
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_26_3.py", line 37, in write_csv
    with open(file_name, 'w', newline='') as file:
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.005s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
.....E
======================================================================
ERROR: test_write_csv_6 (ClassEval_26_4.CSVProcessorTestWriteCSV)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_26_4.py", line 215, in test_write_csv_6
    self.assertEqual(0, csvProcessor.write_csv([], file_path))
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_26_4.py", line 37, in write_csv
    with open(file_name, 'w', newline='') as file:
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.005s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.015s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.010s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.018s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.014s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.019s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.010s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.012s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.010s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
EEEEE
======================================================================
ERROR: test_process_file_1 (ClassEval_84_0.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_0.py", line 213, in test_process_file_1
    result = textFileProcessor.process_file()
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_0.py", line 59, in process_file
    with open(self.file_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

======================================================================
ERROR: test_process_file_2 (ClassEval_84_0.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_0.py", line 227, in test_process_file_2
    result = textFileProcessor.process_file()
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_0.py", line 59, in process_file
    with open(self.file_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

======================================================================
ERROR: test_process_file_3 (ClassEval_84_0.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_0.py", line 241, in test_process_file_3
    result = textFileProcessor.process_file()
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_0.py", line 59, in process_file
    with open(self.file_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

======================================================================
ERROR: test_process_file_4 (ClassEval_84_0.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_0.py", line 255, in test_process_file_4
    result = textFileProcessor.process_file()
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_0.py", line 59, in process_file
    with open(self.file_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

======================================================================
ERROR: test_process_file_5 (ClassEval_84_0.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_0.py", line 269, in test_process_file_5
    result = textFileProcessor.process_file()
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_0.py", line 59, in process_file
    with open(self.file_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (errors=5)
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.010s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.009s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
FFFFF
======================================================================
FAIL: test_process_file_1 (ClassEval_84_1.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_1.py", line 214, in test_process_file_1
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloWorld'
- nametestage
+ HelloWorld


======================================================================
FAIL: test_process_file_2 (ClassEval_84_1.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_1.py", line 228, in test_process_file_2
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloabcWorld'
- nametestage
+ HelloabcWorld


======================================================================
FAIL: test_process_file_3 (ClassEval_84_1.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_1.py", line 242, in test_process_file_3
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != ''
- nametestage
+ 


======================================================================
FAIL: test_process_file_4 (ClassEval_84_1.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_1.py", line 256, in test_process_file_4
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloWorld'
- nametestage
+ HelloWorld


======================================================================
FAIL: test_process_file_5 (ClassEval_84_1.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_1.py", line 270, in test_process_file_5
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloaWorld'
- nametestage
+ HelloaWorld


----------------------------------------------------------------------
Ran 5 tests in 0.005s

FAILED (failures=5)
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.010s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
FFFFF
======================================================================
FAIL: test_process_file_1 (ClassEval_84_2.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_2.py", line 214, in test_process_file_1
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloWorld'
- nametestage
+ HelloWorld


======================================================================
FAIL: test_process_file_2 (ClassEval_84_2.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_2.py", line 228, in test_process_file_2
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloabcWorld'
- nametestage
+ HelloabcWorld


======================================================================
FAIL: test_process_file_3 (ClassEval_84_2.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_2.py", line 242, in test_process_file_3
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != ''
- nametestage
+ 


======================================================================
FAIL: test_process_file_4 (ClassEval_84_2.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_2.py", line 256, in test_process_file_4
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloWorld'
- nametestage
+ HelloWorld


======================================================================
FAIL: test_process_file_5 (ClassEval_84_2.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_2.py", line 270, in test_process_file_5
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloaWorld'
- nametestage
+ HelloaWorld


----------------------------------------------------------------------
Ran 5 tests in 0.006s

FAILED (failures=5)
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.010s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
FFFFF
======================================================================
FAIL: test_process_file_1 (ClassEval_84_3.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_3.py", line 222, in test_process_file_1
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloWorld'
- nametestage
+ HelloWorld


======================================================================
FAIL: test_process_file_2 (ClassEval_84_3.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_3.py", line 236, in test_process_file_2
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloabcWorld'
- nametestage
+ HelloabcWorld


======================================================================
FAIL: test_process_file_3 (ClassEval_84_3.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_3.py", line 250, in test_process_file_3
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != ''
- nametestage
+ 


======================================================================
FAIL: test_process_file_4 (ClassEval_84_3.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_3.py", line 264, in test_process_file_4
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloWorld'
- nametestage
+ HelloWorld


======================================================================
FAIL: test_process_file_5 (ClassEval_84_3.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_3.py", line 278, in test_process_file_5
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloaWorld'
- nametestage
+ HelloaWorld


----------------------------------------------------------------------
Ran 5 tests in 0.005s

FAILED (failures=5)
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.010s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
FFFFF
======================================================================
FAIL: test_process_file_1 (ClassEval_84_4.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_4.py", line 214, in test_process_file_1
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloWorld'
- nametestage
+ HelloWorld


======================================================================
FAIL: test_process_file_2 (ClassEval_84_4.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_4.py", line 228, in test_process_file_2
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloabcWorld'
- nametestage
+ HelloabcWorld


======================================================================
FAIL: test_process_file_3 (ClassEval_84_4.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_4.py", line 242, in test_process_file_3
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != ''
- nametestage
+ 


======================================================================
FAIL: test_process_file_4 (ClassEval_84_4.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_4.py", line 256, in test_process_file_4
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloWorld'
- nametestage
+ HelloWorld


======================================================================
FAIL: test_process_file_5 (ClassEval_84_4.TextFileProcessorTestProcessFile)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_84_4.py", line 270, in test_process_file_5
    self.assertEqual(result, self.expected_result)
AssertionError: 'nametestage' != 'HelloaWorld'
- nametestage
+ HelloaWorld


----------------------------------------------------------------------
Ran 5 tests in 0.005s

FAILED (failures=5)
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
.....E
======================================================================
ERROR: test_read_xml_6 (ClassEval_98_0.XMLProcessorTestReadXml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_0.py", line 167, in test_read_xml_6
    root = self.processor.read_xml()
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_0.py", line 23, in read_xml
    tree = ET.parse(self.file_name)
  File "C:\Users\tanuj\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "C:\Users\tanuj\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.007s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.011s

OK
FFFFF
======================================================================
FAIL: test_process_xml_data_1 (ClassEval_98_0.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_0.py", line 320, in test_process_xml_data_1
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_2 (ClassEval_98_0.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_0.py", line 345, in test_process_xml_data_2
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_3 (ClassEval_98_0.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_0.py", line 369, in test_process_xml_data_3
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_4 (ClassEval_98_0.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_0.py", line 392, in test_process_xml_data_4
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_5 (ClassEval_98_0.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_0.py", line 416, in test_process_xml_data_5
    self.assertEqual(lst[0].text, 'AAA')
AssertionError: 'aaa' != 'AAA'
- aaa
+ AAA


----------------------------------------------------------------------
Ran 5 tests in 0.007s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
F
======================================================================
FAIL: test_XMLProcessor (ClassEval_98_0.XMLProcessorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_0.py", line 554, in test_XMLProcessor
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (failures=1)
.....E
======================================================================
ERROR: test_read_xml_6 (ClassEval_98_1.XMLProcessorTestReadXml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_1.py", line 178, in test_read_xml_6
    root = self.processor.read_xml()
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_1.py", line 28, in read_xml
    tree = ET.parse(self.file_name)
  File "C:\Users\tanuj\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "C:\Users\tanuj\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.006s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.013s

OK
FFFFF
======================================================================
FAIL: test_process_xml_data_1 (ClassEval_98_1.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_1.py", line 331, in test_process_xml_data_1
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_2 (ClassEval_98_1.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_1.py", line 356, in test_process_xml_data_2
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_3 (ClassEval_98_1.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_1.py", line 380, in test_process_xml_data_3
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_4 (ClassEval_98_1.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_1.py", line 403, in test_process_xml_data_4
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_5 (ClassEval_98_1.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_1.py", line 427, in test_process_xml_data_5
    self.assertEqual(lst[0].text, 'AAA')
AssertionError: 'aaa' != 'AAA'
- aaa
+ AAA


----------------------------------------------------------------------
Ran 5 tests in 0.010s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.011s

OK
F
======================================================================
FAIL: test_XMLProcessor (ClassEval_98_1.XMLProcessorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_1.py", line 565, in test_XMLProcessor
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (failures=1)
.....E
======================================================================
ERROR: test_read_xml_6 (ClassEval_98_2.XMLProcessorTestReadXml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_2.py", line 170, in test_read_xml_6
    root = self.processor.read_xml()
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_2.py", line 28, in read_xml
    tree = ET.parse(self.file_name)
  File "C:\Users\tanuj\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "C:\Users\tanuj\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.009s

FAILED (errors=1)
.....E
======================================================================
ERROR: test_write_xml_6 (ClassEval_98_2.XMLProcessorTestWriteXml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 762, in _get_writer
    write = file_or_filename.write
AttributeError: 'str' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_2.py", line 300, in test_write_xml_6
    result = self.processor.write_xml("")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_2.py", line 44, in write_xml
    tree.write(file_name)
  File "C:\Users\tanuj\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 732, in write
    with _get_writer(file_or_filename, enc_lower) as write:
  File "C:\Users\tanuj\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\tanuj\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 768, in _get_writer
    file = open(file_or_filename, "w", encoding=encoding,
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.022s

FAILED (errors=1)
FFFFF
======================================================================
FAIL: test_process_xml_data_1 (ClassEval_98_2.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_2.py", line 323, in test_process_xml_data_1
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_2 (ClassEval_98_2.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_2.py", line 348, in test_process_xml_data_2
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_3 (ClassEval_98_2.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_2.py", line 372, in test_process_xml_data_3
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_4 (ClassEval_98_2.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_2.py", line 395, in test_process_xml_data_4
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_5 (ClassEval_98_2.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_2.py", line 419, in test_process_xml_data_5
    self.assertEqual(lst[0].text, 'AAA')
AssertionError: 'aaa' != 'AAA'
- aaa
+ AAA


----------------------------------------------------------------------
Ran 5 tests in 0.016s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.010s

OK
F
======================================================================
FAIL: test_XMLProcessor (ClassEval_98_2.XMLProcessorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_2.py", line 557, in test_XMLProcessor
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
.....E
======================================================================
ERROR: test_read_xml_6 (ClassEval_98_3.XMLProcessorTestReadXml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_3.py", line 170, in test_read_xml_6
    root = self.processor.read_xml()
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_3.py", line 23, in read_xml
    tree = ET.parse(self.file_name)
  File "C:\Users\tanuj\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "C:\Users\tanuj\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.010s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.009s

OK
FFFFF
======================================================================
FAIL: test_process_xml_data_1 (ClassEval_98_3.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_3.py", line 323, in test_process_xml_data_1
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_2 (ClassEval_98_3.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_3.py", line 348, in test_process_xml_data_2
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_3 (ClassEval_98_3.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_3.py", line 372, in test_process_xml_data_3
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_4 (ClassEval_98_3.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_3.py", line 395, in test_process_xml_data_4
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_5 (ClassEval_98_3.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_3.py", line 419, in test_process_xml_data_5
    self.assertEqual(lst[0].text, 'AAA')
AssertionError: 'aaa' != 'AAA'
- aaa
+ AAA


----------------------------------------------------------------------
Ran 5 tests in 0.008s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.006s

OK
F
======================================================================
FAIL: test_XMLProcessor (ClassEval_98_3.XMLProcessorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_3.py", line 557, in test_XMLProcessor
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (failures=1)
.....E
======================================================================
ERROR: test_read_xml_6 (ClassEval_98_4.XMLProcessorTestReadXml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_4.py", line 168, in test_read_xml_6
    root = self.processor.read_xml()
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_4.py", line 23, in read_xml
    tree = ET.parse(self.file_name)
  File "C:\Users\tanuj\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "C:\Users\tanuj\AppData\Local\Programs\Python\Python310\lib\xml\etree\ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: ''

----------------------------------------------------------------------
Ran 6 tests in 0.012s

FAILED (errors=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.017s

OK
FFFFF
======================================================================
FAIL: test_process_xml_data_1 (ClassEval_98_4.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_4.py", line 321, in test_process_xml_data_1
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_2 (ClassEval_98_4.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_4.py", line 346, in test_process_xml_data_2
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_3 (ClassEval_98_4.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_4.py", line 370, in test_process_xml_data_3
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_4 (ClassEval_98_4.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_4.py", line 393, in test_process_xml_data_4
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


======================================================================
FAIL: test_process_xml_data_5 (ClassEval_98_4.XMLProcessorTestProcessXmlData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_4.py", line 417, in test_process_xml_data_5
    self.assertEqual(lst[0].text, 'AAA')
AssertionError: 'aaa' != 'AAA'
- aaa
+ AAA


----------------------------------------------------------------------
Ran 5 tests in 0.012s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.005s

OK
F
======================================================================
FAIL: test_XMLProcessor (ClassEval_98_4.XMLProcessorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_98_4.py", line 555, in test_XMLProcessor
    self.assertEqual(lst[0].text, 'APPLE')
AssertionError: 'apple' != 'APPLE'
- apple
+ APPLE


----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (failures=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.024s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.019s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.015s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.013s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.010s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.013s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.014s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.012s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.010s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.014s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.016s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.016s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.006s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.023s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.025s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.032s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.017s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.060s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.034s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.042s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.031s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.025s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
