.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....F
======================================================================
FAIL: test_convert_type_5 (ClassEval_2_1.ArgumentParserTestConvertType)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_2_1.py", line 299, in test_convert_type_5
    self.assertEqual(result, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
F
======================================================================
FAIL: test_main (ClassEval_2_1.ArgumentParserTestMain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_2_1.py", line 316, in test_main
    self.assertEqual(parser.arguments, arguments)
AssertionError: {'arg1': 21, 'option1': 'True', 'arg2': 'value', 'option2': 'True'} != {'arg1': 21, 'option1': True, 'arg2': 'value', 'option2': True}
- {'arg1': 21, 'arg2': 'value', 'option1': 'True', 'option2': 'True'}
?                                          -    -             -    -

+ {'arg1': 21, 'arg2': 'value', 'option1': True, 'option2': True}

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....F
======================================================================
FAIL: test_convert_type_5 (ClassEval_2_2.ArgumentParserTestConvertType)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_2_2.py", line 286, in test_convert_type_5
    self.assertEqual(result, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.003s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....F
======================================================================
FAIL: test_convert_type_5 (ClassEval_2_3.ArgumentParserTestConvertType)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_2_3.py", line 276, in test_convert_type_5
    self.assertEqual(result, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
FF...
======================================================================
FAIL: test_parse_arguments_1 (ClassEval_2_4.ArgumentParserTestParseArguments)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_2_4.py", line 116, in test_parse_arguments_1
    self.assertEqual(self.parser.get_argument("name"), "John")
AssertionError: None != 'John'

======================================================================
FAIL: test_parse_arguments_2 (ClassEval_2_4.ArgumentParserTestParseArguments)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_2_4.py", line 129, in test_parse_arguments_2
    self.assertEqual(self.parser.get_argument("verbose"), True)
AssertionError: None != True

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
F
======================================================================
FAIL: test_main (ClassEval_2_4.ArgumentParserTestMain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_2_4.py", line 293, in test_main
    self.assertEqual(parser.arguments, arguments)
AssertionError: {'option1': True, 'arg2': 'value', 'option2': True} != {'arg1': 21, 'option1': True, 'arg2': 'value', 'option2': True}
- {'arg2': 'value', 'option1': True, 'option2': True}
+ {'arg1': 21, 'arg2': 'value', 'option1': True, 'option2': True}
?  ++++++++++++


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.FF.F
======================================================================
FAIL: test_calculate_binary_info_2 (ClassEval_10_0.BinaryDataProcessorTestCalculateBinaryInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_10_0.py", line 109, in test_calculate_binary_info_2
    self.assertEqual(bdp.calculate_binary_info(), {'Bit length': 28, 'Ones': 0.5357142857142857, 'Zeroes': 0.4642857142857143})
AssertionError: {'Zeroes': 0.464, 'Ones': 0.536, 'Bit length': 28} != {'Bit length': 28, 'Ones': 0.5357142857142857, 'Zeroes': 0.4642857142857143}
- {'Bit length': 28, 'Ones': 0.536, 'Zeroes': 0.464}
?                                ^

+ {'Bit length': 28, 'Ones': 0.5357142857142857, 'Zeroes': 0.4642857142857143}
?                                ^^^^^^^^^^^^^^                 +++++++++++++


======================================================================
FAIL: test_calculate_binary_info_3 (ClassEval_10_0.BinaryDataProcessorTestCalculateBinaryInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_10_0.py", line 113, in test_calculate_binary_info_3
    self.assertEqual(bdp.calculate_binary_info(), {'Bit length': 29, 'Ones': 0.6206896551724138, 'Zeroes': 0.3793103448275862})
AssertionError: {'Zeroes': 0.379, 'Ones': 0.621, 'Bit length': 29} != {'Bit length': 29, 'Ones': 0.6206896551724138, 'Zeroes': 0.3793103448275862}
- {'Bit length': 29, 'Ones': 0.621, 'Zeroes': 0.379}
+ {'Bit length': 29, 'Ones': 0.6206896551724138, 'Zeroes': 0.3793103448275862}
?                                +++++++ ++++++                 +++++++++++++


======================================================================
FAIL: test_calculate_binary_info_5 (ClassEval_10_0.BinaryDataProcessorTestCalculateBinaryInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_10_0.py", line 121, in test_calculate_binary_info_5
    self.assertEqual(bdp.calculate_binary_info(), {'Bit length': 16, 'Ones': 0.5625, 'Zeroes': 0.4375})
AssertionError: {'Zeroes': 0.438, 'Ones': 0.562, 'Bit length': 16} != {'Bit length': 16, 'Ones': 0.5625, 'Zeroes': 0.4375}
- {'Bit length': 16, 'Ones': 0.562, 'Zeroes': 0.438}
?                                                 ^

+ {'Bit length': 16, 'Ones': 0.5625, 'Zeroes': 0.4375}
?                                 +                ^^


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.FF.F
======================================================================
FAIL: test_calculate_binary_info_2 (ClassEval_10_1.BinaryDataProcessorTestCalculateBinaryInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_10_1.py", line 103, in test_calculate_binary_info_2
    self.assertEqual(bdp.calculate_binary_info(), {'Bit length': 28, 'Ones': 0.5357142857142857, 'Zeroes': 0.4642857142857143})
AssertionError: {'Zeroes': 0.464, 'Ones': 0.536, 'Bit length': 28} != {'Bit length': 28, 'Ones': 0.5357142857142857, 'Zeroes': 0.4642857142857143}
- {'Bit length': 28, 'Ones': 0.536, 'Zeroes': 0.464}
?                                ^

+ {'Bit length': 28, 'Ones': 0.5357142857142857, 'Zeroes': 0.4642857142857143}
?                                ^^^^^^^^^^^^^^                 +++++++++++++


======================================================================
FAIL: test_calculate_binary_info_3 (ClassEval_10_1.BinaryDataProcessorTestCalculateBinaryInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_10_1.py", line 107, in test_calculate_binary_info_3
    self.assertEqual(bdp.calculate_binary_info(), {'Bit length': 29, 'Ones': 0.6206896551724138, 'Zeroes': 0.3793103448275862})
AssertionError: {'Zeroes': 0.379, 'Ones': 0.621, 'Bit length': 29} != {'Bit length': 29, 'Ones': 0.6206896551724138, 'Zeroes': 0.3793103448275862}
- {'Bit length': 29, 'Ones': 0.621, 'Zeroes': 0.379}
+ {'Bit length': 29, 'Ones': 0.6206896551724138, 'Zeroes': 0.3793103448275862}
?                                +++++++ ++++++                 +++++++++++++


======================================================================
FAIL: test_calculate_binary_info_5 (ClassEval_10_1.BinaryDataProcessorTestCalculateBinaryInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_10_1.py", line 115, in test_calculate_binary_info_5
    self.assertEqual(bdp.calculate_binary_info(), {'Bit length': 16, 'Ones': 0.5625, 'Zeroes': 0.4375})
AssertionError: {'Zeroes': 0.438, 'Ones': 0.562, 'Bit length': 16} != {'Bit length': 16, 'Ones': 0.5625, 'Zeroes': 0.4375}
- {'Bit length': 16, 'Ones': 0.562, 'Zeroes': 0.438}
?                                                 ^

+ {'Bit length': 16, 'Ones': 0.5625, 'Zeroes': 0.4375}
?                                 +                ^^


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.FF.F
======================================================================
FAIL: test_calculate_binary_info_2 (ClassEval_10_2.BinaryDataProcessorTestCalculateBinaryInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_10_2.py", line 110, in test_calculate_binary_info_2
    self.assertEqual(bdp.calculate_binary_info(), {'Bit length': 28, 'Ones': 0.5357142857142857, 'Zeroes': 0.4642857142857143})
AssertionError: {'Zeroes': 0.464, 'Ones': 0.536, 'Bit length': 28} != {'Bit length': 28, 'Ones': 0.5357142857142857, 'Zeroes': 0.4642857142857143}
- {'Bit length': 28, 'Ones': 0.536, 'Zeroes': 0.464}
?                                ^

+ {'Bit length': 28, 'Ones': 0.5357142857142857, 'Zeroes': 0.4642857142857143}
?                                ^^^^^^^^^^^^^^                 +++++++++++++


======================================================================
FAIL: test_calculate_binary_info_3 (ClassEval_10_2.BinaryDataProcessorTestCalculateBinaryInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_10_2.py", line 114, in test_calculate_binary_info_3
    self.assertEqual(bdp.calculate_binary_info(), {'Bit length': 29, 'Ones': 0.6206896551724138, 'Zeroes': 0.3793103448275862})
AssertionError: {'Zeroes': 0.379, 'Ones': 0.621, 'Bit length': 29} != {'Bit length': 29, 'Ones': 0.6206896551724138, 'Zeroes': 0.3793103448275862}
- {'Bit length': 29, 'Ones': 0.621, 'Zeroes': 0.379}
+ {'Bit length': 29, 'Ones': 0.6206896551724138, 'Zeroes': 0.3793103448275862}
?                                +++++++ ++++++                 +++++++++++++


======================================================================
FAIL: test_calculate_binary_info_5 (ClassEval_10_2.BinaryDataProcessorTestCalculateBinaryInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_10_2.py", line 122, in test_calculate_binary_info_5
    self.assertEqual(bdp.calculate_binary_info(), {'Bit length': 16, 'Ones': 0.5625, 'Zeroes': 0.4375})
AssertionError: {'Zeroes': 0.438, 'Ones': 0.562, 'Bit length': 16} != {'Bit length': 16, 'Ones': 0.5625, 'Zeroes': 0.4375}
- {'Bit length': 16, 'Ones': 0.562, 'Zeroes': 0.438}
?                                                 ^

+ {'Bit length': 16, 'Ones': 0.5625, 'Zeroes': 0.4375}
?                                 +                ^^


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.FF.F
======================================================================
FAIL: test_calculate_binary_info_2 (ClassEval_10_3.BinaryDataProcessorTestCalculateBinaryInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_10_3.py", line 106, in test_calculate_binary_info_2
    self.assertEqual(bdp.calculate_binary_info(), {'Bit length': 28, 'Ones': 0.5357142857142857, 'Zeroes': 0.4642857142857143})
AssertionError: {'Zeroes': 0.464, 'Ones': 0.536, 'Bit length': 28} != {'Bit length': 28, 'Ones': 0.5357142857142857, 'Zeroes': 0.4642857142857143}
- {'Bit length': 28, 'Ones': 0.536, 'Zeroes': 0.464}
?                                ^

+ {'Bit length': 28, 'Ones': 0.5357142857142857, 'Zeroes': 0.4642857142857143}
?                                ^^^^^^^^^^^^^^                 +++++++++++++


======================================================================
FAIL: test_calculate_binary_info_3 (ClassEval_10_3.BinaryDataProcessorTestCalculateBinaryInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_10_3.py", line 110, in test_calculate_binary_info_3
    self.assertEqual(bdp.calculate_binary_info(), {'Bit length': 29, 'Ones': 0.6206896551724138, 'Zeroes': 0.3793103448275862})
AssertionError: {'Zeroes': 0.379, 'Ones': 0.621, 'Bit length': 29} != {'Bit length': 29, 'Ones': 0.6206896551724138, 'Zeroes': 0.3793103448275862}
- {'Bit length': 29, 'Ones': 0.621, 'Zeroes': 0.379}
+ {'Bit length': 29, 'Ones': 0.6206896551724138, 'Zeroes': 0.3793103448275862}
?                                +++++++ ++++++                 +++++++++++++


======================================================================
FAIL: test_calculate_binary_info_5 (ClassEval_10_3.BinaryDataProcessorTestCalculateBinaryInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_10_3.py", line 118, in test_calculate_binary_info_5
    self.assertEqual(bdp.calculate_binary_info(), {'Bit length': 16, 'Ones': 0.5625, 'Zeroes': 0.4375})
AssertionError: {'Zeroes': 0.438, 'Ones': 0.562, 'Bit length': 16} != {'Bit length': 16, 'Ones': 0.5625, 'Zeroes': 0.4375}
- {'Bit length': 16, 'Ones': 0.562, 'Zeroes': 0.438}
?                                                 ^

+ {'Bit length': 16, 'Ones': 0.5625, 'Zeroes': 0.4375}
?                                 +                ^^


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.FF.F
======================================================================
FAIL: test_calculate_binary_info_2 (ClassEval_10_4.BinaryDataProcessorTestCalculateBinaryInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_10_4.py", line 119, in test_calculate_binary_info_2
    self.assertEqual(bdp.calculate_binary_info(), {'Bit length': 28, 'Ones': 0.5357142857142857, 'Zeroes': 0.4642857142857143})
AssertionError: {'Zeroes': 0.464, 'Ones': 0.536, 'Bit length': 28} != {'Bit length': 28, 'Ones': 0.5357142857142857, 'Zeroes': 0.4642857142857143}
- {'Bit length': 28, 'Ones': 0.536, 'Zeroes': 0.464}
?                                ^

+ {'Bit length': 28, 'Ones': 0.5357142857142857, 'Zeroes': 0.4642857142857143}
?                                ^^^^^^^^^^^^^^                 +++++++++++++


======================================================================
FAIL: test_calculate_binary_info_3 (ClassEval_10_4.BinaryDataProcessorTestCalculateBinaryInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_10_4.py", line 123, in test_calculate_binary_info_3
    self.assertEqual(bdp.calculate_binary_info(), {'Bit length': 29, 'Ones': 0.6206896551724138, 'Zeroes': 0.3793103448275862})
AssertionError: {'Zeroes': 0.379, 'Ones': 0.621, 'Bit length': 29} != {'Bit length': 29, 'Ones': 0.6206896551724138, 'Zeroes': 0.3793103448275862}
- {'Bit length': 29, 'Ones': 0.621, 'Zeroes': 0.379}
+ {'Bit length': 29, 'Ones': 0.6206896551724138, 'Zeroes': 0.3793103448275862}
?                                +++++++ ++++++                 +++++++++++++


======================================================================
FAIL: test_calculate_binary_info_5 (ClassEval_10_4.BinaryDataProcessorTestCalculateBinaryInfo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_10_4.py", line 131, in test_calculate_binary_info_5
    self.assertEqual(bdp.calculate_binary_info(), {'Bit length': 16, 'Ones': 0.5625, 'Zeroes': 0.4375})
AssertionError: {'Zeroes': 0.438, 'Ones': 0.562, 'Bit length': 16} != {'Bit length': 16, 'Ones': 0.5625, 'Zeroes': 0.4375}
- {'Bit length': 16, 'Ones': 0.562, 'Zeroes': 0.438}
?                                                 ^

+ {'Bit length': 16, 'Ones': 0.5625, 'Zeroes': 0.4375}
?                                 +                ^^


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....F
======================================================================
FAIL: test_mismatch_in_text_5 (ClassEval_15_0.BoyerMooreSearchTestMismatchInText)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_15_0.py", line 132, in test_mismatch_in_text_5
    self.assertEqual(boyerMooreSearch.mismatch_in_text(3), 5)
AssertionError: 2 != 5

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..E..
======================================================================
ERROR: test_bad_character_heuristic_3 (ClassEval_15_1.BoyerMooreSearchTestBadCharacterHeuristic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_15_1.py", line 139, in test_bad_character_heuristic_3
    self.assertEqual(boyerMooreSearch.bad_character_heuristic(), [0, 1, 2, 3, 4, 5, 6])
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_15_1.py", line 61, in bad_character_heuristic
    while s <= self.textLen - self.patLen:
func_timeout.dafunc.FunctionTimedOut-5341281349368360914: Function run_unit_test (args=(<test_pipeline.AutoTest object at 0x00000204AE93E440>, 'ClassEval_15_1', 'BoyerMooreSearchTestBadCharacterHeuristic', 'Chatgpt-o4-mini_Data_Formatting')) (kwargs={}) timed out after 5.000000 seconds.


----------------------------------------------------------------------
Ran 5 tests in 5.071s

FAILED (errors=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....F
======================================================================
FAIL: test_mismatch_in_text_5 (ClassEval_15_2.BoyerMooreSearchTestMismatchInText)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_15_2.py", line 119, in test_mismatch_in_text_5
    self.assertEqual(boyerMooreSearch.mismatch_in_text(3), 5)
AssertionError: 2 != 5

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....F
======================================================================
FAIL: test_mismatch_in_text_5 (ClassEval_15_3.BoyerMooreSearchTestMismatchInText)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_15_3.py", line 119, in test_mismatch_in_text_5
    self.assertEqual(boyerMooreSearch.mismatch_in_text(3), 5)
AssertionError: 2 != 5

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....F
======================================================================
FAIL: test_mismatch_in_text_5 (ClassEval_15_4.BoyerMooreSearchTestMismatchInText)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_15_4.py", line 125, in test_mismatch_in_text_5
    self.assertEqual(boyerMooreSearch.mismatch_in_text(3), 5)
AssertionError: 2 != 5

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....E
======================================================================
ERROR: test_convert_key_6 (ClassEval_18_0.CamelCaseMapTestConvertKey)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_18_0.py", line 293, in test_convert_key_6
    self.assertEqual(camelize_map._convert_key(1234), 1234)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_18_0.py", line 53, in _convert_key
    raise KeyError("Keys must be strings")
KeyError: 'Keys must be strings'

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....E
======================================================================
ERROR: test_convert_key_6 (ClassEval_18_1.CamelCaseMapTestConvertKey)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_18_1.py", line 286, in test_convert_key_6
    self.assertEqual(camelize_map._convert_key(1234), 1234)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_18_1.py", line 63, in _convert_key
    raise TypeError("Keys must be strings")
TypeError: Keys must be strings

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....E
======================================================================
ERROR: test_convert_key_6 (ClassEval_18_3.CamelCaseMapTestConvertKey)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_18_3.py", line 271, in test_convert_key_6
    self.assertEqual(camelize_map._convert_key(1234), 1234)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_18_3.py", line 44, in _convert_key
    raise TypeError("Keys must be strings")
TypeError: Keys must be strings

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....E
======================================================================
ERROR: test_convert_6 (ClassEval_27_0.CurrencyConverterTestConvert)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_27_0.py", line 111, in test_convert_6
    res = cc.convert(64, '???', 'USD')
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_27_0.py", line 35, in convert
    raise ValueError(f"Unsupported source currency: {from_currency}")
ValueError: Unsupported source currency: ???

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....E
======================================================================
ERROR: test_convert_6 (ClassEval_27_1.CurrencyConverterTestConvert)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_27_1.py", line 108, in test_convert_6
    res = cc.convert(64, '???', 'USD')
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_27_1.py", line 33, in convert
    raise ValueError(f"Unsupported source currency: {from_currency}")
ValueError: Unsupported source currency: ???

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....E
======================================================================
ERROR: test_convert_6 (ClassEval_27_2.CurrencyConverterTestConvert)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_27_2.py", line 113, in test_convert_6
    res = cc.convert(64, '???', 'USD')
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_27_2.py", line 36, in convert
    raise ValueError(f"Unsupported currency: {from_currency}")
ValueError: Unsupported currency: ???

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....E
======================================================================
ERROR: test_convert_6 (ClassEval_27_3.CurrencyConverterTestConvert)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_27_3.py", line 111, in test_convert_6
    res = cc.convert(64, '???', 'USD')
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_27_3.py", line 34, in convert
    raise ValueError(f"Unsupported source currency: {from_currency}")
ValueError: Unsupported source currency: ???

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....E
======================================================================
ERROR: test_convert_6 (ClassEval_27_4.CurrencyConverterTestConvert)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_27_4.py", line 111, in test_convert_6
    res = cc.convert(64, '???', 'USD')
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_27_4.py", line 35, in convert
    raise ValueError(f"Unsupported source currency: {from_currency}")
ValueError: Unsupported source currency: ???

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F.E
======================================================================
ERROR: test_interpolate_1d_7 (ClassEval_46_0.InterpolationTestInterpolate1d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_0.py", line 151, in test_interpolate_1d_7
    self.assertEqual(interpolation.interpolate_1d([], [], [[], []]), [])
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_0.py", line 28, in interpolate_1d
    raise ValueError("At least two data points are required for interpolation")
ValueError: At least two data points are required for interpolation

======================================================================
FAIL: test_interpolate_1d_5 (ClassEval_46_0.InterpolationTestInterpolate1d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_0.py", line 143, in test_interpolate_1d_5
    self.assertEqual(interpolation.interpolate_1d([1, 6, 4], [1, 7, 5], [2, 3]), [2.2, 3.4])
AssertionError: Lists differ: [2.2, 3.4000000000000004] != [2.2, 3.4]

First differing element 1:
3.4000000000000004
3.4

- [2.2, 3.4000000000000004]
+ [2.2, 3.4]

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=1, errors=1)
.EEE.
======================================================================
ERROR: test_interpolate_2d_2 (ClassEval_46_0.InterpolationTestInterpolate2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_0.py", line 164, in test_interpolate_2d_2
    interpolation.interpolate_2d([1, 2, 3], [1, 2, 3], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1.5, 2.5], [3, 4]),
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_0.py", line 97, in interpolate_2d
    raise ValueError(f"yi={yi} is outside y-range [{y[0]}, {y[-1]}]")
ValueError: yi=4 is outside y-range [1, 3]

======================================================================
ERROR: test_interpolate_2d_3 (ClassEval_46_0.InterpolationTestInterpolate2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_0.py", line 170, in test_interpolate_2d_3
    interpolation.interpolate_2d([1, 2, 3], [1, 2, 3], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [3, 4], [1.5, 2.5]),
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_0.py", line 88, in interpolate_2d
    raise ValueError(f"xi={xi} is outside x-range [{x[0]}, {x[-1]}]")
ValueError: xi=4 is outside x-range [1, 3]

======================================================================
ERROR: test_interpolate_2d_4 (ClassEval_46_0.InterpolationTestInterpolate2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_0.py", line 176, in test_interpolate_2d_4
    interpolation.interpolate_2d([1, 2, 3], [1, 2, 3], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [3, 4], [3, 4]),
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_0.py", line 88, in interpolate_2d
    raise ValueError(f"xi={xi} is outside x-range [{x[0]}, {x[-1]}]")
ValueError: xi=4 is outside x-range [1, 3]

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=3)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F.E
======================================================================
ERROR: test_interpolate_1d_7 (ClassEval_46_1.InterpolationTestInterpolate1d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_1.py", line 157, in test_interpolate_1d_7
    self.assertEqual(interpolation.interpolate_1d([], [], [[], []]), [])
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_1.py", line 26, in interpolate_1d
    raise ValueError("Need at least two data points for interpolation")
ValueError: Need at least two data points for interpolation

======================================================================
FAIL: test_interpolate_1d_5 (ClassEval_46_1.InterpolationTestInterpolate1d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_1.py", line 149, in test_interpolate_1d_5
    self.assertEqual(interpolation.interpolate_1d([1, 6, 4], [1, 7, 5], [2, 3]), [2.2, 3.4])
AssertionError: Lists differ: [2.2, 3.4000000000000004] != [2.2, 3.4]

First differing element 1:
3.4000000000000004
3.4

- [2.2, 3.4000000000000004]
+ [2.2, 3.4]

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=1, errors=1)
.FFF.
======================================================================
FAIL: test_interpolate_2d_2 (ClassEval_46_1.InterpolationTestInterpolate2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_1.py", line 169, in test_interpolate_2d_2
    self.assertEqual(
AssertionError: Lists differ: [7.5, 11.5] != [4.5]

First differing element 0:
7.5
4.5

First list contains 1 additional elements.
First extra element 1:
11.5

- [7.5, 11.5]
+ [4.5]

======================================================================
FAIL: test_interpolate_2d_3 (ClassEval_46_1.InterpolationTestInterpolate2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_1.py", line 175, in test_interpolate_2d_3
    self.assertEqual(
AssertionError: Lists differ: [4.5, 8.5] != [7.5]

First differing element 0:
4.5
7.5

First list contains 1 additional elements.
First extra element 1:
8.5

- [4.5, 8.5]
+ [7.5]

======================================================================
FAIL: test_interpolate_2d_4 (ClassEval_46_1.InterpolationTestInterpolate2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_1.py", line 181, in test_interpolate_2d_4
    self.assertEqual(
AssertionError: Lists differ: [9.0, 13.0] != [9.0]

First list contains 1 additional elements.
First extra element 1:
13.0

- [9.0, 13.0]
+ [9.0]

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F.E
======================================================================
ERROR: test_interpolate_1d_7 (ClassEval_46_2.InterpolationTestInterpolate1d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_2.py", line 154, in test_interpolate_1d_7
    self.assertEqual(interpolation.interpolate_1d([], [], [[], []]), [])
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_2.py", line 33, in interpolate_1d
    y_interp.append(y[0])
IndexError: list index out of range

======================================================================
FAIL: test_interpolate_1d_5 (ClassEval_46_2.InterpolationTestInterpolate1d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_2.py", line 146, in test_interpolate_1d_5
    self.assertEqual(interpolation.interpolate_1d([1, 6, 4], [1, 7, 5], [2, 3]), [2.2, 3.4])
AssertionError: Lists differ: [2.2, 3.4000000000000004] != [2.2, 3.4]

First differing element 1:
3.4000000000000004
3.4

- [2.2, 3.4000000000000004]
+ [2.2, 3.4]

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=1, errors=1)
.FFF.
======================================================================
FAIL: test_interpolate_2d_2 (ClassEval_46_2.InterpolationTestInterpolate2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_2.py", line 166, in test_interpolate_2d_2
    self.assertEqual(
AssertionError: Lists differ: [7.5, 11.5] != [4.5]

First differing element 0:
7.5
4.5

First list contains 1 additional elements.
First extra element 1:
11.5

- [7.5, 11.5]
+ [4.5]

======================================================================
FAIL: test_interpolate_2d_3 (ClassEval_46_2.InterpolationTestInterpolate2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_2.py", line 172, in test_interpolate_2d_3
    self.assertEqual(
AssertionError: Lists differ: [4.5, 8.5] != [7.5]

First differing element 0:
4.5
7.5

First list contains 1 additional elements.
First extra element 1:
8.5

- [4.5, 8.5]
+ [7.5]

======================================================================
FAIL: test_interpolate_2d_4 (ClassEval_46_2.InterpolationTestInterpolate2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_2.py", line 178, in test_interpolate_2d_4
    self.assertEqual(
AssertionError: Lists differ: [9.0, 13.0] != [9.0]

First list contains 1 additional elements.
First extra element 1:
13.0

- [9.0, 13.0]
+ [9.0]

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.EEEEEE
======================================================================
ERROR: test_interpolate_1d_2 (ClassEval_46_3.InterpolationTestInterpolate1d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 118, in test_interpolate_1d_2
    self.assertEqual(interpolation.interpolate_1d([1, 6, 4], [1, 2, 5], [1.5, 2.5]), [1.1, 1.3])
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 28, in interpolate_1d
    raise ValueError("x must be strictly increasing")
ValueError: x must be strictly increasing

======================================================================
ERROR: test_interpolate_1d_3 (ClassEval_46_3.InterpolationTestInterpolate1d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 122, in test_interpolate_1d_3
    self.assertEqual(interpolation.interpolate_1d([1, 6, 4], [1, 7, 5], [1.5, 2.5]), [1.6, 2.8])
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 28, in interpolate_1d
    raise ValueError("x must be strictly increasing")
ValueError: x must be strictly increasing

======================================================================
ERROR: test_interpolate_1d_4 (ClassEval_46_3.InterpolationTestInterpolate1d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 126, in test_interpolate_1d_4
    self.assertEqual(interpolation.interpolate_1d([1, 6, 4], [1, 2, 5], [2, 3]), [1.2, 1.4])
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 28, in interpolate_1d
    raise ValueError("x must be strictly increasing")
ValueError: x must be strictly increasing

======================================================================
ERROR: test_interpolate_1d_5 (ClassEval_46_3.InterpolationTestInterpolate1d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 130, in test_interpolate_1d_5
    self.assertEqual(interpolation.interpolate_1d([1, 6, 4], [1, 7, 5], [2, 3]), [2.2, 3.4])
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 28, in interpolate_1d
    raise ValueError("x must be strictly increasing")
ValueError: x must be strictly increasing

======================================================================
ERROR: test_interpolate_1d_6 (ClassEval_46_3.InterpolationTestInterpolate1d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 134, in test_interpolate_1d_6
    self.assertEqual(interpolation.interpolate_1d([1, 6, 4], [1, 7, 5], []), [])
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 28, in interpolate_1d
    raise ValueError("x must be strictly increasing")
ValueError: x must be strictly increasing

======================================================================
ERROR: test_interpolate_1d_7 (ClassEval_46_3.InterpolationTestInterpolate1d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 138, in test_interpolate_1d_7
    self.assertEqual(interpolation.interpolate_1d([], [], [[], []]), [])
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 32, in interpolate_1d
    if xi < x[0] or xi > x[-1]:
IndexError: list index out of range

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (errors=6)
.EEE.
======================================================================
ERROR: test_interpolate_2d_2 (ClassEval_46_3.InterpolationTestInterpolate2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 151, in test_interpolate_2d_2
    interpolation.interpolate_2d([1, 2, 3], [1, 2, 3], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1.5, 2.5], [3, 4]),
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 78, in interpolate_2d
    raise ValueError(f"Point ({xi},{yi}) outside data range")
ValueError: Point (2.5,4) outside data range

======================================================================
ERROR: test_interpolate_2d_3 (ClassEval_46_3.InterpolationTestInterpolate2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 157, in test_interpolate_2d_3
    interpolation.interpolate_2d([1, 2, 3], [1, 2, 3], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [3, 4], [1.5, 2.5]),
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 78, in interpolate_2d
    raise ValueError(f"Point ({xi},{yi}) outside data range")
ValueError: Point (4,2.5) outside data range

======================================================================
ERROR: test_interpolate_2d_4 (ClassEval_46_3.InterpolationTestInterpolate2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 163, in test_interpolate_2d_4
    interpolation.interpolate_2d([1, 2, 3], [1, 2, 3], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [3, 4], [3, 4]),
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_3.py", line 78, in interpolate_2d
    raise ValueError(f"Point ({xi},{yi}) outside data range")
ValueError: Point (4,4) outside data range

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=3)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F.E
======================================================================
ERROR: test_interpolate_1d_7 (ClassEval_46_4.InterpolationTestInterpolate1d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_4.py", line 131, in test_interpolate_1d_7
    self.assertEqual(interpolation.interpolate_1d([], [], [[], []]), [])
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_4.py", line 24, in interpolate_1d
    raise ValueError("x and y must have the same length >= 2")
ValueError: x and y must have the same length >= 2

======================================================================
FAIL: test_interpolate_1d_5 (ClassEval_46_4.InterpolationTestInterpolate1d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_4.py", line 123, in test_interpolate_1d_5
    self.assertEqual(interpolation.interpolate_1d([1, 6, 4], [1, 7, 5], [2, 3]), [2.2, 3.4])
AssertionError: Lists differ: [2.2, 3.4000000000000004] != [2.2, 3.4]

First differing element 1:
3.4000000000000004
3.4

- [2.2, 3.4000000000000004]
+ [2.2, 3.4]

----------------------------------------------------------------------
Ran 7 tests in 0.001s

FAILED (failures=1, errors=1)
.FFF.
======================================================================
FAIL: test_interpolate_2d_2 (ClassEval_46_4.InterpolationTestInterpolate2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_4.py", line 143, in test_interpolate_2d_2
    self.assertEqual(
AssertionError: Lists differ: [7.5, 11.5] != [4.5]

First differing element 0:
7.5
4.5

First list contains 1 additional elements.
First extra element 1:
11.5

- [7.5, 11.5]
+ [4.5]

======================================================================
FAIL: test_interpolate_2d_3 (ClassEval_46_4.InterpolationTestInterpolate2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_4.py", line 149, in test_interpolate_2d_3
    self.assertEqual(
AssertionError: Lists differ: [4.5, 8.5] != [7.5]

First differing element 0:
4.5
7.5

First list contains 1 additional elements.
First extra element 1:
8.5

- [4.5, 8.5]
+ [7.5]

======================================================================
FAIL: test_interpolate_2d_4 (ClassEval_46_4.InterpolationTestInterpolate2d)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_46_4.py", line 155, in test_interpolate_2d_4
    self.assertEqual(
AssertionError: Lists differ: [9.0, 13.0] != [9.0]

First list contains 1 additional elements.
First extra element 1:
13.0

- [9.0, 13.0]
+ [9.0]

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.EF.
----------------------------------------------------------------------
Ran 1 test in 4.514s

OK
..FF.
======================================================================
FAIL: test_palindromic_length_3 (ClassEval_55_0.ManacherTestPalindromicLength)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_55_0.py", line 82, in test_palindromic_length_3
    self.assertEqual(manacher.palindromic_length(2, 3, 'a|b|a|b|a|x'), 0)
AssertionError: 2 != 0

======================================================================
FAIL: test_palindromic_length_4 (ClassEval_55_0.ManacherTestPalindromicLength)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_55_0.py", line 86, in test_palindromic_length_4
    self.assertEqual(manacher.palindromic_length(9, 2, 'a|b|a|b|a|x'), 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
..FF.
======================================================================
FAIL: test_palindromic_length_3 (ClassEval_55_1.ManacherTestPalindromicLength)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_55_1.py", line 82, in test_palindromic_length_3
    self.assertEqual(manacher.palindromic_length(2, 3, 'a|b|a|b|a|x'), 0)
AssertionError: 2 != 0

======================================================================
FAIL: test_palindromic_length_4 (ClassEval_55_1.ManacherTestPalindromicLength)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_55_1.py", line 86, in test_palindromic_length_4
    self.assertEqual(manacher.palindromic_length(9, 2, 'a|b|a|b|a|x'), 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
..FF.
======================================================================
FAIL: test_palindromic_length_3 (ClassEval_55_2.ManacherTestPalindromicLength)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_55_2.py", line 73, in test_palindromic_length_3
    self.assertEqual(manacher.palindromic_length(2, 3, 'a|b|a|b|a|x'), 0)
AssertionError: 2 != 0

======================================================================
FAIL: test_palindromic_length_4 (ClassEval_55_2.ManacherTestPalindromicLength)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_55_2.py", line 77, in test_palindromic_length_4
    self.assertEqual(manacher.palindromic_length(9, 2, 'a|b|a|b|a|x'), 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
..FF.
======================================================================
FAIL: test_palindromic_length_3 (ClassEval_55_3.ManacherTestPalindromicLength)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_55_3.py", line 82, in test_palindromic_length_3
    self.assertEqual(manacher.palindromic_length(2, 3, 'a|b|a|b|a|x'), 0)
AssertionError: 2 != 0

======================================================================
FAIL: test_palindromic_length_4 (ClassEval_55_3.ManacherTestPalindromicLength)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_55_3.py", line 86, in test_palindromic_length_4
    self.assertEqual(manacher.palindromic_length(9, 2, 'a|b|a|b|a|x'), 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
...F.E
======================================================================
ERROR: test_format_6 (ClassEval_65_0.NumberWordFormatterTestFormat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_0.py", line 189, in test_format_6
    self.assertEqual(formatter.format(None), "")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_0.py", line 34, in format
    return self.format_string(s)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_0.py", line 80, in format_string
    w = self.trans_three(s3)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_0.py", line 149, in trans_three
    words.append(self.trans_two(rem))
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_0.py", line 121, in trans_two
    ones = int(s[1])
ValueError: invalid literal for int() with base 10: 'N'

======================================================================
FAIL: test_format_4 (ClassEval_65_0.NumberWordFormatterTestFormat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_0.py", line 181, in test_format_4
    self.assertEqual(formatter.format(1.23), "ONE AND CENTS TWENTY THREE ONLY")
AssertionError: 'ONE POINT TWO THREE ONLY' != 'ONE AND CENTS TWENTY THREE ONLY'
- ONE POINT TWO THREE ONLY
+ ONE AND CENTS TWENTY THREE ONLY


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1, errors=1)
...F..
======================================================================
FAIL: test_format_string_4 (ClassEval_65_0.NumberWordFormatterTestFormatString)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_0.py", line 208, in test_format_string_4
    self.assertEqual(formatter.format_string('1.23'), "ONE AND CENTS TWENTY THREE ONLY")
AssertionError: 'ONE POINT TWO THREE ONLY' != 'ONE AND CENTS TWENTY THREE ONLY'
- ONE POINT TWO THREE ONLY
+ ONE AND CENTS TWENTY THREE ONLY


----------------------------------------------------------------------
Ran 6 tests in 0.000s

FAILED (failures=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
...F.E
======================================================================
ERROR: test_format_6 (ClassEval_65_1.NumberWordFormatterTestFormat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_1.py", line 186, in test_format_6
    self.assertEqual(formatter.format(None), "")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_1.py", line 65, in format
    part = self.trans_three(grp)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_1.py", line 141, in trans_three
    two = self.trans_two(rest)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_1.py", line 113, in trans_two
    ten, one = int(s[0]), int(s[1])
ValueError: invalid literal for int() with base 10: 'N'

======================================================================
FAIL: test_format_4 (ClassEval_65_1.NumberWordFormatterTestFormat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_1.py", line 178, in test_format_4
    self.assertEqual(formatter.format(1.23), "ONE AND CENTS TWENTY THREE ONLY")
AssertionError: 'ONE POINT TWO THREE ONLY' != 'ONE AND CENTS TWENTY THREE ONLY'
- ONE POINT TWO THREE ONLY
+ ONE AND CENTS TWENTY THREE ONLY


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1, errors=1)
...F..
======================================================================
FAIL: test_format_string_4 (ClassEval_65_1.NumberWordFormatterTestFormatString)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_1.py", line 205, in test_format_string_4
    self.assertEqual(formatter.format_string('1.23'), "ONE AND CENTS TWENTY THREE ONLY")
AssertionError: 'ONE POINT TWO THREE ONLY' != 'ONE AND CENTS TWENTY THREE ONLY'
- ONE POINT TWO THREE ONLY
+ ONE AND CENTS TWENTY THREE ONLY


----------------------------------------------------------------------
Ran 6 tests in 0.000s

FAILED (failures=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
...F.E
======================================================================
ERROR: test_format_6 (ClassEval_65_2.NumberWordFormatterTestFormat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_2.py", line 162, in test_format_6
    self.assertEqual(formatter.format(None), "")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_2.py", line 32, in format
    return self.format_string(s)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_2.py", line 66, in format_string
    part_word = self.trans_three(grp)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_2.py", line 113, in trans_three
    h, rest = int(s[0]), s[1:]
ValueError: invalid literal for int() with base 10: 'o'

======================================================================
FAIL: test_format_4 (ClassEval_65_2.NumberWordFormatterTestFormat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_2.py", line 154, in test_format_4
    self.assertEqual(formatter.format(1.23), "ONE AND CENTS TWENTY THREE ONLY")
AssertionError: 'ONE POINT TWO THREE ONLY' != 'ONE AND CENTS TWENTY THREE ONLY'
- ONE POINT TWO THREE ONLY
+ ONE AND CENTS TWENTY THREE ONLY


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1, errors=1)
...F..
======================================================================
FAIL: test_format_string_4 (ClassEval_65_2.NumberWordFormatterTestFormatString)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_2.py", line 181, in test_format_string_4
    self.assertEqual(formatter.format_string('1.23'), "ONE AND CENTS TWENTY THREE ONLY")
AssertionError: 'ONE POINT TWO THREE ONLY' != 'ONE AND CENTS TWENTY THREE ONLY'
- ONE POINT TWO THREE ONLY
+ ONE AND CENTS TWENTY THREE ONLY


----------------------------------------------------------------------
Ran 6 tests in 0.000s

FAILED (failures=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
...F.E
======================================================================
ERROR: test_format_6 (ClassEval_65_3.NumberWordFormatterTestFormat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_3.py", line 169, in test_format_6
    self.assertEqual(formatter.format(None), "")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_3.py", line 36, in format
    return self.format_string(s)
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_3.py", line 73, in format_string
    num = int(grp)
ValueError: invalid literal for int() with base 10: 'one'

======================================================================
FAIL: test_format_4 (ClassEval_65_3.NumberWordFormatterTestFormat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_3.py", line 161, in test_format_4
    self.assertEqual(formatter.format(1.23), "ONE AND CENTS TWENTY THREE ONLY")
AssertionError: 'ONE POINT TWO THREE ONLY' != 'ONE AND CENTS TWENTY THREE ONLY'
- ONE POINT TWO THREE ONLY
+ ONE AND CENTS TWENTY THREE ONLY


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1, errors=1)
...F..
======================================================================
FAIL: test_format_string_4 (ClassEval_65_3.NumberWordFormatterTestFormatString)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_3.py", line 188, in test_format_string_4
    self.assertEqual(formatter.format_string('1.23'), "ONE AND CENTS TWENTY THREE ONLY")
AssertionError: 'ONE POINT TWO THREE ONLY' != 'ONE AND CENTS TWENTY THREE ONLY'
- ONE POINT TWO THREE ONLY
+ ONE AND CENTS TWENTY THREE ONLY


----------------------------------------------------------------------
Ran 6 tests in 0.000s

FAILED (failures=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
...F.E
======================================================================
ERROR: test_format_6 (ClassEval_65_4.NumberWordFormatterTestFormat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_4.py", line 167, in test_format_6
    self.assertEqual(formatter.format(None), "")
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_4.py", line 80, in format
    if int(int_part) == 0:
ValueError: invalid literal for int() with base 10: 'None'

======================================================================
FAIL: test_format_4 (ClassEval_65_4.NumberWordFormatterTestFormat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_4.py", line 159, in test_format_4
    self.assertEqual(formatter.format(1.23), "ONE AND CENTS TWENTY THREE ONLY")
AssertionError: 'ONE POINT TWO THREE ONLY' != 'ONE AND CENTS TWENTY THREE ONLY'
- ONE POINT TWO THREE ONLY
+ ONE AND CENTS TWENTY THREE ONLY


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1, errors=1)
...F..
======================================================================
FAIL: test_format_string_4 (ClassEval_65_4.NumberWordFormatterTestFormatString)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_65_4.py", line 186, in test_format_string_4
    self.assertEqual(formatter.format_string('1.23'), "ONE AND CENTS TWENTY THREE ONLY")
AssertionError: 'ONE POINT TWO THREE ONLY' != 'ONE AND CENTS TWENTY THREE ONLY'
- ONE POINT TWO THREE ONLY
+ ONE AND CENTS TWENTY THREE ONLY


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.FF....FF.F
======================================================================
FAIL: test_replace_10 (ClassEval_66_0.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_0.py", line 109, in test_replace_10
    self.assertEqual(res, "")
AssertionError: '&#X' != ''
- &#X
+ 


======================================================================
FAIL: test_replace_11 (ClassEval_66_0.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_0.py", line 114, in test_replace_11
    self.assertEqual(res, "")
AssertionError: '&#c1d;BC' != ''
- &#c1d;BC
+ 


======================================================================
FAIL: test_replace_6 (ClassEval_66_0.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_0.py", line 89, in test_replace_6
    self.assertEqual(res, "")
AssertionError: '&#' != ''
- &#
+ 


======================================================================
FAIL: test_replace_7 (ClassEval_66_0.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_0.py", line 94, in test_replace_7
    self.assertEqual(res, "eBC")
AssertionError: '&#X65;BC' != 'eBC'
- &#X65;BC
+ eBC


======================================================================
FAIL: test_replace_9 (ClassEval_66_0.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_0.py", line 104, in test_replace_9
    self.assertEqual(res, "CCC")
AssertionError: 'CCC;' != 'CCC'
- CCC;
?    -
+ CCC


----------------------------------------------------------------------
Ran 11 tests in 0.001s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.FF....F..F
======================================================================
FAIL: test_replace_10 (ClassEval_66_1.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_1.py", line 137, in test_replace_10
    self.assertEqual(res, "")
AssertionError: '&#X' != ''
- &#X
+ 


======================================================================
FAIL: test_replace_11 (ClassEval_66_1.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_1.py", line 142, in test_replace_11
    self.assertEqual(res, "")
AssertionError: '&#c1d;BC' != ''
- &#c1d;BC
+ 


======================================================================
FAIL: test_replace_6 (ClassEval_66_1.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_1.py", line 117, in test_replace_6
    self.assertEqual(res, "")
AssertionError: '&#' != ''
- &#
+ 


======================================================================
FAIL: test_replace_9 (ClassEval_66_1.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_1.py", line 132, in test_replace_9
    self.assertEqual(res, "CCC")
AssertionError: 'CCC;' != 'CCC'
- CCC;
?    -
+ CCC


----------------------------------------------------------------------
Ran 11 tests in 0.001s

FAILED (failures=4)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.FF....F..F
======================================================================
FAIL: test_replace_10 (ClassEval_66_2.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_2.py", line 135, in test_replace_10
    self.assertEqual(res, "")
AssertionError: '&#X' != ''
- &#X
+ 


======================================================================
FAIL: test_replace_11 (ClassEval_66_2.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_2.py", line 140, in test_replace_11
    self.assertEqual(res, "")
AssertionError: '&#c1d;BC' != ''
- &#c1d;BC
+ 


======================================================================
FAIL: test_replace_6 (ClassEval_66_2.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_2.py", line 115, in test_replace_6
    self.assertEqual(res, "")
AssertionError: '&#' != ''
- &#
+ 


======================================================================
FAIL: test_replace_9 (ClassEval_66_2.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_2.py", line 130, in test_replace_9
    self.assertEqual(res, "CCC")
AssertionError: 'CCC;' != 'CCC'
- CCC;
?    -
+ CCC


----------------------------------------------------------------------
Ran 11 tests in 0.002s

FAILED (failures=4)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.FF....F..F
======================================================================
FAIL: test_replace_10 (ClassEval_66_3.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_3.py", line 123, in test_replace_10
    self.assertEqual(res, "")
AssertionError: '&#X' != ''
- &#X
+ 


======================================================================
FAIL: test_replace_11 (ClassEval_66_3.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_3.py", line 128, in test_replace_11
    self.assertEqual(res, "")
AssertionError: '&#c1d;BC' != ''
- &#c1d;BC
+ 


======================================================================
FAIL: test_replace_6 (ClassEval_66_3.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_3.py", line 103, in test_replace_6
    self.assertEqual(res, "")
AssertionError: '&#' != ''
- &#
+ 


======================================================================
FAIL: test_replace_9 (ClassEval_66_3.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_3.py", line 118, in test_replace_9
    self.assertEqual(res, "CCC")
AssertionError: 'CCC;' != 'CCC'
- CCC;
?    -
+ CCC


----------------------------------------------------------------------
Ran 11 tests in 0.001s

FAILED (failures=4)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.FF....F..F
======================================================================
FAIL: test_replace_10 (ClassEval_66_4.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_4.py", line 125, in test_replace_10
    self.assertEqual(res, "")
AssertionError: '&#X' != ''
- &#X
+ 


======================================================================
FAIL: test_replace_11 (ClassEval_66_4.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_4.py", line 130, in test_replace_11
    self.assertEqual(res, "")
AssertionError: '&#c1d;BC' != ''
- &#c1d;BC
+ 


======================================================================
FAIL: test_replace_6 (ClassEval_66_4.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_4.py", line 105, in test_replace_6
    self.assertEqual(res, "")
AssertionError: '&#' != ''
- &#
+ 


======================================================================
FAIL: test_replace_9 (ClassEval_66_4.NumericEntityUnescaperTestReplace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_66_4.py", line 120, in test_replace_9
    self.assertEqual(res, "CCC")
AssertionError: 'CCC;' != 'CCC'
- CCC;
?    -
+ CCC


----------------------------------------------------------------------
Ran 11 tests in 0.001s

FAILED (failures=4)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FF...
======================================================================
FAIL: test_generate_split_sentences_pattern_1 (ClassEval_72_0.RegexUtilsTestGenerateSplitSentencesPattern)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_72_0.py", line 266, in test_generate_split_sentences_pattern_1
    self.assertEqual(res, True)
AssertionError: False != True

======================================================================
FAIL: test_generate_split_sentences_pattern_2 (ClassEval_72_0.RegexUtilsTestGenerateSplitSentencesPattern)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_72_0.py", line 272, in test_generate_split_sentences_pattern_2
    self.assertEqual(res, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_regexutils (ClassEval_72_0.RegexUtilsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_72_0.py", line 400, in test_regexutils
    self.assertEqual(res, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FF...
======================================================================
FAIL: test_generate_split_sentences_pattern_1 (ClassEval_72_1.RegexUtilsTestGenerateSplitSentencesPattern)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_72_1.py", line 283, in test_generate_split_sentences_pattern_1
    self.assertEqual(res, True)
AssertionError: False != True

======================================================================
FAIL: test_generate_split_sentences_pattern_2 (ClassEval_72_1.RegexUtilsTestGenerateSplitSentencesPattern)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_72_1.py", line 289, in test_generate_split_sentences_pattern_2
    self.assertEqual(res, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
F
======================================================================
FAIL: test_regexutils (ClassEval_72_1.RegexUtilsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_72_1.py", line 417, in test_regexutils
    self.assertEqual(res, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FF...
======================================================================
FAIL: test_generate_split_sentences_pattern_1 (ClassEval_72_2.RegexUtilsTestGenerateSplitSentencesPattern)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_72_2.py", line 262, in test_generate_split_sentences_pattern_1
    self.assertEqual(res, True)
AssertionError: False != True

======================================================================
FAIL: test_generate_split_sentences_pattern_2 (ClassEval_72_2.RegexUtilsTestGenerateSplitSentencesPattern)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_72_2.py", line 268, in test_generate_split_sentences_pattern_2
    self.assertEqual(res, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_regexutils (ClassEval_72_2.RegexUtilsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_72_2.py", line 396, in test_regexutils
    self.assertEqual(res, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FF...
======================================================================
FAIL: test_generate_split_sentences_pattern_1 (ClassEval_72_3.RegexUtilsTestGenerateSplitSentencesPattern)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_72_3.py", line 286, in test_generate_split_sentences_pattern_1
    self.assertEqual(res, True)
AssertionError: False != True

======================================================================
FAIL: test_generate_split_sentences_pattern_2 (ClassEval_72_3.RegexUtilsTestGenerateSplitSentencesPattern)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_72_3.py", line 292, in test_generate_split_sentences_pattern_2
    self.assertEqual(res, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_regexutils (ClassEval_72_3.RegexUtilsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_72_3.py", line 420, in test_regexutils
    self.assertEqual(res, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
FF...
======================================================================
FAIL: test_generate_split_sentences_pattern_1 (ClassEval_72_4.RegexUtilsTestGenerateSplitSentencesPattern)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_72_4.py", line 263, in test_generate_split_sentences_pattern_1
    self.assertEqual(res, True)
AssertionError: False != True

======================================================================
FAIL: test_generate_split_sentences_pattern_2 (ClassEval_72_4.RegexUtilsTestGenerateSplitSentencesPattern)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_72_4.py", line 269, in test_generate_split_sentences_pattern_2
    self.assertEqual(res, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
F
======================================================================
FAIL: test_regexutils (ClassEval_72_4.RegexUtilsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_72_4.py", line 397, in test_regexutils
    self.assertEqual(res, True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...F.
======================================================================
FAIL: test_count_words_4 (ClassEval_78_1.SplitSentenceTestCountWords)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_78_1.py", line 115, in test_count_words_4
    self.assertEqual(cnt, 3)
AssertionError: 2 != 3

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...F.
======================================================================
FAIL: test_count_words_4 (ClassEval_78_2.SplitSentenceTestCountWords)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_78_2.py", line 107, in test_count_words_4
    self.assertEqual(cnt, 3)
AssertionError: 2 != 3

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...F.
======================================================================
FAIL: test_count_words_4 (ClassEval_78_3.SplitSentenceTestCountWords)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_78_3.py", line 116, in test_count_words_4
    self.assertEqual(cnt, 3)
AssertionError: 2 != 3

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...F.
======================================================================
FAIL: test_count_words_4 (ClassEval_78_4.SplitSentenceTestCountWords)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_78_4.py", line 106, in test_count_words_4
    self.assertEqual(cnt, 3)
AssertionError: 2 != 3

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.F.FF
======================================================================
FAIL: test_add_stock_2 (ClassEval_82_0.StockPortfolioTrackerTestAddStock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_82_0.py", line 137, in test_add_stock_2
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20}])
AssertionError: Lists differ: [{'na[32 chars]antity': 10}, {'name': 'AAPL', 'price': 150.0, 'quantity': 10}] != [{'na[32 chars]antity': 20}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

First list contains 1 additional elements.
First extra element 1:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                               ^  ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20}]
?                                               ^  ^

-  {'name': 'AAPL', 'price': 150.0, 'quantity': 10}]

======================================================================
FAIL: test_add_stock_4 (ClassEval_82_0.StockPortfolioTrackerTestAddStock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_82_0.py", line 151, in test_add_stock_4
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
AssertionError: Lists differ: [{'na[36 chars]ty': 10}, {'name': 'AAPL', 'price': 150.0, 'qu[58 chars] 10}] != [{'na[36 chars]ty': 20}, {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

First list contains 1 additional elements.
First extra element 2:
{'name': 'MSFT', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                               ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
?                                               ^

-  {'name': 'AAPL', 'price': 150.0, 'quantity': 10},
   {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]

======================================================================
FAIL: test_add_stock_5 (ClassEval_82_0.StockPortfolioTrackerTestAddStock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_82_0.py", line 160, in test_add_stock_5
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
AssertionError: Lists differ: [{'na[36 chars]ty': 10}, {'name': 'AAPL', 'price': 150.0, 'qu[108 chars] 10}] != [{'na[36 chars]ty': 20}, {'name': 'MSFT', 'price': 150.0, 'quantity': 20}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

First list contains 2 additional elements.
First extra element 2:
{'name': 'MSFT', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                               ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
?                                               ^

-  {'name': 'AAPL', 'price': 150.0, 'quantity': 10},
-  {'name': 'MSFT', 'price': 150.0, 'quantity': 10},
-  {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]
?                                               ^

+  {'name': 'MSFT', 'price': 150.0, 'quantity': 20}]
?                                               ^


----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
..F..
======================================================================
FAIL: test_remove_stock_3 (ClassEval_82_1.StockPortfolioTrackerTestRemoveStock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_82_1.py", line 177, in test_remove_stock_3
    self.assertEqual(tracker.remove_stock({"name": "MSFT", "price": 150.0, "quantity": 20}), False)
AssertionError: True != False

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
.F.FF
======================================================================
FAIL: test_add_stock_2 (ClassEval_82_2.StockPortfolioTrackerTestAddStock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_82_2.py", line 129, in test_add_stock_2
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20}])
AssertionError: Lists differ: [{'na[32 chars]antity': 10}, {'name': 'AAPL', 'price': 150.0, 'quantity': 10}] != [{'na[32 chars]antity': 20}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

First list contains 1 additional elements.
First extra element 1:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                               ^  ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20}]
?                                               ^  ^

-  {'name': 'AAPL', 'price': 150.0, 'quantity': 10}]

======================================================================
FAIL: test_add_stock_4 (ClassEval_82_2.StockPortfolioTrackerTestAddStock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_82_2.py", line 143, in test_add_stock_4
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
AssertionError: Lists differ: [{'na[36 chars]ty': 10}, {'name': 'AAPL', 'price': 150.0, 'qu[58 chars] 10}] != [{'na[36 chars]ty': 20}, {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

First list contains 1 additional elements.
First extra element 2:
{'name': 'MSFT', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                               ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
?                                               ^

-  {'name': 'AAPL', 'price': 150.0, 'quantity': 10},
   {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]

======================================================================
FAIL: test_add_stock_5 (ClassEval_82_2.StockPortfolioTrackerTestAddStock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_82_2.py", line 152, in test_add_stock_5
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
AssertionError: Lists differ: [{'na[36 chars]ty': 10}, {'name': 'AAPL', 'price': 150.0, 'qu[108 chars] 10}] != [{'na[36 chars]ty': 20}, {'name': 'MSFT', 'price': 150.0, 'quantity': 20}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

First list contains 2 additional elements.
First extra element 2:
{'name': 'MSFT', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                               ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
?                                               ^

-  {'name': 'AAPL', 'price': 150.0, 'quantity': 10},
-  {'name': 'MSFT', 'price': 150.0, 'quantity': 10},
-  {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]
?                                               ^

+  {'name': 'MSFT', 'price': 150.0, 'quantity': 20}]
?                                               ^


----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
.F.FF
======================================================================
FAIL: test_add_stock_2 (ClassEval_82_3.StockPortfolioTrackerTestAddStock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_82_3.py", line 127, in test_add_stock_2
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20}])
AssertionError: Lists differ: [{'na[32 chars]antity': 10}, {'name': 'AAPL', 'price': 150.0, 'quantity': 10}] != [{'na[32 chars]antity': 20}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

First list contains 1 additional elements.
First extra element 1:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                               ^  ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20}]
?                                               ^  ^

-  {'name': 'AAPL', 'price': 150.0, 'quantity': 10}]

======================================================================
FAIL: test_add_stock_4 (ClassEval_82_3.StockPortfolioTrackerTestAddStock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_82_3.py", line 141, in test_add_stock_4
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
AssertionError: Lists differ: [{'na[36 chars]ty': 10}, {'name': 'AAPL', 'price': 150.0, 'qu[58 chars] 10}] != [{'na[36 chars]ty': 20}, {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

First list contains 1 additional elements.
First extra element 2:
{'name': 'MSFT', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                               ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
?                                               ^

-  {'name': 'AAPL', 'price': 150.0, 'quantity': 10},
   {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]

======================================================================
FAIL: test_add_stock_5 (ClassEval_82_3.StockPortfolioTrackerTestAddStock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_82_3.py", line 150, in test_add_stock_5
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
AssertionError: Lists differ: [{'na[36 chars]ty': 10}, {'name': 'AAPL', 'price': 150.0, 'qu[108 chars] 10}] != [{'na[36 chars]ty': 20}, {'name': 'MSFT', 'price': 150.0, 'quantity': 20}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

First list contains 2 additional elements.
First extra element 2:
{'name': 'MSFT', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                               ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
?                                               ^

-  {'name': 'AAPL', 'price': 150.0, 'quantity': 10},
-  {'name': 'MSFT', 'price': 150.0, 'quantity': 10},
-  {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]
?                                               ^

+  {'name': 'MSFT', 'price': 150.0, 'quantity': 20}]
?                                               ^


----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
.F.FF
======================================================================
FAIL: test_add_stock_2 (ClassEval_82_4.StockPortfolioTrackerTestAddStock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_82_4.py", line 142, in test_add_stock_2
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20}])
AssertionError: Lists differ: [{'na[32 chars]antity': 10}, {'name': 'AAPL', 'price': 150.0, 'quantity': 10}] != [{'na[32 chars]antity': 20}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

First list contains 1 additional elements.
First extra element 1:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                               ^  ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20}]
?                                               ^  ^

-  {'name': 'AAPL', 'price': 150.0, 'quantity': 10}]

======================================================================
FAIL: test_add_stock_4 (ClassEval_82_4.StockPortfolioTrackerTestAddStock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_82_4.py", line 156, in test_add_stock_4
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
AssertionError: Lists differ: [{'na[36 chars]ty': 10}, {'name': 'AAPL', 'price': 150.0, 'qu[58 chars] 10}] != [{'na[36 chars]ty': 20}, {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

First list contains 1 additional elements.
First extra element 2:
{'name': 'MSFT', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                               ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
?                                               ^

-  {'name': 'AAPL', 'price': 150.0, 'quantity': 10},
   {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]

======================================================================
FAIL: test_add_stock_5 (ClassEval_82_4.StockPortfolioTrackerTestAddStock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_82_4.py", line 165, in test_add_stock_5
    self.assertEqual(tracker.portfolio, [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
AssertionError: Lists differ: [{'na[36 chars]ty': 10}, {'name': 'AAPL', 'price': 150.0, 'qu[108 chars] 10}] != [{'na[36 chars]ty': 20}, {'name': 'MSFT', 'price': 150.0, 'quantity': 20}]

First differing element 0:
{'name': 'AAPL', 'price': 150.0, 'quantity': 10}
{'name': 'AAPL', 'price': 150.0, 'quantity': 20}

First list contains 2 additional elements.
First extra element 2:
{'name': 'MSFT', 'price': 150.0, 'quantity': 10}

- [{'name': 'AAPL', 'price': 150.0, 'quantity': 10},
?                                               ^

+ [{'name': 'AAPL', 'price': 150.0, 'quantity': 20},
?                                               ^

-  {'name': 'AAPL', 'price': 150.0, 'quantity': 10},
-  {'name': 'MSFT', 'price': 150.0, 'quantity': 10},
-  {'name': 'MSFT', 'price': 150.0, 'quantity': 10}]
?                                               ^

+  {'name': 'MSFT', 'price': 150.0, 'quantity': 20}]
?                                               ^


----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=3)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....F
======================================================================
FAIL: test_get_scheme_6 (ClassEval_90_0.URLHandlerTestGetScheme)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_0.py", line 88, in test_get_scheme_6
    self.assertIsNone(temp)
AssertionError: '' is not None

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....F..
======================================================================
FAIL: test_get_host_6 (ClassEval_90_0.URLHandlerTestGetHost)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_0.py", line 121, in test_get_host_6
    self.assertIsNone(temp)
AssertionError: '' is not None

----------------------------------------------------------------------
Ran 8 tests in 0.000s

FAILED (failures=1)
.....F
======================================================================
FAIL: test_get_path_6 (ClassEval_90_0.URLHandlerTestGetPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_0.py", line 165, in test_get_path_6
    self.assertIsNone(temp)
AssertionError: 'abcdefg' is not None

----------------------------------------------------------------------
Ran 6 tests in 0.000s

FAILED (failures=1)
..F...
======================================================================
FAIL: test_get_query_params_3 (ClassEval_90_0.URLHandlerTestGetQueryParams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_0.py", line 184, in test_get_query_params_3
    self.assertEqual(temp, None)
AssertionError: {} != None

----------------------------------------------------------------------
Ran 6 tests in 0.000s

FAILED (failures=1)
.F...
======================================================================
FAIL: test_get_fragment_2 (ClassEval_90_0.URLHandlerTestGetFragment)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_0.py", line 212, in test_get_fragment_2
    self.assertEqual(temp, None)
AssertionError: '' != None

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....F
======================================================================
FAIL: test_get_scheme_6 (ClassEval_90_1.URLHandlerTestGetScheme)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_1.py", line 95, in test_get_scheme_6
    self.assertIsNone(temp)
AssertionError: '' is not None

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....F..
======================================================================
FAIL: test_get_host_6 (ClassEval_90_1.URLHandlerTestGetHost)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_1.py", line 128, in test_get_host_6
    self.assertIsNone(temp)
AssertionError: '' is not None

----------------------------------------------------------------------
Ran 8 tests in 0.000s

FAILED (failures=1)
.....F
======================================================================
FAIL: test_get_path_6 (ClassEval_90_1.URLHandlerTestGetPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_1.py", line 172, in test_get_path_6
    self.assertIsNone(temp)
AssertionError: 'abcdefg' is not None

----------------------------------------------------------------------
Ran 6 tests in 0.000s

FAILED (failures=1)
..F...
======================================================================
FAIL: test_get_query_params_3 (ClassEval_90_1.URLHandlerTestGetQueryParams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_1.py", line 191, in test_get_query_params_3
    self.assertEqual(temp, None)
AssertionError: {} != None

----------------------------------------------------------------------
Ran 6 tests in 0.000s

FAILED (failures=1)
.F...
======================================================================
FAIL: test_get_fragment_2 (ClassEval_90_1.URLHandlerTestGetFragment)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_1.py", line 219, in test_get_fragment_2
    self.assertEqual(temp, None)
AssertionError: '' != None

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....F
======================================================================
FAIL: test_get_scheme_6 (ClassEval_90_2.URLHandlerTestGetScheme)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_2.py", line 106, in test_get_scheme_6
    self.assertIsNone(temp)
AssertionError: '' is not None

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....F..
======================================================================
FAIL: test_get_host_6 (ClassEval_90_2.URLHandlerTestGetHost)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_2.py", line 139, in test_get_host_6
    self.assertIsNone(temp)
AssertionError: '' is not None

----------------------------------------------------------------------
Ran 8 tests in 0.000s

FAILED (failures=1)
.....F
======================================================================
FAIL: test_get_path_6 (ClassEval_90_2.URLHandlerTestGetPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_2.py", line 183, in test_get_path_6
    self.assertIsNone(temp)
AssertionError: 'abcdefg' is not None

----------------------------------------------------------------------
Ran 6 tests in 0.000s

FAILED (failures=1)
..F...
======================================================================
FAIL: test_get_query_params_3 (ClassEval_90_2.URLHandlerTestGetQueryParams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_2.py", line 202, in test_get_query_params_3
    self.assertEqual(temp, None)
AssertionError: {} != None

----------------------------------------------------------------------
Ran 6 tests in 0.000s

FAILED (failures=1)
.F...
======================================================================
FAIL: test_get_fragment_2 (ClassEval_90_2.URLHandlerTestGetFragment)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_2.py", line 230, in test_get_fragment_2
    self.assertEqual(temp, None)
AssertionError: '' != None

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....F
======================================================================
FAIL: test_get_scheme_6 (ClassEval_90_3.URLHandlerTestGetScheme)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_3.py", line 94, in test_get_scheme_6
    self.assertIsNone(temp)
AssertionError: '' is not None

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....F..
======================================================================
FAIL: test_get_host_6 (ClassEval_90_3.URLHandlerTestGetHost)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_3.py", line 127, in test_get_host_6
    self.assertIsNone(temp)
AssertionError: '' is not None

----------------------------------------------------------------------
Ran 8 tests in 0.000s

FAILED (failures=1)
.....F
======================================================================
FAIL: test_get_path_6 (ClassEval_90_3.URLHandlerTestGetPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_3.py", line 171, in test_get_path_6
    self.assertIsNone(temp)
AssertionError: 'abcdefg' is not None

----------------------------------------------------------------------
Ran 6 tests in 0.000s

FAILED (failures=1)
..F...
======================================================================
FAIL: test_get_query_params_3 (ClassEval_90_3.URLHandlerTestGetQueryParams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_3.py", line 190, in test_get_query_params_3
    self.assertEqual(temp, None)
AssertionError: {} != None

----------------------------------------------------------------------
Ran 6 tests in 0.000s

FAILED (failures=1)
.F...
======================================================================
FAIL: test_get_fragment_2 (ClassEval_90_3.URLHandlerTestGetFragment)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_3.py", line 218, in test_get_fragment_2
    self.assertEqual(temp, None)
AssertionError: '' != None

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....F
======================================================================
FAIL: test_get_scheme_6 (ClassEval_90_4.URLHandlerTestGetScheme)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_4.py", line 112, in test_get_scheme_6
    self.assertIsNone(temp)
AssertionError: '' is not None

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....F..
======================================================================
FAIL: test_get_host_6 (ClassEval_90_4.URLHandlerTestGetHost)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_4.py", line 145, in test_get_host_6
    self.assertIsNone(temp)
AssertionError: '' is not None

----------------------------------------------------------------------
Ran 8 tests in 0.000s

FAILED (failures=1)
.....F
======================================================================
FAIL: test_get_path_6 (ClassEval_90_4.URLHandlerTestGetPath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_4.py", line 189, in test_get_path_6
    self.assertIsNone(temp)
AssertionError: 'abcdefg' is not None

----------------------------------------------------------------------
Ran 6 tests in 0.000s

FAILED (failures=1)
..F...
======================================================================
FAIL: test_get_query_params_3 (ClassEval_90_4.URLHandlerTestGetQueryParams)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_4.py", line 208, in test_get_query_params_3
    self.assertEqual(temp, None)
AssertionError: {} != None

----------------------------------------------------------------------
Ran 6 tests in 0.000s

FAILED (failures=1)
.F...
======================================================================
FAIL: test_get_fragment_2 (ClassEval_90_4.URLHandlerTestGetFragment)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_90_4.py", line 236, in test_get_fragment_2
    self.assertEqual(temp, None)
AssertionError: '' != None

----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (failures=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
E