.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_0.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_0.py", line 108, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_0.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_0.py", line 115, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'red'
- apple
+ red


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_2.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_2.py", line 106, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_2.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_2.py", line 113, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'red'
- apple
+ red


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
EEEEE
======================================================================
ERROR: test_add_word_1 (ClassEval_53_3.LongestWordTestAddWord.test_add_word_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 8, in test_add_word_1
    longestWord = LongestWord()
                  ^^^^^^^^^^^
NameError: name 'LongestWord' is not defined

======================================================================
ERROR: test_add_word_2 (ClassEval_53_3.LongestWordTestAddWord.test_add_word_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 13, in test_add_word_2
    longestWord = LongestWord()
                  ^^^^^^^^^^^
NameError: name 'LongestWord' is not defined

======================================================================
ERROR: test_add_word_3 (ClassEval_53_3.LongestWordTestAddWord.test_add_word_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 19, in test_add_word_3
    longestWord = LongestWord()
                  ^^^^^^^^^^^
NameError: name 'LongestWord' is not defined

======================================================================
ERROR: test_add_word_4 (ClassEval_53_3.LongestWordTestAddWord.test_add_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 26, in test_add_word_4
    longestWord = LongestWord()
                  ^^^^^^^^^^^
NameError: name 'LongestWord' is not defined

======================================================================
ERROR: test_add_word_5 (ClassEval_53_3.LongestWordTestAddWord.test_add_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 34, in test_add_word_5
    longestWord = LongestWord()
                  ^^^^^^^^^^^
NameError: name 'LongestWord' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.021s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_find_longest_word_1 (ClassEval_53_3.LongestWordTestFindLongestWord.test_find_longest_word_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 45, in test_find_longest_word_1
    longestWord = LongestWord()
                  ^^^^^^^^^^^
NameError: name 'LongestWord' is not defined

======================================================================
ERROR: test_find_longest_word_2 (ClassEval_53_3.LongestWordTestFindLongestWord.test_find_longest_word_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 51, in test_find_longest_word_2
    longestWord = LongestWord()
                  ^^^^^^^^^^^
NameError: name 'LongestWord' is not defined

======================================================================
ERROR: test_find_longest_word_3 (ClassEval_53_3.LongestWordTestFindLongestWord.test_find_longest_word_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 56, in test_find_longest_word_3
    longestWord = LongestWord()
                  ^^^^^^^^^^^
NameError: name 'LongestWord' is not defined

======================================================================
ERROR: test_find_longest_word_4 (ClassEval_53_3.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 62, in test_find_longest_word_4
    longestWord = LongestWord()
                  ^^^^^^^^^^^
NameError: name 'LongestWord' is not defined

======================================================================
ERROR: test_find_longest_word_5 (ClassEval_53_3.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 68, in test_find_longest_word_5
    longestWord = LongestWord()
                  ^^^^^^^^^^^
NameError: name 'LongestWord' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.019s

FAILED (errors=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_4.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_4.py", line 104, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_4.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_4.py", line 111, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'red'
- apple
+ red


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F
======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_0.NLPDataProcessorTestRemove.test_remove_stop_words_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_0.py", line 93, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: Lists differ: [['test'], ['apple'], ['dog']] != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

First differing element 0:
['test']
['is', 'test']

- [['test'], ['apple'], ['dog']]
+ [['is', 'test'], ['is', 'apple'], ['is', 'dog']]
?   ++++++          ++++++           ++++++


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F
======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_1.NLPDataProcessorTestRemove.test_remove_stop_words_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_1.py", line 86, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: Lists differ: [['test'], ['apple'], ['dog']] != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

First differing element 0:
['test']
['is', 'test']

- [['test'], ['apple'], ['dog']]
+ [['is', 'test'], ['is', 'apple'], ['is', 'dog']]
?   ++++++          ++++++           ++++++


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F
======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_2.NLPDataProcessorTestRemove.test_remove_stop_words_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_2.py", line 92, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: Lists differ: [['test'], ['apple'], ['dog']] != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

First differing element 0:
['test']
['is', 'test']

- [['test'], ['apple'], ['dog']]
+ [['is', 'test'], ['is', 'apple'], ['is', 'dog']]
?   ++++++          ++++++           ++++++


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F
======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_3.NLPDataProcessorTestRemove.test_remove_stop_words_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_3.py", line 93, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: Lists differ: [['test'], ['apple'], ['dog']] != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

First differing element 0:
['test']
['is', 'test']

- [['test'], ['apple'], ['dog']]
+ [['is', 'test'], ['is', 'apple'], ['is', 'dog']]
?   ++++++          ++++++           ++++++


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
....F
======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_4.NLPDataProcessorTestRemove.test_remove_stop_words_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_4.py", line 91, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: Lists differ: [['test'], ['apple'], ['dog']] != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

First differing element 0:
['test']
['is', 'test']

- [['test'], ['apple'], ['dog']]
+ [['is', 'test'], ['is', 'apple'], ['is', 'dog']]
?   ++++++          ++++++           ++++++


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
...FF
======================================================================
FAIL: test_calculate_word_frequency4 (ClassEval_63_0.NLPDataProcessorTestCalculate.test_calculate_word_frequency4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_63_0.py", line 120, in test_calculate_word_frequency4
    self.assertEqual(self.processor.calculate_word_frequency(words_list), expected_output)
AssertionError: {'%%%': 6, 'hello': 5, 'world': 4, 'a': 2, 'is': 2} != {'%%%': 6, 'hello': 5, 'world': 4, 'is': 2, 'this': 2}
- {'%%%': 6, 'a': 2, 'hello': 5, 'is': 2, 'world': 4}
?           --------

+ {'%%%': 6, 'hello': 5, 'is': 2, 'this': 2, 'world': 4}
?                                +++++++++++


======================================================================
FAIL: test_calculate_word_frequency5 (ClassEval_63_0.NLPDataProcessorTestCalculate.test_calculate_word_frequency5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_63_0.py", line 127, in test_calculate_word_frequency5
    self.assertEqual(self.processor.calculate_word_frequency(words_list), expected_output)
AssertionError: {'%%%': 12, 'hello': 10, 'world': 8, 'a': 4, 'is': 4} != {'%%%': 12, 'hello': 10, 'world': 8, 'is': 4, 'this': 4}
- {'%%%': 12, 'a': 4, 'hello': 10, 'is': 4, 'world': 8}
?            --------

+ {'%%%': 12, 'hello': 10, 'is': 4, 'this': 4, 'world': 8}
?                                  +++++++++++


----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=2)
.F..F.
======================================================================
FAIL: test_process (ClassEval_63_0.NLPDataProcessorTestProcess.test_process)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_63_0.py", line 137, in test_process
    self.assertEqual(self.processor.process(string_list), expected_output)
AssertionError: {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2} != {'hello': 2, 'world': 2, 'this': 2, 'is': 2, 'a': 2}
- {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2}
?                              -----------

+ {'a': 2, 'hello': 2, 'is': 2, 'this': 2, 'world': 2}
?                                       ++++++++++++


======================================================================
FAIL: test_process5 (ClassEval_63_0.NLPDataProcessorTestProcess.test_process5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_63_0.py", line 157, in test_process5
    self.assertEqual(self.processor.process(string_list), expected_output)
AssertionError: {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2} != {'hello': 2, 'world': 2, 'this': 2, 'is': 2, 'a': 2}
- {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2}
?                              -----------

+ {'a': 2, 'hello': 2, 'is': 2, 'this': 2, 'world': 2}
?                                       ++++++++++++


----------------------------------------------------------------------
Ran 6 tests in 0.003s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_calculate_word_frequency4 (ClassEval_63_1.NLPDataProcessorTestCalculate.test_calculate_word_frequency4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_63_1.py", line 119, in test_calculate_word_frequency4
    self.assertEqual(self.processor.calculate_word_frequency(words_list), expected_output)
AssertionError: {'%%%': 6, 'hello': 5, 'world': 4, 'a': 2, 'is': 2} != {'%%%': 6, 'hello': 5, 'world': 4, 'is': 2, 'this': 2}
- {'%%%': 6, 'a': 2, 'hello': 5, 'is': 2, 'world': 4}
?           --------

+ {'%%%': 6, 'hello': 5, 'is': 2, 'this': 2, 'world': 4}
?                                +++++++++++


======================================================================
FAIL: test_calculate_word_frequency5 (ClassEval_63_1.NLPDataProcessorTestCalculate.test_calculate_word_frequency5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_63_1.py", line 126, in test_calculate_word_frequency5
    self.assertEqual(self.processor.calculate_word_frequency(words_list), expected_output)
AssertionError: {'%%%': 12, 'hello': 10, 'world': 8, 'a': 4, 'is': 4} != {'%%%': 12, 'hello': 10, 'world': 8, 'is': 4, 'this': 4}
- {'%%%': 12, 'a': 4, 'hello': 10, 'is': 4, 'world': 8}
?            --------

+ {'%%%': 12, 'hello': 10, 'is': 4, 'this': 4, 'world': 8}
?                                  +++++++++++


----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=2)
.F..F.
======================================================================
FAIL: test_process (ClassEval_63_1.NLPDataProcessorTestProcess.test_process)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_63_1.py", line 136, in test_process
    self.assertEqual(self.processor.process(string_list), expected_output)
AssertionError: {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2} != {'hello': 2, 'world': 2, 'this': 2, 'is': 2, 'a': 2}
- {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2}
?                              -----------

+ {'a': 2, 'hello': 2, 'is': 2, 'this': 2, 'world': 2}
?                                       ++++++++++++


======================================================================
FAIL: test_process5 (ClassEval_63_1.NLPDataProcessorTestProcess.test_process5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_63_1.py", line 156, in test_process5
    self.assertEqual(self.processor.process(string_list), expected_output)
AssertionError: {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2} != {'hello': 2, 'world': 2, 'this': 2, 'is': 2, 'a': 2}
- {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2}
?                              -----------

+ {'a': 2, 'hello': 2, 'is': 2, 'this': 2, 'world': 2}
?                                       ++++++++++++


----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_calculate_word_frequency4 (ClassEval_63_4.NLPDataProcessorTestCalculate.test_calculate_word_frequency4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_63_4.py", line 113, in test_calculate_word_frequency4
    self.assertEqual(self.processor.calculate_word_frequency(words_list), expected_output)
AssertionError: {'%%%': 6, 'hello': 5, 'world': 4, 'a': 2, 'is': 2} != {'%%%': 6, 'hello': 5, 'world': 4, 'is': 2, 'this': 2}
- {'%%%': 6, 'a': 2, 'hello': 5, 'is': 2, 'world': 4}
?           --------

+ {'%%%': 6, 'hello': 5, 'is': 2, 'this': 2, 'world': 4}
?                                +++++++++++


======================================================================
FAIL: test_calculate_word_frequency5 (ClassEval_63_4.NLPDataProcessorTestCalculate.test_calculate_word_frequency5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_63_4.py", line 120, in test_calculate_word_frequency5
    self.assertEqual(self.processor.calculate_word_frequency(words_list), expected_output)
AssertionError: {'%%%': 12, 'hello': 10, 'world': 8, 'a': 4, 'is': 4} != {'%%%': 12, 'hello': 10, 'world': 8, 'is': 4, 'this': 4}
- {'%%%': 12, 'a': 4, 'hello': 10, 'is': 4, 'world': 8}
?            --------

+ {'%%%': 12, 'hello': 10, 'is': 4, 'this': 4, 'world': 8}
?                                  +++++++++++


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=2)
.F..F.
======================================================================
FAIL: test_process (ClassEval_63_4.NLPDataProcessorTestProcess.test_process)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_63_4.py", line 130, in test_process
    self.assertEqual(self.processor.process(string_list), expected_output)
AssertionError: {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2} != {'hello': 2, 'world': 2, 'this': 2, 'is': 2, 'a': 2}
- {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2}
?                              -----------

+ {'a': 2, 'hello': 2, 'is': 2, 'this': 2, 'world': 2}
?                                       ++++++++++++


======================================================================
FAIL: test_process5 (ClassEval_63_4.NLPDataProcessorTestProcess.test_process5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_63_4.py", line 150, in test_process5
    self.assertEqual(self.processor.process(string_list), expected_output)
AssertionError: {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2} != {'hello': 2, 'world': 2, 'this': 2, 'is': 2, 'a': 2}
- {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2}
?                              -----------

+ {'a': 2, 'hello': 2, 'is': 2, 'this': 2, 'world': 2}
?                                       ++++++++++++


----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=2)
..F..F
======================================================================
FAIL: test_text2int3 (ClassEval_97_0.Words2NumbersTestText2Int.test_text2int3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 86, in test_text2int3
    self.assertEqual(w2n.text2int("two thousand and nineteen"), "2019")
AssertionError: '2018' != '2019'
- 2018
?    ^
+ 2019
?    ^


======================================================================
FAIL: test_text2int6 (ClassEval_97_0.Words2NumbersTestText2Int.test_text2int6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 98, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
AssertionError: '' != '1000169'
+ 1000169


----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=2)
FFF..F
======================================================================
FAIL: test_is_valid_input (ClassEval_97_0.Words2NumbersTestIsValidInput.test_is_valid_input)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 103, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input2 (ClassEval_97_0.Words2NumbersTestIsValidInput.test_is_valid_input2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 107, in test_is_valid_input2
    self.assertTrue(w2n.is_valid_input("second hundred and third"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_0.Words2NumbersTestIsValidInput.test_is_valid_input3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 111, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_0.Words2NumbersTestIsValidInput.test_is_valid_input6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 123, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=4)
.....F
======================================================================
FAIL: test_text2int6 (ClassEval_97_1.Words2NumbersTestText2Int.test_text2int6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 99, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
AssertionError: '' != '1000169'
+ 1000169


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.FF..F
======================================================================
FAIL: test_is_valid_input2 (ClassEval_97_1.Words2NumbersTestIsValidInput.test_is_valid_input2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 108, in test_is_valid_input2
    self.assertTrue(w2n.is_valid_input("second hundred and third"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_1.Words2NumbersTestIsValidInput.test_is_valid_input3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 112, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_1.Words2NumbersTestIsValidInput.test_is_valid_input6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 124, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=3)
.FFFFF
======================================================================
FAIL: test_text2int2 (ClassEval_97_2.Words2NumbersTestText2Int.test_text2int2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 106, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
AssertionError: '23' != '123'
- 23
+ 123
? +


======================================================================
FAIL: test_text2int3 (ClassEval_97_2.Words2NumbersTestText2Int.test_text2int3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 110, in test_text2int3
    self.assertEqual(w2n.text2int("two thousand and nineteen"), "2019")
AssertionError: '19' != '2019'
- 19
+ 2019
? ++


======================================================================
FAIL: test_text2int4 (ClassEval_97_2.Words2NumbersTestText2Int.test_text2int4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 114, in test_text2int4
    self.assertEqual(w2n.text2int("one hundred and one"), "101")
AssertionError: '1' != '101'
- 1
+ 101


======================================================================
FAIL: test_text2int5 (ClassEval_97_2.Words2NumbersTestText2Int.test_text2int5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 118, in test_text2int5
    self.assertEqual(w2n.text2int("one million and eleven"), "1000011")
AssertionError: '11' != '1000011'
- 11
+ 1000011


======================================================================
FAIL: test_text2int6 (ClassEval_97_2.Words2NumbersTestText2Int.test_text2int6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 122, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
AssertionError: '69' != '1000169'
- 69
+ 1000169


----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=5)
.....F
======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_2.Words2NumbersTestIsValidInput.test_is_valid_input6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 147, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....F
======================================================================
FAIL: test_text2int6 (ClassEval_97_3.Words2NumbersTestText2Int.test_text2int6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 97, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
AssertionError: '' != '1000169'
+ 1000169


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.FF..F
======================================================================
FAIL: test_is_valid_input2 (ClassEval_97_3.Words2NumbersTestIsValidInput.test_is_valid_input2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 106, in test_is_valid_input2
    self.assertTrue(w2n.is_valid_input("second hundred and third"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_3.Words2NumbersTestIsValidInput.test_is_valid_input3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 110, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_3.Words2NumbersTestIsValidInput.test_is_valid_input6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 122, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=3)
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.....F
======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_4.Words2NumbersTestIsValidInput.test_is_valid_input6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 124, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.002s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_0.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_0.py", line 108, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple
+ 


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_0.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_0.py", line 115, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'red'
- apple
+ red


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_2.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_2.py", line 106, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple
+ 


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_2.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_2.py", line 113, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'red'
- apple
+ red


----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=2)
EEEEE
======================================================================
ERROR: test_add_word_1 (ClassEval_53_3.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 8, in test_add_word_1
    longestWord = LongestWord()
NameError: name 'LongestWord' is not defined

======================================================================
ERROR: test_add_word_2 (ClassEval_53_3.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 13, in test_add_word_2
    longestWord = LongestWord()
NameError: name 'LongestWord' is not defined

======================================================================
ERROR: test_add_word_3 (ClassEval_53_3.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 19, in test_add_word_3
    longestWord = LongestWord()
NameError: name 'LongestWord' is not defined

======================================================================
ERROR: test_add_word_4 (ClassEval_53_3.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 26, in test_add_word_4
    longestWord = LongestWord()
NameError: name 'LongestWord' is not defined

======================================================================
ERROR: test_add_word_5 (ClassEval_53_3.LongestWordTestAddWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 34, in test_add_word_5
    longestWord = LongestWord()
NameError: name 'LongestWord' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
EEEEE
======================================================================
ERROR: test_find_longest_word_1 (ClassEval_53_3.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 45, in test_find_longest_word_1
    longestWord = LongestWord()
NameError: name 'LongestWord' is not defined

======================================================================
ERROR: test_find_longest_word_2 (ClassEval_53_3.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 51, in test_find_longest_word_2
    longestWord = LongestWord()
NameError: name 'LongestWord' is not defined

======================================================================
ERROR: test_find_longest_word_3 (ClassEval_53_3.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 56, in test_find_longest_word_3
    longestWord = LongestWord()
NameError: name 'LongestWord' is not defined

======================================================================
ERROR: test_find_longest_word_4 (ClassEval_53_3.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 62, in test_find_longest_word_4
    longestWord = LongestWord()
NameError: name 'LongestWord' is not defined

======================================================================
ERROR: test_find_longest_word_5 (ClassEval_53_3.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_3.py", line 68, in test_find_longest_word_5
    longestWord = LongestWord()
NameError: name 'LongestWord' is not defined

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (errors=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_4.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_4.py", line 104, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple
+ 


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_4.LongestWordTestFindLongestWord)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_53_4.py", line 111, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'red'
- apple
+ red


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F
======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_0.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_0.py", line 93, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: Lists differ: [['test'], ['apple'], ['dog']] != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

First differing element 0:
['test']
['is', 'test']

- [['test'], ['apple'], ['dog']]
+ [['is', 'test'], ['is', 'apple'], ['is', 'dog']]
?   ++++++          ++++++           ++++++


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
....F
======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_1.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_1.py", line 86, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: Lists differ: [['test'], ['apple'], ['dog']] != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

First differing element 0:
['test']
['is', 'test']

- [['test'], ['apple'], ['dog']]
+ [['is', 'test'], ['is', 'apple'], ['is', 'dog']]
?   ++++++          ++++++           ++++++


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F
======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_2.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_2.py", line 92, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: Lists differ: [['test'], ['apple'], ['dog']] != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

First differing element 0:
['test']
['is', 'test']

- [['test'], ['apple'], ['dog']]
+ [['is', 'test'], ['is', 'apple'], ['is', 'dog']]
?   ++++++          ++++++           ++++++


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F
======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_3.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_3.py", line 93, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: Lists differ: [['test'], ['apple'], ['dog']] != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

First differing element 0:
['test']
['is', 'test']

- [['test'], ['apple'], ['dog']]
+ [['is', 'test'], ['is', 'apple'], ['is', 'dog']]
?   ++++++          ++++++           ++++++


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F
======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_4.NLPDataProcessorTestRemove)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_62_4.py", line 91, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: Lists differ: [['test'], ['apple'], ['dog']] != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

First differing element 0:
['test']
['is', 'test']

- [['test'], ['apple'], ['dog']]
+ [['is', 'test'], ['is', 'apple'], ['is', 'dog']]
?   ++++++          ++++++           ++++++


----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_calculate_word_frequency4 (ClassEval_63_0.NLPDataProcessorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_63_0.py", line 120, in test_calculate_word_frequency4
    self.assertEqual(self.processor.calculate_word_frequency(words_list), expected_output)
AssertionError: {'%%%': 6, 'hello': 5, 'world': 4, 'a': 2, 'is': 2} != {'%%%': 6, 'hello': 5, 'world': 4, 'is': 2, 'this': 2}
- {'%%%': 6, 'a': 2, 'hello': 5, 'is': 2, 'world': 4}
?           --------

+ {'%%%': 6, 'hello': 5, 'is': 2, 'this': 2, 'world': 4}
?                                +++++++++++


======================================================================
FAIL: test_calculate_word_frequency5 (ClassEval_63_0.NLPDataProcessorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_63_0.py", line 127, in test_calculate_word_frequency5
    self.assertEqual(self.processor.calculate_word_frequency(words_list), expected_output)
AssertionError: {'%%%': 12, 'hello': 10, 'world': 8, 'a': 4, 'is': 4} != {'%%%': 12, 'hello': 10, 'world': 8, 'is': 4, 'this': 4}
- {'%%%': 12, 'a': 4, 'hello': 10, 'is': 4, 'world': 8}
?            --------

+ {'%%%': 12, 'hello': 10, 'is': 4, 'this': 4, 'world': 8}
?                                  +++++++++++


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=2)
.F..F.
======================================================================
FAIL: test_process (ClassEval_63_0.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_63_0.py", line 137, in test_process
    self.assertEqual(self.processor.process(string_list), expected_output)
AssertionError: {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2} != {'hello': 2, 'world': 2, 'this': 2, 'is': 2, 'a': 2}
- {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2}
?                              -----------

+ {'a': 2, 'hello': 2, 'is': 2, 'this': 2, 'world': 2}
?                                       ++++++++++++


======================================================================
FAIL: test_process5 (ClassEval_63_0.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_63_0.py", line 157, in test_process5
    self.assertEqual(self.processor.process(string_list), expected_output)
AssertionError: {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2} != {'hello': 2, 'world': 2, 'this': 2, 'is': 2, 'a': 2}
- {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2}
?                              -----------

+ {'a': 2, 'hello': 2, 'is': 2, 'this': 2, 'world': 2}
?                                       ++++++++++++


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_calculate_word_frequency4 (ClassEval_63_1.NLPDataProcessorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_63_1.py", line 119, in test_calculate_word_frequency4
    self.assertEqual(self.processor.calculate_word_frequency(words_list), expected_output)
AssertionError: {'%%%': 6, 'hello': 5, 'world': 4, 'a': 2, 'is': 2} != {'%%%': 6, 'hello': 5, 'world': 4, 'is': 2, 'this': 2}
- {'%%%': 6, 'a': 2, 'hello': 5, 'is': 2, 'world': 4}
?           --------

+ {'%%%': 6, 'hello': 5, 'is': 2, 'this': 2, 'world': 4}
?                                +++++++++++


======================================================================
FAIL: test_calculate_word_frequency5 (ClassEval_63_1.NLPDataProcessorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_63_1.py", line 126, in test_calculate_word_frequency5
    self.assertEqual(self.processor.calculate_word_frequency(words_list), expected_output)
AssertionError: {'%%%': 12, 'hello': 10, 'world': 8, 'a': 4, 'is': 4} != {'%%%': 12, 'hello': 10, 'world': 8, 'is': 4, 'this': 4}
- {'%%%': 12, 'a': 4, 'hello': 10, 'is': 4, 'world': 8}
?            --------

+ {'%%%': 12, 'hello': 10, 'is': 4, 'this': 4, 'world': 8}
?                                  +++++++++++


----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=2)
.F..F.
======================================================================
FAIL: test_process (ClassEval_63_1.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_63_1.py", line 136, in test_process
    self.assertEqual(self.processor.process(string_list), expected_output)
AssertionError: {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2} != {'hello': 2, 'world': 2, 'this': 2, 'is': 2, 'a': 2}
- {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2}
?                              -----------

+ {'a': 2, 'hello': 2, 'is': 2, 'this': 2, 'world': 2}
?                                       ++++++++++++


======================================================================
FAIL: test_process5 (ClassEval_63_1.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_63_1.py", line 156, in test_process5
    self.assertEqual(self.processor.process(string_list), expected_output)
AssertionError: {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2} != {'hello': 2, 'world': 2, 'this': 2, 'is': 2, 'a': 2}
- {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2}
?                              -----------

+ {'a': 2, 'hello': 2, 'is': 2, 'this': 2, 'world': 2}
?                                       ++++++++++++


----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
...FF
======================================================================
FAIL: test_calculate_word_frequency4 (ClassEval_63_4.NLPDataProcessorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_63_4.py", line 113, in test_calculate_word_frequency4
    self.assertEqual(self.processor.calculate_word_frequency(words_list), expected_output)
AssertionError: {'%%%': 6, 'hello': 5, 'world': 4, 'a': 2, 'is': 2} != {'%%%': 6, 'hello': 5, 'world': 4, 'is': 2, 'this': 2}
- {'%%%': 6, 'a': 2, 'hello': 5, 'is': 2, 'world': 4}
?           --------

+ {'%%%': 6, 'hello': 5, 'is': 2, 'this': 2, 'world': 4}
?                                +++++++++++


======================================================================
FAIL: test_calculate_word_frequency5 (ClassEval_63_4.NLPDataProcessorTestCalculate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_63_4.py", line 120, in test_calculate_word_frequency5
    self.assertEqual(self.processor.calculate_word_frequency(words_list), expected_output)
AssertionError: {'%%%': 12, 'hello': 10, 'world': 8, 'a': 4, 'is': 4} != {'%%%': 12, 'hello': 10, 'world': 8, 'is': 4, 'this': 4}
- {'%%%': 12, 'a': 4, 'hello': 10, 'is': 4, 'world': 8}
?            --------

+ {'%%%': 12, 'hello': 10, 'is': 4, 'this': 4, 'world': 8}
?                                  +++++++++++


----------------------------------------------------------------------
Ran 5 tests in 0.008s

FAILED (failures=2)
.F..F.
======================================================================
FAIL: test_process (ClassEval_63_4.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_63_4.py", line 130, in test_process
    self.assertEqual(self.processor.process(string_list), expected_output)
AssertionError: {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2} != {'hello': 2, 'world': 2, 'this': 2, 'is': 2, 'a': 2}
- {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2}
?                              -----------

+ {'a': 2, 'hello': 2, 'is': 2, 'this': 2, 'world': 2}
?                                       ++++++++++++


======================================================================
FAIL: test_process5 (ClassEval_63_4.NLPDataProcessorTestProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_63_4.py", line 150, in test_process5
    self.assertEqual(self.processor.process(string_list), expected_output)
AssertionError: {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2} != {'hello': 2, 'world': 2, 'this': 2, 'is': 2, 'a': 2}
- {'a': 2, 'hello': 2, 'is': 2, 'test': 2, 'this': 2}
?                              -----------

+ {'a': 2, 'hello': 2, 'is': 2, 'this': 2, 'world': 2}
?                                       ++++++++++++


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=2)
..F..F
======================================================================
FAIL: test_text2int3 (ClassEval_97_0.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_0.py", line 86, in test_text2int3
    self.assertEqual(w2n.text2int("two thousand and nineteen"), "2019")
AssertionError: '2018' != '2019'
- 2018
?    ^
+ 2019
?    ^


======================================================================
FAIL: test_text2int6 (ClassEval_97_0.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_0.py", line 98, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
AssertionError: '' != '1000169'
+ 1000169

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=2)
FFF..F
======================================================================
FAIL: test_is_valid_input (ClassEval_97_0.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_0.py", line 103, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input2 (ClassEval_97_0.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_0.py", line 107, in test_is_valid_input2
    self.assertTrue(w2n.is_valid_input("second hundred and third"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_0.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_0.py", line 111, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_0.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_0.py", line 123, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=4)
.....F
======================================================================
FAIL: test_text2int6 (ClassEval_97_1.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_1.py", line 99, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
AssertionError: '' != '1000169'
+ 1000169

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.FF..F
======================================================================
FAIL: test_is_valid_input2 (ClassEval_97_1.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_1.py", line 108, in test_is_valid_input2
    self.assertTrue(w2n.is_valid_input("second hundred and third"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_1.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_1.py", line 112, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_1.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_1.py", line 124, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=3)
.FFFFF
======================================================================
FAIL: test_text2int2 (ClassEval_97_2.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_2.py", line 106, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
AssertionError: '23' != '123'
- 23
+ 123
? +


======================================================================
FAIL: test_text2int3 (ClassEval_97_2.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_2.py", line 110, in test_text2int3
    self.assertEqual(w2n.text2int("two thousand and nineteen"), "2019")
AssertionError: '19' != '2019'
- 19
+ 2019
? ++


======================================================================
FAIL: test_text2int4 (ClassEval_97_2.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_2.py", line 114, in test_text2int4
    self.assertEqual(w2n.text2int("one hundred and one"), "101")
AssertionError: '1' != '101'
- 1
+ 101


======================================================================
FAIL: test_text2int5 (ClassEval_97_2.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_2.py", line 118, in test_text2int5
    self.assertEqual(w2n.text2int("one million and eleven"), "1000011")
AssertionError: '11' != '1000011'
- 11
+ 1000011


======================================================================
FAIL: test_text2int6 (ClassEval_97_2.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_2.py", line 122, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
AssertionError: '69' != '1000169'
- 69
+ 1000169


----------------------------------------------------------------------
Ran 6 tests in 0.005s

FAILED (failures=5)
.....F
======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_2.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_2.py", line 147, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=1)
.....F
======================================================================
FAIL: test_text2int6 (ClassEval_97_3.Words2NumbersTestText2Int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_3.py", line 97, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
AssertionError: '' != '1000169'
+ 1000169

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
.FF..F
======================================================================
FAIL: test_is_valid_input2 (ClassEval_97_3.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_3.py", line 106, in test_is_valid_input2
    self.assertTrue(w2n.is_valid_input("second hundred and third"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_3.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_3.py", line 110, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_3.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_3.py", line 122, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=3)
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.....F
======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_4.Words2NumbersTestIsValidInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tanuj\Desktop\CS540\repo\CS540\classeval_evaluation\ClassEval_97_4.py", line 124, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
