.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_0.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_0.py", line 104, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_0.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_0.py", line 111, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'red'
- apple
+ red


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_1.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_1.py", line 104, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_1.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_1.py", line 111, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'red'
- apple
+ red


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_2.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_2.py", line 106, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_2.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_2.py", line 113, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'red'
- apple
+ red


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_3.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 106, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_3.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_3.py", line 113, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'red'
- apple
+ red


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
...FF
======================================================================
FAIL: test_find_longest_word_4 (ClassEval_53_4.LongestWordTestFindLongestWord.test_find_longest_word_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_4.py", line 106, in test_find_longest_word_4
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != ''
- apple


======================================================================
FAIL: test_find_longest_word_5 (ClassEval_53_4.LongestWordTestFindLongestWord.test_find_longest_word_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_53_4.py", line 113, in test_find_longest_word_5
    self.assertEqual('apple', longestWord.find_longest_word(sentence))
AssertionError: 'apple' != 'red'
- apple
+ red


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F
======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_0.NLPDataProcessorTestRemove.test_remove_stop_words_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_0.py", line 79, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: Lists differ: [['test'], ['apple'], ['dog']] != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

First differing element 0:
['test']
['is', 'test']

- [['test'], ['apple'], ['dog']]
+ [['is', 'test'], ['is', 'apple'], ['is', 'dog']]
?   ++++++          ++++++           ++++++


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F
======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_1.NLPDataProcessorTestRemove.test_remove_stop_words_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_1.py", line 79, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: Lists differ: [['test'], ['apple'], ['dog']] != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

First differing element 0:
['test']
['is', 'test']

- [['test'], ['apple'], ['dog']]
+ [['is', 'test'], ['is', 'apple'], ['is', 'dog']]
?   ++++++          ++++++           ++++++


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F
======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_2.NLPDataProcessorTestRemove.test_remove_stop_words_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_2.py", line 81, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: Lists differ: [['test'], ['apple'], ['dog']] != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

First differing element 0:
['test']
['is', 'test']

- [['test'], ['apple'], ['dog']]
+ [['is', 'test'], ['is', 'apple'], ['is', 'dog']]
?   ++++++          ++++++           ++++++


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F
======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_3.NLPDataProcessorTestRemove.test_remove_stop_words_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_3.py", line 81, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: Lists differ: [['test'], ['apple'], ['dog']] != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

First differing element 0:
['test']
['is', 'test']

- [['test'], ['apple'], ['dog']]
+ [['is', 'test'], ['is', 'apple'], ['is', 'dog']]
?   ++++++          ++++++           ++++++


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
....F
======================================================================
FAIL: test_remove_stop_words_5 (ClassEval_62_4.NLPDataProcessorTestRemove.test_remove_stop_words_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_62_4.py", line 79, in test_remove_stop_words_5
    self.assertEqual(words_list, expected_words_list)
AssertionError: Lists differ: [['test'], ['apple'], ['dog']] != [['is', 'test'], ['is', 'apple'], ['is', 'dog']]

First differing element 0:
['test']
['is', 'test']

- [['test'], ['apple'], ['dog']]
+ [['is', 'test'], ['is', 'apple'], ['is', 'dog']]
?   ++++++          ++++++           ++++++


----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
EE...E
======================================================================
ERROR: test_text2int (ClassEval_97_0.Words2NumbersTestText2Int.test_text2int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 68, in test_text2int
    self.assertEqual(w2n.text2int("thirty-two"), "32")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 41, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: thirty-two

======================================================================
ERROR: test_text2int2 (ClassEval_97_0.Words2NumbersTestText2Int.test_text2int2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 72, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 41, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: twenty-three

======================================================================
ERROR: test_text2int6 (ClassEval_97_0.Words2NumbersTestText2Int.test_text2int6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 88, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 41, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: sixty-ninth

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=3)
FFF..F
======================================================================
FAIL: test_is_valid_input (ClassEval_97_0.Words2NumbersTestIsValidInput.test_is_valid_input)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 93, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input2 (ClassEval_97_0.Words2NumbersTestIsValidInput.test_is_valid_input2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 97, in test_is_valid_input2
    self.assertTrue(w2n.is_valid_input("second hundred and third"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_0.Words2NumbersTestIsValidInput.test_is_valid_input3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 101, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_0.Words2NumbersTestIsValidInput.test_is_valid_input6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_0.py", line 113, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=4)
EE...E
======================================================================
ERROR: test_text2int (ClassEval_97_1.Words2NumbersTestText2Int.test_text2int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 68, in test_text2int
    self.assertEqual(w2n.text2int("thirty-two"), "32")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 41, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: thirty-two

======================================================================
ERROR: test_text2int2 (ClassEval_97_1.Words2NumbersTestText2Int.test_text2int2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 72, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 41, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: twenty-three

======================================================================
ERROR: test_text2int6 (ClassEval_97_1.Words2NumbersTestText2Int.test_text2int6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 88, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 41, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: sixty-ninth

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (errors=3)
FFF..F
======================================================================
FAIL: test_is_valid_input (ClassEval_97_1.Words2NumbersTestIsValidInput.test_is_valid_input)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 93, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input2 (ClassEval_97_1.Words2NumbersTestIsValidInput.test_is_valid_input2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 97, in test_is_valid_input2
    self.assertTrue(w2n.is_valid_input("second hundred and third"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_1.Words2NumbersTestIsValidInput.test_is_valid_input3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 101, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_1.Words2NumbersTestIsValidInput.test_is_valid_input6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_1.py", line 113, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=4)
EE...E
======================================================================
ERROR: test_text2int (ClassEval_97_2.Words2NumbersTestText2Int.test_text2int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 68, in test_text2int
    self.assertEqual(w2n.text2int("thirty-two"), "32")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 41, in text2int
    raise ValueError("Illegal word: " + word)
ValueError: Illegal word: thirty-two

======================================================================
ERROR: test_text2int2 (ClassEval_97_2.Words2NumbersTestText2Int.test_text2int2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 72, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 41, in text2int
    raise ValueError("Illegal word: " + word)
ValueError: Illegal word: twenty-three

======================================================================
ERROR: test_text2int6 (ClassEval_97_2.Words2NumbersTestText2Int.test_text2int6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 88, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 41, in text2int
    raise ValueError("Illegal word: " + word)
ValueError: Illegal word: sixty-ninth

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=3)
FFF..F
======================================================================
FAIL: test_is_valid_input (ClassEval_97_2.Words2NumbersTestIsValidInput.test_is_valid_input)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 93, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input2 (ClassEval_97_2.Words2NumbersTestIsValidInput.test_is_valid_input2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 97, in test_is_valid_input2
    self.assertTrue(w2n.is_valid_input("second hundred and third"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_2.Words2NumbersTestIsValidInput.test_is_valid_input3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 101, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_2.Words2NumbersTestIsValidInput.test_is_valid_input6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_2.py", line 113, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=4)
EE...E
======================================================================
ERROR: test_text2int (ClassEval_97_3.Words2NumbersTestText2Int.test_text2int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 68, in test_text2int
    self.assertEqual(w2n.text2int("thirty-two"), "32")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 41, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: thirty-two

======================================================================
ERROR: test_text2int2 (ClassEval_97_3.Words2NumbersTestText2Int.test_text2int2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 72, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 41, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: twenty-three

======================================================================
ERROR: test_text2int6 (ClassEval_97_3.Words2NumbersTestText2Int.test_text2int6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 88, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 41, in text2int
    raise Exception("Illegal word: " + word)
Exception: Illegal word: sixty-ninth

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=3)
FFF..F
======================================================================
FAIL: test_is_valid_input (ClassEval_97_3.Words2NumbersTestIsValidInput.test_is_valid_input)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 93, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input2 (ClassEval_97_3.Words2NumbersTestIsValidInput.test_is_valid_input2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 97, in test_is_valid_input2
    self.assertTrue(w2n.is_valid_input("second hundred and third"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_3.Words2NumbersTestIsValidInput.test_is_valid_input3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 101, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_3.Words2NumbersTestIsValidInput.test_is_valid_input6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_3.py", line 113, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=4)
EE...E
======================================================================
ERROR: test_text2int (ClassEval_97_4.Words2NumbersTestText2Int.test_text2int)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 68, in test_text2int
    self.assertEqual(w2n.text2int("thirty-two"), "32")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 41, in text2int
    raise Exception('Illegal word: ' + word)
Exception: Illegal word: thirty-two

======================================================================
ERROR: test_text2int2 (ClassEval_97_4.Words2NumbersTestText2Int.test_text2int2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 72, in test_text2int2
    self.assertEqual(w2n.text2int("one hundred and twenty-three"), "123")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 41, in text2int
    raise Exception('Illegal word: ' + word)
Exception: Illegal word: twenty-three

======================================================================
ERROR: test_text2int6 (ClassEval_97_4.Words2NumbersTestText2Int.test_text2int6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 88, in test_text2int6
    self.assertEqual(w2n.text2int("one million one hundred sixty-ninth"), "1000169")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 41, in text2int
    raise Exception('Illegal word: ' + word)
Exception: Illegal word: sixty-ninth

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=3)
FFF..F
======================================================================
FAIL: test_is_valid_input (ClassEval_97_4.Words2NumbersTestIsValidInput.test_is_valid_input)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 93, in test_is_valid_input
    self.assertTrue(w2n.is_valid_input("twenty-five thousand three hundred and forty-two"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input2 (ClassEval_97_4.Words2NumbersTestIsValidInput.test_is_valid_input2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 97, in test_is_valid_input2
    self.assertTrue(w2n.is_valid_input("second hundred and third"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input3 (ClassEval_97_4.Words2NumbersTestIsValidInput.test_is_valid_input3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 101, in test_is_valid_input3
    self.assertTrue(w2n.is_valid_input("twenty-fifth thousand three hundred and forty-second"))
AssertionError: False is not true

======================================================================
FAIL: test_is_valid_input6 (ClassEval_97_4.Words2NumbersTestIsValidInput.test_is_valid_input6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_97_4.py", line 113, in test_is_valid_input6
    self.assertTrue(w2n.is_valid_input("fifteenth hundred"))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=4)
