..
----------------------------------------------------------------------
Ran 2 tests in 0.005s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.005s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.005s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.005s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.030s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.005s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.008s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.007s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.005s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.009s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.006s

OK
..
----------------------------------------------------------------------
Ran 2 tests in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.006s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.005s

OK
.F
======================================================================
FAIL: test_create_table_2 (ClassEval_14_4.BookManagementDBTestCreateTable.test_create_table_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_14_4.py", line 127, in test_create_table_2
    self.assertEqual(column_names, expected_column_names)
AssertionError: Lists differ: ['id', 'title', 'author', 'availability'] != ['id', 'title', 'author', 'available']

First differing element 3:
'availability'
'available'

- ['id', 'title', 'author', 'availability']
?                                   - ^^^

+ ['id', 'title', 'author', 'available']
?                                    ^


----------------------------------------------------------------------
Ran 2 tests in 0.007s

FAILED (failures=1)
E
======================================================================
ERROR: test_add_book (ClassEval_14_4.BookManagementDBTestAddBook.test_add_book)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_14_4.py", line 149, in test_add_book
    self.cursor.execute("SELECT title, author, available FROM books WHERE id=1")
sqlite3.OperationalError: no such column: available

----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (errors=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.005s

OK
E
======================================================================
ERROR: test_borrow_book (ClassEval_14_4.BookManagementDBTestBorrowBook.test_borrow_book)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_14_4.py", line 200, in test_borrow_book
    self.cursor.execute("SELECT available FROM books WHERE id=1")
sqlite3.OperationalError: no such column: available

----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (errors=1)
E
======================================================================
ERROR: test_return_book (ClassEval_14_4.BookManagementDBTestReturnBook.test_return_book)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_14_4.py", line 225, in test_return_book
    self.cursor.execute("SELECT available FROM books WHERE id=1")
sqlite3.OperationalError: no such column: available

----------------------------------------------------------------------
Ran 1 test in 0.008s

FAILED (errors=1)
.
----------------------------------------------------------------------
Ran 1 test in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.015s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.026s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.027s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.034s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.007s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.024s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.022s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.035s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.009s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.009s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.027s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.026s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.034s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.013s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.033s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.034s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.042s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.009s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.011s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.029s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.027s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.030s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.068s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.020s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.024s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.005s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.019s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.016s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.021s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.015s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.016s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.022s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.006s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.017s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.018s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.019s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.004s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.016s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.014s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.019s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.003s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.001s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.......
----------------------------------------------------------------------
Ran 7 tests in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.001s

OK
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.026s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.024s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.026s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.027s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.033s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.036s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.012s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.026s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.022s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.058s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.010s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.026s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.022s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.027s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.008s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.019s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.021s

OK
.....
----------------------------------------------------------------------
Ran 5 tests in 0.030s

OK
.
----------------------------------------------------------------------
Ran 1 test in 0.014s

OK
FFFFF
======================================================================
FAIL: test_insert_user_1 (ClassEval_92_0.UserLoginDBTestInsertUser.test_insert_user_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 129, in test_insert_user_1
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

======================================================================
FAIL: test_insert_user_2 (ClassEval_92_0.UserLoginDBTestInsertUser.test_insert_user_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 136, in test_insert_user_2
    self.assertEqual(user[0], 'user2')
AssertionError: ('user2', 'pass2') != 'user2'

======================================================================
FAIL: test_insert_user_3 (ClassEval_92_0.UserLoginDBTestInsertUser.test_insert_user_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 143, in test_insert_user_3
    self.assertEqual(user[0], 'user3')
AssertionError: ('user3', 'pass3') != 'user3'

======================================================================
FAIL: test_insert_user_4 (ClassEval_92_0.UserLoginDBTestInsertUser.test_insert_user_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 150, in test_insert_user_4
    self.assertEqual(user[0], 'user4')
AssertionError: ('user4', 'pass4') != 'user4'

======================================================================
FAIL: test_insert_user_5 (ClassEval_92_0.UserLoginDBTestInsertUser.test_insert_user_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 157, in test_insert_user_5
    self.assertEqual(user[0], 'user5')
AssertionError: ('user5', 'pass5') != 'user5'

----------------------------------------------------------------------
Ran 5 tests in 0.023s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_search_user_by_username_1 (ClassEval_92_0.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 186, in test_search_user_by_username_1
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

======================================================================
FAIL: test_search_user_by_username_2 (ClassEval_92_0.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 193, in test_search_user_by_username_2
    self.assertEqual(user[0], 'user2')
AssertionError: ('user2', 'pass2') != 'user2'

======================================================================
FAIL: test_search_user_by_username_3 (ClassEval_92_0.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 200, in test_search_user_by_username_3
    self.assertEqual(user[0], 'user3')
AssertionError: ('user3', 'pass3') != 'user3'

======================================================================
FAIL: test_search_user_by_username_4 (ClassEval_92_0.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 207, in test_search_user_by_username_4
    self.assertEqual(user[0], 'user4')
AssertionError: ('user4', 'pass4') != 'user4'

======================================================================
FAIL: test_search_user_by_username_5 (ClassEval_92_0.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 214, in test_search_user_by_username_5
    self.assertEqual(user[0], 'user5')
AssertionError: ('user5', 'pass5') != 'user5'

----------------------------------------------------------------------
Ran 5 tests in 0.020s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_delete_user_by_username_1 (ClassEval_92_0.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 243, in test_delete_user_by_username_1
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_2 (ClassEval_92_0.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 249, in test_delete_user_by_username_2
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_3 (ClassEval_92_0.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 255, in test_delete_user_by_username_3
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_4 (ClassEval_92_0.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 261, in test_delete_user_by_username_4
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_5 (ClassEval_92_0.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 267, in test_delete_user_by_username_5
    self.assertIsNone(user)
AssertionError: [] is not None

----------------------------------------------------------------------
Ran 5 tests in 0.024s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.015s

OK
F
======================================================================
FAIL: test_UserLoginDB (ClassEval_92_0.UserLoginDBTest.test_UserLoginDB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_0.py", line 341, in test_UserLoginDB
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_insert_user_1 (ClassEval_92_1.UserLoginDBTestInsertUser.test_insert_user_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_1.py", line 134, in test_insert_user_1
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

======================================================================
FAIL: test_insert_user_2 (ClassEval_92_1.UserLoginDBTestInsertUser.test_insert_user_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_1.py", line 141, in test_insert_user_2
    self.assertEqual(user[0], 'user2')
AssertionError: ('user2', 'pass2') != 'user2'

======================================================================
FAIL: test_insert_user_3 (ClassEval_92_1.UserLoginDBTestInsertUser.test_insert_user_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_1.py", line 148, in test_insert_user_3
    self.assertEqual(user[0], 'user3')
AssertionError: ('user3', 'pass3') != 'user3'

======================================================================
FAIL: test_insert_user_4 (ClassEval_92_1.UserLoginDBTestInsertUser.test_insert_user_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_1.py", line 155, in test_insert_user_4
    self.assertEqual(user[0], 'user4')
AssertionError: ('user4', 'pass4') != 'user4'

======================================================================
FAIL: test_insert_user_5 (ClassEval_92_1.UserLoginDBTestInsertUser.test_insert_user_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_1.py", line 162, in test_insert_user_5
    self.assertEqual(user[0], 'user5')
AssertionError: ('user5', 'pass5') != 'user5'

----------------------------------------------------------------------
Ran 5 tests in 0.021s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_search_user_by_username_1 (ClassEval_92_1.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_1.py", line 191, in test_search_user_by_username_1
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

======================================================================
FAIL: test_search_user_by_username_2 (ClassEval_92_1.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_1.py", line 198, in test_search_user_by_username_2
    self.assertEqual(user[0], 'user2')
AssertionError: ('user2', 'pass2') != 'user2'

======================================================================
FAIL: test_search_user_by_username_3 (ClassEval_92_1.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_1.py", line 205, in test_search_user_by_username_3
    self.assertEqual(user[0], 'user3')
AssertionError: ('user3', 'pass3') != 'user3'

======================================================================
FAIL: test_search_user_by_username_4 (ClassEval_92_1.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_1.py", line 212, in test_search_user_by_username_4
    self.assertEqual(user[0], 'user4')
AssertionError: ('user4', 'pass4') != 'user4'

======================================================================
FAIL: test_search_user_by_username_5 (ClassEval_92_1.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_1.py", line 219, in test_search_user_by_username_5
    self.assertEqual(user[0], 'user5')
AssertionError: ('user5', 'pass5') != 'user5'

----------------------------------------------------------------------
Ran 5 tests in 0.020s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_delete_user_by_username_1 (ClassEval_92_1.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_1.py", line 248, in test_delete_user_by_username_1
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_2 (ClassEval_92_1.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_1.py", line 254, in test_delete_user_by_username_2
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_3 (ClassEval_92_1.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_1.py", line 260, in test_delete_user_by_username_3
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_4 (ClassEval_92_1.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_1.py", line 266, in test_delete_user_by_username_4
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_5 (ClassEval_92_1.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_1.py", line 272, in test_delete_user_by_username_5
    self.assertIsNone(user)
AssertionError: [] is not None

----------------------------------------------------------------------
Ran 5 tests in 0.021s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.011s

OK
F
======================================================================
FAIL: test_UserLoginDB (ClassEval_92_1.UserLoginDBTest.test_UserLoginDB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_1.py", line 346, in test_UserLoginDB
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_insert_user_1 (ClassEval_92_2.UserLoginDBTestInsertUser.test_insert_user_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_2.py", line 138, in test_insert_user_1
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

======================================================================
FAIL: test_insert_user_2 (ClassEval_92_2.UserLoginDBTestInsertUser.test_insert_user_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_2.py", line 145, in test_insert_user_2
    self.assertEqual(user[0], 'user2')
AssertionError: ('user2', 'pass2') != 'user2'

======================================================================
FAIL: test_insert_user_3 (ClassEval_92_2.UserLoginDBTestInsertUser.test_insert_user_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_2.py", line 152, in test_insert_user_3
    self.assertEqual(user[0], 'user3')
AssertionError: ('user3', 'pass3') != 'user3'

======================================================================
FAIL: test_insert_user_4 (ClassEval_92_2.UserLoginDBTestInsertUser.test_insert_user_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_2.py", line 159, in test_insert_user_4
    self.assertEqual(user[0], 'user4')
AssertionError: ('user4', 'pass4') != 'user4'

======================================================================
FAIL: test_insert_user_5 (ClassEval_92_2.UserLoginDBTestInsertUser.test_insert_user_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_2.py", line 166, in test_insert_user_5
    self.assertEqual(user[0], 'user5')
AssertionError: ('user5', 'pass5') != 'user5'

----------------------------------------------------------------------
Ran 5 tests in 0.014s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_search_user_by_username_1 (ClassEval_92_2.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_2.py", line 195, in test_search_user_by_username_1
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

======================================================================
FAIL: test_search_user_by_username_2 (ClassEval_92_2.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_2.py", line 202, in test_search_user_by_username_2
    self.assertEqual(user[0], 'user2')
AssertionError: ('user2', 'pass2') != 'user2'

======================================================================
FAIL: test_search_user_by_username_3 (ClassEval_92_2.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_2.py", line 209, in test_search_user_by_username_3
    self.assertEqual(user[0], 'user3')
AssertionError: ('user3', 'pass3') != 'user3'

======================================================================
FAIL: test_search_user_by_username_4 (ClassEval_92_2.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_2.py", line 216, in test_search_user_by_username_4
    self.assertEqual(user[0], 'user4')
AssertionError: ('user4', 'pass4') != 'user4'

======================================================================
FAIL: test_search_user_by_username_5 (ClassEval_92_2.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_2.py", line 223, in test_search_user_by_username_5
    self.assertEqual(user[0], 'user5')
AssertionError: ('user5', 'pass5') != 'user5'

----------------------------------------------------------------------
Ran 5 tests in 0.014s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_delete_user_by_username_1 (ClassEval_92_2.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_2.py", line 252, in test_delete_user_by_username_1
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_2 (ClassEval_92_2.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_2.py", line 258, in test_delete_user_by_username_2
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_3 (ClassEval_92_2.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_2.py", line 264, in test_delete_user_by_username_3
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_4 (ClassEval_92_2.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_2.py", line 270, in test_delete_user_by_username_4
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_5 (ClassEval_92_2.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_2.py", line 276, in test_delete_user_by_username_5
    self.assertIsNone(user)
AssertionError: [] is not None

----------------------------------------------------------------------
Ran 5 tests in 0.018s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.012s

OK
F
======================================================================
FAIL: test_UserLoginDB (ClassEval_92_2.UserLoginDBTest.test_UserLoginDB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_2.py", line 350, in test_UserLoginDB
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_insert_user_1 (ClassEval_92_3.UserLoginDBTestInsertUser.test_insert_user_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_3.py", line 135, in test_insert_user_1
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

======================================================================
FAIL: test_insert_user_2 (ClassEval_92_3.UserLoginDBTestInsertUser.test_insert_user_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_3.py", line 142, in test_insert_user_2
    self.assertEqual(user[0], 'user2')
AssertionError: ('user2', 'pass2') != 'user2'

======================================================================
FAIL: test_insert_user_3 (ClassEval_92_3.UserLoginDBTestInsertUser.test_insert_user_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_3.py", line 149, in test_insert_user_3
    self.assertEqual(user[0], 'user3')
AssertionError: ('user3', 'pass3') != 'user3'

======================================================================
FAIL: test_insert_user_4 (ClassEval_92_3.UserLoginDBTestInsertUser.test_insert_user_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_3.py", line 156, in test_insert_user_4
    self.assertEqual(user[0], 'user4')
AssertionError: ('user4', 'pass4') != 'user4'

======================================================================
FAIL: test_insert_user_5 (ClassEval_92_3.UserLoginDBTestInsertUser.test_insert_user_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_3.py", line 163, in test_insert_user_5
    self.assertEqual(user[0], 'user5')
AssertionError: ('user5', 'pass5') != 'user5'

----------------------------------------------------------------------
Ran 5 tests in 0.018s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_search_user_by_username_1 (ClassEval_92_3.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_3.py", line 192, in test_search_user_by_username_1
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

======================================================================
FAIL: test_search_user_by_username_2 (ClassEval_92_3.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_3.py", line 199, in test_search_user_by_username_2
    self.assertEqual(user[0], 'user2')
AssertionError: ('user2', 'pass2') != 'user2'

======================================================================
FAIL: test_search_user_by_username_3 (ClassEval_92_3.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_3.py", line 206, in test_search_user_by_username_3
    self.assertEqual(user[0], 'user3')
AssertionError: ('user3', 'pass3') != 'user3'

======================================================================
FAIL: test_search_user_by_username_4 (ClassEval_92_3.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_3.py", line 213, in test_search_user_by_username_4
    self.assertEqual(user[0], 'user4')
AssertionError: ('user4', 'pass4') != 'user4'

======================================================================
FAIL: test_search_user_by_username_5 (ClassEval_92_3.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_3.py", line 220, in test_search_user_by_username_5
    self.assertEqual(user[0], 'user5')
AssertionError: ('user5', 'pass5') != 'user5'

----------------------------------------------------------------------
Ran 5 tests in 0.016s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_delete_user_by_username_1 (ClassEval_92_3.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_3.py", line 249, in test_delete_user_by_username_1
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_2 (ClassEval_92_3.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_3.py", line 255, in test_delete_user_by_username_2
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_3 (ClassEval_92_3.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_3.py", line 261, in test_delete_user_by_username_3
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_4 (ClassEval_92_3.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_3.py", line 267, in test_delete_user_by_username_4
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_5 (ClassEval_92_3.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_3.py", line 273, in test_delete_user_by_username_5
    self.assertIsNone(user)
AssertionError: [] is not None

----------------------------------------------------------------------
Ran 5 tests in 0.020s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.013s

OK
F
======================================================================
FAIL: test_UserLoginDB (ClassEval_92_3.UserLoginDBTest.test_UserLoginDB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_3.py", line 347, in test_UserLoginDB
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_insert_user_1 (ClassEval_92_4.UserLoginDBTestInsertUser.test_insert_user_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_4.py", line 134, in test_insert_user_1
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

======================================================================
FAIL: test_insert_user_2 (ClassEval_92_4.UserLoginDBTestInsertUser.test_insert_user_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_4.py", line 141, in test_insert_user_2
    self.assertEqual(user[0], 'user2')
AssertionError: ('user2', 'pass2') != 'user2'

======================================================================
FAIL: test_insert_user_3 (ClassEval_92_4.UserLoginDBTestInsertUser.test_insert_user_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_4.py", line 148, in test_insert_user_3
    self.assertEqual(user[0], 'user3')
AssertionError: ('user3', 'pass3') != 'user3'

======================================================================
FAIL: test_insert_user_4 (ClassEval_92_4.UserLoginDBTestInsertUser.test_insert_user_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_4.py", line 155, in test_insert_user_4
    self.assertEqual(user[0], 'user4')
AssertionError: ('user4', 'pass4') != 'user4'

======================================================================
FAIL: test_insert_user_5 (ClassEval_92_4.UserLoginDBTestInsertUser.test_insert_user_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_4.py", line 162, in test_insert_user_5
    self.assertEqual(user[0], 'user5')
AssertionError: ('user5', 'pass5') != 'user5'

----------------------------------------------------------------------
Ran 5 tests in 0.012s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_search_user_by_username_1 (ClassEval_92_4.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_4.py", line 191, in test_search_user_by_username_1
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

======================================================================
FAIL: test_search_user_by_username_2 (ClassEval_92_4.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_4.py", line 198, in test_search_user_by_username_2
    self.assertEqual(user[0], 'user2')
AssertionError: ('user2', 'pass2') != 'user2'

======================================================================
FAIL: test_search_user_by_username_3 (ClassEval_92_4.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_4.py", line 205, in test_search_user_by_username_3
    self.assertEqual(user[0], 'user3')
AssertionError: ('user3', 'pass3') != 'user3'

======================================================================
FAIL: test_search_user_by_username_4 (ClassEval_92_4.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_4.py", line 212, in test_search_user_by_username_4
    self.assertEqual(user[0], 'user4')
AssertionError: ('user4', 'pass4') != 'user4'

======================================================================
FAIL: test_search_user_by_username_5 (ClassEval_92_4.UserLoginDBTestSearchUserByUsername.test_search_user_by_username_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_4.py", line 219, in test_search_user_by_username_5
    self.assertEqual(user[0], 'user5')
AssertionError: ('user5', 'pass5') != 'user5'

----------------------------------------------------------------------
Ran 5 tests in 0.012s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_delete_user_by_username_1 (ClassEval_92_4.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_4.py", line 248, in test_delete_user_by_username_1
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_2 (ClassEval_92_4.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_4.py", line 254, in test_delete_user_by_username_2
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_3 (ClassEval_92_4.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_4.py", line 260, in test_delete_user_by_username_3
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_4 (ClassEval_92_4.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_4.py", line 266, in test_delete_user_by_username_4
    self.assertIsNone(user)
AssertionError: [] is not None

======================================================================
FAIL: test_delete_user_by_username_5 (ClassEval_92_4.UserLoginDBTestDeleteUserByUsername.test_delete_user_by_username_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_4.py", line 272, in test_delete_user_by_username_5
    self.assertIsNone(user)
AssertionError: [] is not None

----------------------------------------------------------------------
Ran 5 tests in 0.017s

FAILED (failures=5)
.....
----------------------------------------------------------------------
Ran 5 tests in 0.010s

OK
F
======================================================================
FAIL: test_UserLoginDB (ClassEval_92_4.UserLoginDBTest.test_UserLoginDB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_92_4.py", line 346, in test_UserLoginDB
    self.assertEqual(user[0], 'user1')
AssertionError: ('user1', 'pass1') != 'user1'

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
