FFFFFFFFF
======================================================================
FAIL: test_interpret_1 (ClassEval_5_0.AutomaticGuitarSimulatorTestInterpret.test_interpret_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 38, in test_interpret_1
    self.assertEqual(play_list, [{'Chord': 'C', 'Tune': '53231323'}])
AssertionError: None != [{'Chord': 'C', 'Tune': '53231323'}]

======================================================================
FAIL: test_interpret_2 (ClassEval_5_0.AutomaticGuitarSimulatorTestInterpret.test_interpret_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 43, in test_interpret_2
    self.assertEqual(play_list, [{'Chord': 'F', 'Tune': '43231323'}])
AssertionError: None != [{'Chord': 'F', 'Tune': '43231323'}]

======================================================================
FAIL: test_interpret_3 (ClassEval_5_0.AutomaticGuitarSimulatorTestInterpret.test_interpret_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 48, in test_interpret_3
    self.assertEqual(play_list, [{'Chord': 'Em', 'Tune': '43231323'}])
AssertionError: None != [{'Chord': 'Em', 'Tune': '43231323'}]

======================================================================
FAIL: test_interpret_4 (ClassEval_5_0.AutomaticGuitarSimulatorTestInterpret.test_interpret_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 53, in test_interpret_4
    self.assertEqual(play_list, [{'Chord': 'G', 'Tune': '63231323'}])
AssertionError: None != [{'Chord': 'G', 'Tune': '63231323'}]

======================================================================
FAIL: test_interpret_5 (ClassEval_5_0.AutomaticGuitarSimulatorTestInterpret.test_interpret_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 58, in test_interpret_5
    self.assertEqual(play_list, [{'Chord': 'F', 'Tune': '43231323'}, {'Chord': 'G', 'Tune': '63231323'}])
AssertionError: None != [{'Chord': 'F', 'Tune': '43231323'}, {'Chord': 'G', 'Tune': '63231323'}]

======================================================================
FAIL: test_interpret_6 (ClassEval_5_0.AutomaticGuitarSimulatorTestInterpret.test_interpret_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 63, in test_interpret_6
    self.assertEqual(play_list, [])
AssertionError: None != []

======================================================================
FAIL: test_interpret_7 (ClassEval_5_0.AutomaticGuitarSimulatorTestInterpret.test_interpret_7)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 68, in test_interpret_7
    self.assertEqual(play_list, [{'Chord': 'ABC', 'Tune': '43231323'}, {'Chord': 'DEF', 'Tune': '63231323'}])
AssertionError: None != [{'Chord': 'ABC', 'Tune': '43231323'}, {'Chord': 'DEF', 'Tune': '63231323'}]

======================================================================
FAIL: test_interpret_8 (ClassEval_5_0.AutomaticGuitarSimulatorTestInterpret.test_interpret_8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 73, in test_interpret_8
    self.assertEqual(play_list, [{'Chord': 'C', 'Tune': '53231323'}])
AssertionError: None != [{'Chord': 'C', 'Tune': '53231323'}]

======================================================================
FAIL: test_interpret_9 (ClassEval_5_0.AutomaticGuitarSimulatorTestInterpret.test_interpret_9)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 78, in test_interpret_9
    self.assertEqual(play_list, [])
AssertionError: None != []

----------------------------------------------------------------------
Ran 9 tests in 0.003s

FAILED (failures=9)
EEEEF
======================================================================
ERROR: test_display_1 (ClassEval_5_0.AutomaticGuitarSimulatorTestDisplay.test_display_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 85, in test_display_1
    str = context.display(play_list[0]['Chord'], play_list[0]['Tune'])
                          ~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_display_2 (ClassEval_5_0.AutomaticGuitarSimulatorTestDisplay.test_display_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 91, in test_display_2
    str = context.display(play_list[1]['Chord'], play_list[1]['Tune'])
                          ~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_display_3 (ClassEval_5_0.AutomaticGuitarSimulatorTestDisplay.test_display_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 97, in test_display_3
    str = context.display(play_list[0]['Chord'], play_list[0]['Tune'])
                          ~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: test_display_4 (ClassEval_5_0.AutomaticGuitarSimulatorTestDisplay.test_display_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 103, in test_display_4
    str = context.display(play_list[1]['Chord'], play_list[1]['Tune'])
                          ~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

======================================================================
FAIL: test_display_5 (ClassEval_5_0.AutomaticGuitarSimulatorTestDisplay.test_display_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 109, in test_display_5
    self.assertEqual(str, "Normal Guitar Playing -- Chord: , Play Tune: ")
AssertionError: None != 'Normal Guitar Playing -- Chord: , Play Tune: '

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1, errors=4)
F
======================================================================
FAIL: test_AutomaticGuitarSimulator (ClassEval_5_0.AutomaticGuitarSimulatorTest.test_AutomaticGuitarSimulator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_5_0.py", line 116, in test_AutomaticGuitarSimulator
    self.assertEqual(play_list, [{'Chord': 'C', 'Tune': '53231323'}])
AssertionError: None != [{'Chord': 'C', 'Tune': '53231323'}]

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
F.FFF
======================================================================
FAIL: test_add_book_1 (ClassEval_13_0.BookManagementTestAddBook.test_add_book_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 64, in test_add_book_1
    self.assertEqual({"book1": 1}, bookManagement.inventory)
AssertionError: {'book1': 1} != {}
- {'book1': 1}
+ {}

======================================================================
FAIL: test_add_book_3 (ClassEval_13_0.BookManagementTestAddBook.test_add_book_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 74, in test_add_book_3
    self.assertEqual({"book1": 3}, bookManagement.inventory)
AssertionError: {'book1': 3} != {}
- {'book1': 3}
+ {}

======================================================================
FAIL: test_add_book_4 (ClassEval_13_0.BookManagementTestAddBook.test_add_book_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 79, in test_add_book_4
    self.assertEqual({"book1": 2}, bookManagement.inventory)
AssertionError: {'book1': 2} != {}
- {'book1': 2}
+ {}

======================================================================
FAIL: test_add_book_5 (ClassEval_13_0.BookManagementTestAddBook.test_add_book_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 85, in test_add_book_5
    self.assertEqual({"book1": 3}, bookManagement.inventory)
AssertionError: {'book1': 3} != {}
- {'book1': 3}
+ {}

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=4)
FFFFF
======================================================================
FAIL: test_remove_book_1 (ClassEval_13_0.BookManagementTestRemoveBook.test_remove_book_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 97, in test_remove_book_1
    self.assertEqual(self.bookManagement.inventory, {"book2": 1})
AssertionError: {} != {'book2': 1}
- {}
+ {'book2': 1}

======================================================================
FAIL: test_remove_book_2 (ClassEval_13_0.BookManagementTestRemoveBook.test_remove_book_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 102, in test_remove_book_2
    self.assertEqual(self.bookManagement.inventory, {"book1": 1, "book2": 1})
AssertionError: {} != {'book1': 1, 'book2': 1}
- {}
+ {'book1': 1, 'book2': 1}

======================================================================
FAIL: test_remove_book_3 (ClassEval_13_0.BookManagementTestRemoveBook.test_remove_book_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 106, in test_remove_book_3
    with self.assertRaises(Exception):
AssertionError: Exception not raised

======================================================================
FAIL: test_remove_book_4 (ClassEval_13_0.BookManagementTestRemoveBook.test_remove_book_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 111, in test_remove_book_4
    with self.assertRaises(Exception):
AssertionError: Exception not raised

======================================================================
FAIL: test_remove_book_5 (ClassEval_13_0.BookManagementTestRemoveBook.test_remove_book_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 115, in test_remove_book_5
    with self.assertRaises(Exception):
AssertionError: Exception not raised

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F.FF.
======================================================================
FAIL: test_view_inventory_1 (ClassEval_13_0.BookManagementTestViewInventory.test_view_inventory_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 125, in test_view_inventory_1
    self.assertEqual(expected, bookManagement.inventory)
AssertionError: {'book1': 2, 'book2': 1} != {}
- {'book1': 2, 'book2': 1}
+ {}

======================================================================
FAIL: test_view_inventory_3 (ClassEval_13_0.BookManagementTestViewInventory.test_view_inventory_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 137, in test_view_inventory_3
    self.assertEqual(expected, bookManagement.inventory)
AssertionError: {'book1': 2, 'book2': 1} != {}
- {'book1': 2, 'book2': 1}
+ {}

======================================================================
FAIL: test_view_inventory_4 (ClassEval_13_0.BookManagementTestViewInventory.test_view_inventory_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 145, in test_view_inventory_4
    self.assertEqual(expected, bookManagement.inventory)
AssertionError: {'book2': 1} != {}
- {'book2': 1}
+ {}

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
FFFFF
======================================================================
FAIL: test_view_book_quantity_1 (ClassEval_13_0.BookManagementTestViewBookQuantity.test_view_book_quantity_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 161, in test_view_book_quantity_1
    self.assertEqual(2, bookManagement.view_book_quantity("book1"))
AssertionError: 2 != None

======================================================================
FAIL: test_view_book_quantity_2 (ClassEval_13_0.BookManagementTestViewBookQuantity.test_view_book_quantity_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 165, in test_view_book_quantity_2
    self.assertEqual(0, bookManagement.view_book_quantity("book1"))
AssertionError: 0 != None

======================================================================
FAIL: test_view_book_quantity_3 (ClassEval_13_0.BookManagementTestViewBookQuantity.test_view_book_quantity_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 170, in test_view_book_quantity_3
    self.assertEqual(2, bookManagement.view_book_quantity("book1"))
AssertionError: 2 != None

======================================================================
FAIL: test_view_book_quantity_4 (ClassEval_13_0.BookManagementTestViewBookQuantity.test_view_book_quantity_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 176, in test_view_book_quantity_4
    self.assertEqual(0, bookManagement.view_book_quantity("book1"))
AssertionError: 0 != None

======================================================================
FAIL: test_view_book_quantity_5 (ClassEval_13_0.BookManagementTestViewBookQuantity.test_view_book_quantity_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 182, in test_view_book_quantity_5
    self.assertEqual(1, bookManagement.view_book_quantity("book1"))
AssertionError: 1 != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F
======================================================================
FAIL: test_main (ClassEval_13_0.BookManagementTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_13_0.py", line 190, in test_main
    self.assertEqual(bookManagement.view_inventory(), {"book1": 2, "book2": 1})
AssertionError: None != {'book1': 2, 'book2': 1}

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_get_cookies (ClassEval_25_0.CookiesUtilTestGetCookies.test_get_cookies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 85, in test_get_cookies
    self.assertEqual(self.cookies_util.cookies, {'key1': 'value1', 'key2': 'value2'})
AssertionError: None != {'key1': 'value1', 'key2': 'value2'}

======================================================================
FAIL: test_get_cookies_2 (ClassEval_25_0.CookiesUtilTestGetCookies.test_get_cookies_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 92, in test_get_cookies_2
    self.assertEqual(self.cookies_util.cookies, {'key1': 'value1', 'key2': 'value2'})
AssertionError: None != {'key1': 'value1', 'key2': 'value2'}

======================================================================
FAIL: test_get_cookies_3 (ClassEval_25_0.CookiesUtilTestGetCookies.test_get_cookies_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 100, in test_get_cookies_3
    self.assertEqual(self.cookies_util.cookies, {'key1': 'value1', 'key2': 'value2'})
AssertionError: None != {'key1': 'value1', 'key2': 'value2'}

======================================================================
FAIL: test_get_cookies_4 (ClassEval_25_0.CookiesUtilTestGetCookies.test_get_cookies_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 109, in test_get_cookies_4
    self.assertEqual(self.cookies_util.cookies, {'key1': 'value1', 'key2': 'value2'})
AssertionError: None != {'key1': 'value1', 'key2': 'value2'}

======================================================================
FAIL: test_get_cookies_5 (ClassEval_25_0.CookiesUtilTestGetCookies.test_get_cookies_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 119, in test_get_cookies_5
    self.assertEqual(self.cookies_util.cookies, {'key1': 'value1', 'key2': 'value2'})
AssertionError: None != {'key1': 'value1', 'key2': 'value2'}

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFFF
======================================================================
FAIL: test_load_cookies (ClassEval_25_0.CookiesUtilTestLoadCookies.test_load_cookies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 126, in test_load_cookies
    self.assertEqual(self.cookies_util.load_cookies(), {'key1': 'value1', 'key2': 'value2'})
AssertionError: None != {'key1': 'value1', 'key2': 'value2'}

======================================================================
FAIL: test_load_cookies_2 (ClassEval_25_0.CookiesUtilTestLoadCookies.test_load_cookies_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 131, in test_load_cookies_2
    self.assertEqual(self.cookies_util.load_cookies(), {'key1': 'value1', 'key2': 'value2'})
AssertionError: None != {'key1': 'value1', 'key2': 'value2'}

======================================================================
FAIL: test_load_cookies_3 (ClassEval_25_0.CookiesUtilTestLoadCookies.test_load_cookies_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 137, in test_load_cookies_3
    self.assertEqual(self.cookies_util.load_cookies(), {'key1': 'value1', 'key2': 'value2'})
AssertionError: None != {'key1': 'value1', 'key2': 'value2'}

======================================================================
FAIL: test_load_cookies_4 (ClassEval_25_0.CookiesUtilTestLoadCookies.test_load_cookies_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 144, in test_load_cookies_4
    self.assertEqual(self.cookies_util.load_cookies(), {'key1': 'value1', 'key2': 'value2'})
AssertionError: None != {'key1': 'value1', 'key2': 'value2'}

======================================================================
FAIL: test_load_cookies_5 (ClassEval_25_0.CookiesUtilTestLoadCookies.test_load_cookies_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 152, in test_load_cookies_5
    self.assertEqual(self.cookies_util.load_cookies(), {'key1': 'value1', 'key2': 'value2'})
AssertionError: None != {'key1': 'value1', 'key2': 'value2'}

======================================================================
FAIL: test_load_cookies_6 (ClassEval_25_0.CookiesUtilTestLoadCookies.test_load_cookies_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 156, in test_load_cookies_6
    self.assertEqual(self.cookies_util.load_cookies(), {})
AssertionError: None != {}

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=6)
FFFFF.
======================================================================
FAIL: test_save_cookies (ClassEval_25_0.CookiesUtilTestSaveCookies.test_save_cookies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 165, in test_save_cookies
    self.assertTrue(self.cookies_util._save_cookies())
AssertionError: None is not true

======================================================================
FAIL: test_save_cookies_2 (ClassEval_25_0.CookiesUtilTestSaveCookies.test_save_cookies_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 170, in test_save_cookies_2
    self.assertTrue(self.cookies_util._save_cookies())
AssertionError: None is not true

======================================================================
FAIL: test_save_cookies_3 (ClassEval_25_0.CookiesUtilTestSaveCookies.test_save_cookies_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 176, in test_save_cookies_3
    self.assertTrue(self.cookies_util._save_cookies())
AssertionError: None is not true

======================================================================
FAIL: test_save_cookies_4 (ClassEval_25_0.CookiesUtilTestSaveCookies.test_save_cookies_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 183, in test_save_cookies_4
    self.assertTrue(self.cookies_util._save_cookies())
AssertionError: None is not true

======================================================================
FAIL: test_save_cookies_5 (ClassEval_25_0.CookiesUtilTestSaveCookies.test_save_cookies_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 191, in test_save_cookies_5
    self.assertTrue(self.cookies_util._save_cookies())
AssertionError: None is not true

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=5)
E
======================================================================
ERROR: test_set_cookies (ClassEval_25_0.CookiesUtilTestSetCookies.test_set_cookies)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 206, in test_set_cookies
    self.assertEqual(request['cookies'], "cookies={'key1': 'value1', 'key2': 'value2'}")
                     ~~~~~~~^^^^^^^^^^^
KeyError: 'cookies'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
F
======================================================================
FAIL: test_main (ClassEval_25_0.CookiesUtilTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_25_0.py", line 216, in test_main
    self.assertEqual(self.cookies_util.cookies, {'key1': 'value1', 'key2': 'value2'})
AssertionError: None != {'key1': 'value1', 'key2': 'value2'}

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_get_BMI (ClassEval_40_0.FitnessTrackerTestGetBMI.test_get_BMI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 48, in test_get_BMI
    self.assertEqual(fitnessTracker.get_BMI(), 21.604938271604937)
AssertionError: None != 21.604938271604937

======================================================================
FAIL: test_get_BMI_2 (ClassEval_40_0.FitnessTrackerTestGetBMI.test_get_BMI_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 52, in test_get_BMI_2
    self.assertEqual(fitnessTracker.get_BMI(), 15.432098765432098)
AssertionError: None != 15.432098765432098

======================================================================
FAIL: test_get_BMI_3 (ClassEval_40_0.FitnessTrackerTestGetBMI.test_get_BMI_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 56, in test_get_BMI_3
    self.assertEqual(fitnessTracker.get_BMI(), 17.915089237425637)
AssertionError: None != 17.915089237425637

======================================================================
FAIL: test_get_BMI_4 (ClassEval_40_0.FitnessTrackerTestGetBMI.test_get_BMI_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 60, in test_get_BMI_4
    self.assertEqual(fitnessTracker.get_BMI(), 20.281233098972418)
AssertionError: None != 20.281233098972418

======================================================================
FAIL: test_get_BMI_5 (ClassEval_40_0.FitnessTrackerTestGetBMI.test_get_BMI_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 64, in test_get_BMI_5
    self.assertEqual(fitnessTracker.get_BMI(), 21.971335857220122)
AssertionError: None != 21.971335857220122

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_condition_judge (ClassEval_40_0.FitnessTrackerTestConditionJudge.test_condition_judge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 70, in test_condition_judge
    self.assertEqual(fitnessTracker.condition_judge(), -1)
AssertionError: None != -1

======================================================================
FAIL: test_condition_judge_2 (ClassEval_40_0.FitnessTrackerTestConditionJudge.test_condition_judge_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 74, in test_condition_judge_2
    self.assertEqual(fitnessTracker.condition_judge(), 1)
AssertionError: None != 1

======================================================================
FAIL: test_condition_judge_3 (ClassEval_40_0.FitnessTrackerTestConditionJudge.test_condition_judge_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 78, in test_condition_judge_3
    self.assertEqual(fitnessTracker.condition_judge(), -1)
AssertionError: None != -1

======================================================================
FAIL: test_condition_judge_4 (ClassEval_40_0.FitnessTrackerTestConditionJudge.test_condition_judge_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 82, in test_condition_judge_4
    self.assertEqual(fitnessTracker.condition_judge(), 0)
AssertionError: None != 0

======================================================================
FAIL: test_condition_judge_5 (ClassEval_40_0.FitnessTrackerTestConditionJudge.test_condition_judge_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 86, in test_condition_judge_5
    self.assertEqual(fitnessTracker.condition_judge(), 1)
AssertionError: None != 1

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_calculate_calorie_intake (ClassEval_40_0.FitnessTrackerTestCaculateCalorieIntake.test_calculate_calorie_intake)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 92, in test_calculate_calorie_intake
    self.assertEqual(fitnessTracker.calculate_calorie_intake(), 630.3499999999999)
AssertionError: None != 630.3499999999999

======================================================================
FAIL: test_calculate_calorie_intake_2 (ClassEval_40_0.FitnessTrackerTestCaculateCalorieIntake.test_calculate_calorie_intake_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 96, in test_calculate_calorie_intake_2
    self.assertEqual(fitnessTracker.calculate_calorie_intake(), 647.6999999999999)
AssertionError: None != 647.6999999999999

======================================================================
FAIL: test_calculate_calorie_intake_3 (ClassEval_40_0.FitnessTrackerTestCaculateCalorieIntake.test_calculate_calorie_intake_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 100, in test_calculate_calorie_intake_3
    self.assertEqual(fitnessTracker.calculate_calorie_intake(), 697.2)
AssertionError: None != 697.2

======================================================================
FAIL: test_calculate_calorie_intake_4 (ClassEval_40_0.FitnessTrackerTestCaculateCalorieIntake.test_calculate_calorie_intake_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 104, in test_calculate_calorie_intake_4
    self.assertEqual(fitnessTracker.calculate_calorie_intake(), 708.05)
AssertionError: None != 708.05

======================================================================
FAIL: test_calculate_calorie_intake_5 (ClassEval_40_0.FitnessTrackerTestCaculateCalorieIntake.test_calculate_calorie_intake_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 108, in test_calculate_calorie_intake_5
    self.assertEqual(fitnessTracker.calculate_calorie_intake(), 786.9)
AssertionError: None != 786.9

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F
======================================================================
FAIL: test_main (ClassEval_40_0.FitnessTrackerTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_40_0.py", line 114, in test_main
    self.assertEqual(fitnessTracker.get_BMI(), 21.604938271604937)
AssertionError: None != 21.604938271604937

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
F.FFF.
======================================================================
FAIL: test_book_room_1 (ClassEval_42_0.HotelTestBookRoom.test_book_room_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 126, in test_book_room_1
    self.assertEqual(result, 'Success!')
AssertionError: None != 'Success!'

======================================================================
FAIL: test_book_room_3 (ClassEval_42_0.HotelTestBookRoom.test_book_room_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 139, in test_book_room_3
    self.assertEqual(result, 1)
AssertionError: None != 1

======================================================================
FAIL: test_book_room_4 (ClassEval_42_0.HotelTestBookRoom.test_book_room_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 146, in test_book_room_4
    self.assertEqual(result, 'Success!')
AssertionError: None != 'Success!'

======================================================================
FAIL: test_book_room_5 (ClassEval_42_0.HotelTestBookRoom.test_book_room_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 153, in test_book_room_5
    self.assertEqual(result, 1)
AssertionError: None != 1

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=4)
F..F..
======================================================================
FAIL: test_check_in_1 (ClassEval_42_0.HotelTestCheckIn.test_check_in_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 170, in test_check_in_1
    self.assertEqual(self.hotel.booked_rooms, {'single': {'guest 1': 1}, 'double': {'guest 2': 1}})
AssertionError: {'single': {'guest 1': 2}, 'double': {'guest 2': 1}} != {'single': {'guest 1': 1}, 'double': {'guest 2': 1}}
- {'double': {'guest 2': 1}, 'single': {'guest 1': 2}}
?                                                  ^

+ {'double': {'guest 2': 1}, 'single': {'guest 1': 1}}
?                                                  ^


======================================================================
FAIL: test_check_in_4 (ClassEval_42_0.HotelTestCheckIn.test_check_in_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 182, in test_check_in_4
    self.assertEqual(self.hotel.booked_rooms, {'double': {}, 'single': {'guest 1': 2}})
AssertionError: {'single': {'guest 1': 2}, 'double': {'guest 2': 1}} != {'double': {}, 'single': {'guest 1': 2}}
- {'double': {'guest 2': 1}, 'single': {'guest 1': 2}}
?             ------------

+ {'double': {}, 'single': {'guest 1': 2}}

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=2)
FFFFF
======================================================================
FAIL: test_check_out_1 (ClassEval_42_0.HotelTestCheckOut.test_check_out_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 200, in test_check_out_1
    self.assertEqual(self.hotel.available_rooms, {'single': 4, 'double': 2})
AssertionError: {'single': 3, 'double': 2} != {'single': 4, 'double': 2}
- {'double': 2, 'single': 3}
?                         ^

+ {'double': 2, 'single': 4}
?                         ^


======================================================================
FAIL: test_check_out_2 (ClassEval_42_0.HotelTestCheckOut.test_check_out_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 205, in test_check_out_2
    self.assertEqual(self.hotel.available_rooms, {'single': 6, 'double': 2})
AssertionError: {'single': 3, 'double': 2} != {'single': 6, 'double': 2}
- {'double': 2, 'single': 3}
?                         ^

+ {'double': 2, 'single': 6}
?                         ^


======================================================================
FAIL: test_check_out_3 (ClassEval_42_0.HotelTestCheckOut.test_check_out_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 210, in test_check_out_3
    self.assertEqual(self.hotel.available_rooms, {'single': 3, 'double': 2, 'triple': 2})
AssertionError: {'single': 3, 'double': 2} != {'single': 3, 'double': 2, 'triple': 2}
- {'double': 2, 'single': 3}
+ {'double': 2, 'single': 3, 'triple': 2}
?                          +++++++++++++


======================================================================
FAIL: test_check_out_4 (ClassEval_42_0.HotelTestCheckOut.test_check_out_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 215, in test_check_out_4
    self.assertEqual(self.hotel.available_rooms, {'single': 3, 'double': 3})
AssertionError: {'single': 3, 'double': 2} != {'single': 3, 'double': 3}
- {'double': 2, 'single': 3}
?            ^

+ {'double': 3, 'single': 3}
?            ^


======================================================================
FAIL: test_check_out_5 (ClassEval_42_0.HotelTestCheckOut.test_check_out_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 220, in test_check_out_5
    self.assertEqual(self.hotel.available_rooms, {'single': 3, 'double': 4})
AssertionError: {'single': 3, 'double': 2} != {'single': 3, 'double': 4}
- {'double': 2, 'single': 3}
?            ^

+ {'double': 4, 'single': 3}
?            ^


----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_get_available_rooms (ClassEval_42_0.HotelTestAvailableRooms.test_get_available_rooms)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 230, in test_get_available_rooms
    self.assertEqual(result, 3)
AssertionError: None != 3

======================================================================
FAIL: test_get_available_rooms_2 (ClassEval_42_0.HotelTestAvailableRooms.test_get_available_rooms_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 235, in test_get_available_rooms_2
    self.assertEqual(result, 1)
AssertionError: None != 1

======================================================================
FAIL: test_get_available_rooms_3 (ClassEval_42_0.HotelTestAvailableRooms.test_get_available_rooms_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 240, in test_get_available_rooms_3
    self.assertEqual(result, 0)
AssertionError: None != 0

======================================================================
FAIL: test_get_available_rooms_4 (ClassEval_42_0.HotelTestAvailableRooms.test_get_available_rooms_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 245, in test_get_available_rooms_4
    self.assertEqual(result, 2)
AssertionError: None != 2

======================================================================
FAIL: test_get_available_rooms_5 (ClassEval_42_0.HotelTestAvailableRooms.test_get_available_rooms_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 250, in test_get_available_rooms_5
    self.assertEqual(result, 2)
AssertionError: None != 2

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
F
======================================================================
FAIL: test_main (ClassEval_42_0.HotelTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_42_0.py", line 259, in test_main
    self.assertEqual(result, 'Success!')
AssertionError: None != 'Success!'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_post_job (ClassEval_49_0.JobMarketplaceTestPostJob.test_post_job)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 125, in test_post_job
    self.assertEqual(jobMarketplace.job_listings, [{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['requirement1', 'requirement2']}])
AssertionError: Lists differ: [] != [{'job_title': 'Software Engineer', 'compa[65 chars]2']}]

Second list contains 1 additional elements.
First extra element 0:
{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['requirement1', 'requirement2']}

- []
+ [{'company': 'ABC Company',
+   'job_title': 'Software Engineer',
+   'requirements': ['requirement1', 'requirement2']}]

======================================================================
FAIL: test_post_job_2 (ClassEval_49_0.JobMarketplaceTestPostJob.test_post_job_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 130, in test_post_job_2
    self.assertEqual(jobMarketplace.job_listings, [{'job_title': 'Mechanical Engineer', 'company': 'XYZ Company', 'requirements': ['requirement3', 'requirement4']}])
AssertionError: Lists differ: [] != [{'job_title': 'Mechanical Engineer', 'com[67 chars]4']}]

Second list contains 1 additional elements.
First extra element 0:
{'job_title': 'Mechanical Engineer', 'company': 'XYZ Company', 'requirements': ['requirement3', 'requirement4']}

- []
+ [{'company': 'XYZ Company',
+   'job_title': 'Mechanical Engineer',
+   'requirements': ['requirement3', 'requirement4']}]

======================================================================
FAIL: test_post_job_3 (ClassEval_49_0.JobMarketplaceTestPostJob.test_post_job_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 136, in test_post_job_3
    self.assertEqual(jobMarketplace.job_listings, [{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['requirement1', 'requirement2']}, {'job_title': 'Mechanical Engineer', 'company': 'XYZ Company', 'requirements': ['requirement3', 'requirement4']}])
AssertionError: Lists differ: [] != [{'job_title': 'Software Engineer', 'compa[179 chars]4']}]

Second list contains 2 additional elements.
First extra element 0:
{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['requirement1', 'requirement2']}

- []
+ [{'company': 'ABC Company',
+   'job_title': 'Software Engineer',
+   'requirements': ['requirement1', 'requirement2']},
+  {'company': 'XYZ Company',
+   'job_title': 'Mechanical Engineer',
+   'requirements': ['requirement3', 'requirement4']}]

======================================================================
FAIL: test_post_job_4 (ClassEval_49_0.JobMarketplaceTestPostJob.test_post_job_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 143, in test_post_job_4
    self.assertEqual(jobMarketplace.job_listings, [{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['requirement1', 'requirement2']}, {'job_title': 'Mechanical Engineer', 'company': 'XYZ Company', 'requirements': ['requirement3', 'requirement4']}, {'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['requirement1', 'requirement2']}])
AssertionError: Lists differ: [] != [{'job_title': 'Software Engineer', 'compa[291 chars]2']}]

Second list contains 3 additional elements.
First extra element 0:
{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['requirement1', 'requirement2']}

- []
+ [{'company': 'ABC Company',
+   'job_title': 'Software Engineer',
+   'requirements': ['requirement1', 'requirement2']},
+  {'company': 'XYZ Company',
+   'job_title': 'Mechanical Engineer',
+   'requirements': ['requirement3', 'requirement4']},
+  {'company': 'ABC Company',
+   'job_title': 'Software Engineer',
+   'requirements': ['requirement1', 'requirement2']}]

======================================================================
FAIL: test_post_job_5 (ClassEval_49_0.JobMarketplaceTestPostJob.test_post_job_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 151, in test_post_job_5
    self.assertEqual(jobMarketplace.job_listings, [{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['requirement1', 'requirement2']}, {'job_title': 'Mechanical Engineer', 'company': 'XYZ Company', 'requirements': ['requirement3', 'requirement4']}, {'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['requirement1', 'requirement2']}, {'job_title': 'Mechanical Engineer', 'company': 'XYZ Company', 'requirements': ['requirement3', 'requirement4']}])
AssertionError: Lists differ: [] != [{'job_title': 'Software Engineer', 'compa[405 chars]4']}]

Second list contains 4 additional elements.
First extra element 0:
{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['requirement1', 'requirement2']}

- []
+ [{'company': 'ABC Company',
+   'job_title': 'Software Engineer',
+   'requirements': ['requirement1', 'requirement2']},
+  {'company': 'XYZ Company',
+   'job_title': 'Mechanical Engineer',
+   'requirements': ['requirement3', 'requirement4']},
+  {'company': 'ABC Company',
+   'job_title': 'Software Engineer',
+   'requirements': ['requirement1', 'requirement2']},
+  {'company': 'XYZ Company',
+   'job_title': 'Mechanical Engineer',
+   'requirements': ['requirement3', 'requirement4']}]

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_remove_job (ClassEval_49_0.JobMarketplaceTestRemoveJob.test_remove_job)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 158, in test_remove_job
    self.assertEqual(jobMarketplace.job_listings, [])
AssertionError: Lists differ: [{'job_title': 'Software Engineer', 'compa[65 chars]2']}] != []

First list contains 1 additional elements.
First extra element 0:
{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['requirement1', 'requirement2']}

+ []
- [{'company': 'ABC Company',
-   'job_title': 'Software Engineer',
-   'requirements': ['requirement1', 'requirement2']}]

======================================================================
FAIL: test_remove_job_2 (ClassEval_49_0.JobMarketplaceTestRemoveJob.test_remove_job_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 164, in test_remove_job_2
    self.assertEqual(jobMarketplace.job_listings, [{'job_title': 'Mechanical Engineer', 'company': 'XYZ Company', 'requirements': ['requirement3', 'requirement4']}])
AssertionError: Lists differ: [{'job_title': 'Software Engineer', 'company': 'ABC Compa[164 chars]4']}] != [{'job_title': 'Mechanical Engineer', 'company': 'XYZ Com[52 chars]4']}]

First differing element 0:
{'job_title': 'Software Engineer', 'company': 'ABC Compa[49 chars]t2']}
{'job_title': 'Mechanical Engineer', 'company': 'XYZ Com[51 chars]t4']}

First list contains 1 additional elements.
First extra element 1:
{'job_title': 'Mechanical Engineer', 'company': 'XYZ Company', 'requirements': ['requirement3', 'requirement4']}

- [{'company': 'ABC Company',
-   'job_title': 'Software Engineer',
-   'requirements': ['requirement1', 'requirement2']},
-  {'company': 'XYZ Company',
? ^

+ [{'company': 'XYZ Company',
? ^

    'job_title': 'Mechanical Engineer',
    'requirements': ['requirement3', 'requirement4']}]

======================================================================
FAIL: test_remove_job_3 (ClassEval_49_0.JobMarketplaceTestRemoveJob.test_remove_job_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 171, in test_remove_job_3
    self.assertEqual(jobMarketplace.job_listings, [])
AssertionError: Lists differ: [{'job_title': 'Software Engineer', 'compa[179 chars]4']}] != []

First list contains 2 additional elements.
First extra element 0:
{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['requirement1', 'requirement2']}

+ []
- [{'company': 'ABC Company',
-   'job_title': 'Software Engineer',
-   'requirements': ['requirement1', 'requirement2']},
-  {'company': 'XYZ Company',
-   'job_title': 'Mechanical Engineer',
-   'requirements': ['requirement3', 'requirement4']}]

======================================================================
FAIL: test_remove_job_4 (ClassEval_49_0.JobMarketplaceTestRemoveJob.test_remove_job_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 178, in test_remove_job_4
    self.assertEqual(jobMarketplace.job_listings, [{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['requirement1', 'requirement2']}])
AssertionError: Lists differ: [{'jo[101 chars]t2']}, {'job_title': 'Mechanical Engineer', 'c[181 chars]2']}] != [{'jo[101 chars]t2']}]

First list contains 2 additional elements.
First extra element 1:
{'job_title': 'Mechanical Engineer', 'company': 'XYZ Company', 'requirements': ['requirement3', 'requirement4']}

  [{'company': 'ABC Company',
    'job_title': 'Software Engineer',
-   'requirements': ['requirement1', 'requirement2']},
-  {'company': 'XYZ Company',
-   'job_title': 'Mechanical Engineer',
-   'requirements': ['requirement3', 'requirement4']},
-  {'company': 'ABC Company',
-   'job_title': 'Software Engineer',
    'requirements': ['requirement1', 'requirement2']}]

======================================================================
FAIL: test_remove_job_5 (ClassEval_49_0.JobMarketplaceTestRemoveJob.test_remove_job_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 189, in test_remove_job_5
    self.assertEqual(jobMarketplace.job_listings, [{'job_title': 'Mechanical Engineer', 'company': 'XYZ Company', 'requirements': ['requirement3', 'requirement4']}, {'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['requirement1', 'requirement2']}])
AssertionError: Lists differ: [{'job_title': 'Software Engineer', 'company': 'ABC Compa[276 chars]2']}] != [{'job_title': 'Mechanical Engineer', 'company': 'XYZ Com[164 chars]2']}]

First differing element 0:
{'job_title': 'Software Engineer', 'company': 'ABC Compa[49 chars]t2']}
{'job_title': 'Mechanical Engineer', 'company': 'XYZ Com[51 chars]t4']}

First list contains 1 additional elements.
First extra element 2:
{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['requirement1', 'requirement2']}

- [{'company': 'ABC Company',
-   'job_title': 'Software Engineer',
-   'requirements': ['requirement1', 'requirement2']},
-  {'company': 'XYZ Company',
? ^

+ [{'company': 'XYZ Company',
? ^

    'job_title': 'Mechanical Engineer',
    'requirements': ['requirement3', 'requirement4']},
   {'company': 'ABC Company',
    'job_title': 'Software Engineer',
    'requirements': ['requirement1', 'requirement2']}]

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_submit_resume (ClassEval_49_0.JobMarketplaceTestSubmitResume.test_submit_resume)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 195, in test_submit_resume
    self.assertEqual(jobMarketplace.resumes, [{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}])
AssertionError: Lists differ: [] != [{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}]

Second list contains 1 additional elements.
First extra element 0:
{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}

- []
+ [{'experience': 'experience', 'name': 'Tom', 'skills': ['skill1', 'skill2']}]

======================================================================
FAIL: test_submit_resume_2 (ClassEval_49_0.JobMarketplaceTestSubmitResume.test_submit_resume_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 201, in test_submit_resume_2
    self.assertEqual(jobMarketplace.resumes, [{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}, {'name': 'John', 'skills': ['skill3', 'skill4'], 'experience': 'experience'}])
AssertionError: Lists differ: [] != [{'name': 'Tom', 'skills': ['skill1', 'ski[108 chars]ce'}]

Second list contains 2 additional elements.
First extra element 0:
{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}

- []
+ [{'experience': 'experience', 'name': 'Tom', 'skills': ['skill1', 'skill2']},
+  {'experience': 'experience', 'name': 'John', 'skills': ['skill3', 'skill4']}]

======================================================================
FAIL: test_submit_resume_3 (ClassEval_49_0.JobMarketplaceTestSubmitResume.test_submit_resume_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 208, in test_submit_resume_3
    self.assertEqual(jobMarketplace.resumes, [{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}, {'name': 'John', 'skills': ['skill3', 'skill4'], 'experience': 'experience'}, {'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}])
AssertionError: Lists differ: [] != [{'name': 'Tom', 'skills': ['skill1', 'ski[185 chars]ce'}]

Second list contains 3 additional elements.
First extra element 0:
{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}

- []
+ [{'experience': 'experience', 'name': 'Tom', 'skills': ['skill1', 'skill2']},
+  {'experience': 'experience', 'name': 'John', 'skills': ['skill3', 'skill4']},
+  {'experience': 'experience', 'name': 'Tom', 'skills': ['skill1', 'skill2']}]

======================================================================
FAIL: test_submit_resume_4 (ClassEval_49_0.JobMarketplaceTestSubmitResume.test_submit_resume_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 216, in test_submit_resume_4
    self.assertEqual(jobMarketplace.resumes, [{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}, {'name': 'John', 'skills': ['skill3', 'skill4'], 'experience': 'experience'}, {'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}, {'name': 'John', 'skills': ['skill3', 'skill4'], 'experience': 'experience'}])
AssertionError: Lists differ: [] != [{'name': 'Tom', 'skills': ['skill1', 'ski[263 chars]ce'}]

Second list contains 4 additional elements.
First extra element 0:
{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}

- []
+ [{'experience': 'experience', 'name': 'Tom', 'skills': ['skill1', 'skill2']},
+  {'experience': 'experience', 'name': 'John', 'skills': ['skill3', 'skill4']},
+  {'experience': 'experience', 'name': 'Tom', 'skills': ['skill1', 'skill2']},
+  {'experience': 'experience', 'name': 'John', 'skills': ['skill3', 'skill4']}]

======================================================================
FAIL: test_submit_resume_5 (ClassEval_49_0.JobMarketplaceTestSubmitResume.test_submit_resume_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 225, in test_submit_resume_5
    self.assertEqual(jobMarketplace.resumes, [{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}, {'name': 'John', 'skills': ['skill3', 'skill4'], 'experience': 'experience'}, {'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}, {'name': 'John', 'skills': ['skill3', 'skill4'], 'experience': 'experience'}, {'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}])
AssertionError: Lists differ: [] != [{'name': 'Tom', 'skills': ['skill1', 'ski[340 chars]ce'}]

Second list contains 5 additional elements.
First extra element 0:
{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}

- []
+ [{'experience': 'experience', 'name': 'Tom', 'skills': ['skill1', 'skill2']},
+  {'experience': 'experience', 'name': 'John', 'skills': ['skill3', 'skill4']},
+  {'experience': 'experience', 'name': 'Tom', 'skills': ['skill1', 'skill2']},
+  {'experience': 'experience', 'name': 'John', 'skills': ['skill3', 'skill4']},
+  {'experience': 'experience', 'name': 'Tom', 'skills': ['skill1', 'skill2']}]

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_withdraw_resume (ClassEval_49_0.JobMarketplaceTestWithdrawResume.test_withdraw_resume)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 233, in test_withdraw_resume
    self.assertEqual(jobMarketplace.resumes, [])
AssertionError: Lists differ: [{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}] != []

First list contains 1 additional elements.
First extra element 0:
{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}

- [{'experience': 'experience', 'name': 'Tom', 'skills': ['skill1', 'skill2']}]
+ []

======================================================================
FAIL: test_withdraw_resume_2 (ClassEval_49_0.JobMarketplaceTestWithdrawResume.test_withdraw_resume_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 239, in test_withdraw_resume_2
    self.assertEqual(jobMarketplace.resumes, [{'name': 'John', 'skills': ['skill3', 'skill4'], 'experience': 'experience'}])
AssertionError: Lists differ: [{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'ex[98 chars]ce'}] != [{'name': 'John', 'skills': ['skill3', 'skill4'], 'e[21 chars]ce'}]

First differing element 0:
{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}
{'name': 'John', 'skills': ['skill3', 'skill4'], 'experience': 'experience'}

First list contains 1 additional elements.
First extra element 1:
{'name': 'John', 'skills': ['skill3', 'skill4'], 'experience': 'experience'}

- [{'experience': 'experience', 'name': 'Tom', 'skills': ['skill1', 'skill2']},
-  {'experience': 'experience', 'name': 'John', 'skills': ['skill3', 'skill4']}]
? ^

+ [{'experience': 'experience', 'name': 'John', 'skills': ['skill3', 'skill4']}]
? ^


======================================================================
FAIL: test_withdraw_resume_3 (ClassEval_49_0.JobMarketplaceTestWithdrawResume.test_withdraw_resume_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 246, in test_withdraw_resume_3
    self.assertEqual(jobMarketplace.resumes, [])
AssertionError: Lists differ: [{'name': 'Tom', 'skills': ['skill1', 'ski[108 chars]ce'}] != []

First list contains 2 additional elements.
First extra element 0:
{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}

+ []
- [{'experience': 'experience', 'name': 'Tom', 'skills': ['skill1', 'skill2']},
-  {'experience': 'experience', 'name': 'John', 'skills': ['skill3', 'skill4']}]

======================================================================
FAIL: test_withdraw_resume_4 (ClassEval_49_0.JobMarketplaceTestWithdrawResume.test_withdraw_resume_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 253, in test_withdraw_resume_4
    self.assertEqual(jobMarketplace.resumes, [])
AssertionError: Lists differ: [{'name': 'Amy', 'skills': ['skill3', 'ski[108 chars]ce'}] != []

First list contains 2 additional elements.
First extra element 0:
{'name': 'Amy', 'skills': ['skill3', 'skill2'], 'experience': 'experience'}

+ []
- [{'experience': 'experience', 'name': 'Amy', 'skills': ['skill3', 'skill2']},
-  {'experience': 'experience', 'name': 'John', 'skills': ['skill3', 'skill4']}]

======================================================================
FAIL: test_withdraw_resume_5 (ClassEval_49_0.JobMarketplaceTestWithdrawResume.test_withdraw_resume_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 259, in test_withdraw_resume_5
    self.assertEqual(jobMarketplace.resumes, [{'experience': 'experience', 'name': 'John', 'skills': ['skill3', 'skill4']}])
AssertionError: Lists differ: [{'name': 'Amy', 'skills': ['skill1', 'skill[106 chars]ce'}] != [{'experience': 'experience', 'name': 'John'[29 chars]4']}]

First differing element 0:
{'name': 'Amy', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}
{'experience': 'experience', 'name': 'John', 'skills': ['skill3', 'skill4']}

First list contains 1 additional elements.
First extra element 1:
{'name': 'John', 'skills': ['skill3', 'skill4'], 'experience': 'experience'}

- [{'experience': 'experience', 'name': 'Amy', 'skills': ['skill1', 'skill2']},
-  {'experience': 'experience', 'name': 'John', 'skills': ['skill3', 'skill4']}]
? ^

+ [{'experience': 'experience', 'name': 'John', 'skills': ['skill3', 'skill4']}]
? ^


----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_search_jobs (ClassEval_49_0.JobMarketplaceTestSearchJobs.test_search_jobs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 265, in test_search_jobs
    self.assertEqual(jobMarketplace.search_jobs("skill1"), [{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['skill1', 'skill2']}])
AssertionError: None != [{'job_title': 'Software Engineer', 'comp[54 chars]2']}]

======================================================================
FAIL: test_search_jobs_2 (ClassEval_49_0.JobMarketplaceTestSearchJobs.test_search_jobs_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 270, in test_search_jobs_2
    self.assertEqual(jobMarketplace.search_jobs("skill1"), [{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['skill1', 'skill2']}])
AssertionError: None != [{'job_title': 'Software Engineer', 'comp[54 chars]2']}]

======================================================================
FAIL: test_search_jobs_3 (ClassEval_49_0.JobMarketplaceTestSearchJobs.test_search_jobs_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 275, in test_search_jobs_3
    self.assertEqual(jobMarketplace.search_jobs("skill3"), [{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['skill3', 'skill4']}])
AssertionError: None != [{'job_title': 'Software Engineer', 'comp[54 chars]4']}]

======================================================================
FAIL: test_search_jobs_4 (ClassEval_49_0.JobMarketplaceTestSearchJobs.test_search_jobs_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 280, in test_search_jobs_4
    self.assertEqual(jobMarketplace.search_jobs("skill5"), [])
AssertionError: None != []

======================================================================
FAIL: test_search_jobs_5 (ClassEval_49_0.JobMarketplaceTestSearchJobs.test_search_jobs_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 285, in test_search_jobs_5
    self.assertEqual(jobMarketplace.search_jobs("skill6"), [])
AssertionError: None != []

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_get_job_applicants (ClassEval_49_0.JobMarketplaceTestGetJobApplicants.test_get_job_applicants)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 292, in test_get_job_applicants
    self.assertEqual(jobMarketplace.get_job_applicants(jobMarketplace.job_listings[0]), [{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}])
AssertionError: None != [{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}]

======================================================================
FAIL: test_get_job_applicants_2 (ClassEval_49_0.JobMarketplaceTestGetJobApplicants.test_get_job_applicants_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 298, in test_get_job_applicants_2
    self.assertEqual(jobMarketplace.get_job_applicants(jobMarketplace.job_listings[0]), [{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}])
AssertionError: None != [{'name': 'Tom', 'skills': ['skill1', 'skill2'], 'experience': 'experience'}]

======================================================================
FAIL: test_get_job_applicants_3 (ClassEval_49_0.JobMarketplaceTestGetJobApplicants.test_get_job_applicants_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 304, in test_get_job_applicants_3
    self.assertEqual(jobMarketplace.get_job_applicants(jobMarketplace.job_listings[0]), [{'name': 'John', 'skills': ['skill3', 'skill4'], 'experience': 'experience'}])
AssertionError: None != [{'name': 'John', 'skills': ['skill3', 'skill4'], 'experience': 'experience'}]

======================================================================
FAIL: test_get_job_applicants_4 (ClassEval_49_0.JobMarketplaceTestGetJobApplicants.test_get_job_applicants_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 310, in test_get_job_applicants_4
    self.assertEqual(jobMarketplace.get_job_applicants(jobMarketplace.job_listings[0]), [])
AssertionError: None != []

======================================================================
FAIL: test_get_job_applicants_5 (ClassEval_49_0.JobMarketplaceTestGetJobApplicants.test_get_job_applicants_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 316, in test_get_job_applicants_5
    self.assertEqual(jobMarketplace.get_job_applicants(jobMarketplace.job_listings[0]), [])
AssertionError: None != []

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
EEEEE
======================================================================
ERROR: test_matches_requirements (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 321, in test_matches_requirements
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill1', 'skill2']), True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'JobMarketplace' object has no attribute 'matches_requirements'

======================================================================
ERROR: test_matches_requirements_2 (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 325, in test_matches_requirements_2
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill3', 'skill4']), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'JobMarketplace' object has no attribute 'matches_requirements'

======================================================================
ERROR: test_matches_requirements_3 (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 329, in test_matches_requirements_3
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill5', 'skill6']), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'JobMarketplace' object has no attribute 'matches_requirements'

======================================================================
ERROR: test_matches_requirements_4 (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 333, in test_matches_requirements_4
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill1', 'skill3']), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'JobMarketplace' object has no attribute 'matches_requirements'

======================================================================
ERROR: test_matches_requirements_5 (ClassEval_49_0.JobMarketplaceTestMatchesRequirements.test_matches_requirements_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 337, in test_matches_requirements_5
    self.assertEqual(jobMarketplace.matches_requirements({"name": "Tom", "skills": ['skill1', 'skill2'], "experience": "experience"}, ['skill1']), False)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'JobMarketplace' object has no attribute 'matches_requirements'

----------------------------------------------------------------------
Ran 5 tests in 0.006s

FAILED (errors=5)
F
======================================================================
FAIL: test_main (ClassEval_49_0.JobMarketplaceTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_49_0.py", line 344, in test_main
    self.assertEqual(jobMarketplace.job_listings, [{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['skill1', 'skill2']}, {'job_title': 'Mechanical Engineer', 'company': 'XYZ Company', 'requirements': ['skill3', 'skill4']}])
AssertionError: Lists differ: [] != [{'job_title': 'Software Engineer', 'compa[155 chars]4']}]

Second list contains 2 additional elements.
First extra element 0:
{'job_title': 'Software Engineer', 'company': 'ABC Company', 'requirements': ['skill1', 'skill2']}

- []
+ [{'company': 'ABC Company',
+   'job_title': 'Software Engineer',
+   'requirements': ['skill1', 'skill2']},
+  {'company': 'XYZ Company',
+   'job_title': 'Mechanical Engineer',
+   'requirements': ['skill3', 'skill4']}]

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_add_song (ClassEval_61_0.MusicPlayerTestAddSong.test_add_song)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 98, in test_add_song
    self.assertEqual(musicPlayer.playlist, ["song1"])
AssertionError: Lists differ: [] != ['song1']

Second list contains 1 additional elements.
First extra element 0:
'song1'

- []
+ ['song1']

======================================================================
FAIL: test_add_song2 (ClassEval_61_0.MusicPlayerTestAddSong.test_add_song2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 104, in test_add_song2
    self.assertEqual(musicPlayer.playlist, ["song1", "song2"])
AssertionError: Lists differ: [] != ['song1', 'song2']

Second list contains 2 additional elements.
First extra element 0:
'song1'

- []
+ ['song1', 'song2']

======================================================================
FAIL: test_add_song3 (ClassEval_61_0.MusicPlayerTestAddSong.test_add_song3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 111, in test_add_song3
    self.assertEqual(musicPlayer.playlist, ["song1", "song2", "song3"])
AssertionError: Lists differ: [] != ['song1', 'song2', 'song3']

Second list contains 3 additional elements.
First extra element 0:
'song1'

- []
+ ['song1', 'song2', 'song3']

======================================================================
FAIL: test_add_song4 (ClassEval_61_0.MusicPlayerTestAddSong.test_add_song4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 119, in test_add_song4
    self.assertEqual(musicPlayer.playlist, ["song1", "song2", "song3", "song4"])
AssertionError: Lists differ: [] != ['song1', 'song2', 'song3', 'song4']

Second list contains 4 additional elements.
First extra element 0:
'song1'

- []
+ ['song1', 'song2', 'song3', 'song4']

======================================================================
FAIL: test_add_song5 (ClassEval_61_0.MusicPlayerTestAddSong.test_add_song5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 128, in test_add_song5
    self.assertEqual(musicPlayer.playlist, ["song1", "song2", "song3", "song4", "song5"])
AssertionError: Lists differ: [] != ['song1', 'song2', 'song3', 'song4', 'song5']

Second list contains 5 additional elements.
First extra element 0:
'song1'

- []
+ ['song1', 'song2', 'song3', 'song4', 'song5']

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=5)
FFFFF.
======================================================================
FAIL: test_remove_song (ClassEval_61_0.MusicPlayerTestRemoveSong.test_remove_song)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 135, in test_remove_song
    self.assertEqual(musicPlayer.playlist, ["song2"])
AssertionError: Lists differ: ['song1', 'song2'] != ['song2']

First differing element 0:
'song1'
'song2'

First list contains 1 additional elements.
First extra element 1:
'song2'

- ['song1', 'song2']
+ ['song2']

======================================================================
FAIL: test_remove_song2 (ClassEval_61_0.MusicPlayerTestRemoveSong.test_remove_song2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 142, in test_remove_song2
    self.assertEqual(musicPlayer.playlist, ["song2", "song3"])
AssertionError: Lists differ: ['song1', 'song2', 'song3'] != ['song2', 'song3']

First differing element 0:
'song1'
'song2'

First list contains 1 additional elements.
First extra element 2:
'song3'

- ['song1', 'song2', 'song3']
?  ---------

+ ['song2', 'song3']

======================================================================
FAIL: test_remove_song3 (ClassEval_61_0.MusicPlayerTestRemoveSong.test_remove_song3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 149, in test_remove_song3
    self.assertEqual(musicPlayer.playlist, ["song2", "song3", "song4"])
AssertionError: Lists differ: ['song1', 'song2', 'song3', 'song4'] != ['song2', 'song3', 'song4']

First differing element 0:
'song1'
'song2'

First list contains 1 additional elements.
First extra element 3:
'song4'

- ['song1', 'song2', 'song3', 'song4']
?  ---------

+ ['song2', 'song3', 'song4']

======================================================================
FAIL: test_remove_song4 (ClassEval_61_0.MusicPlayerTestRemoveSong.test_remove_song4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 155, in test_remove_song4
    self.assertEqual(musicPlayer.playlist, ["song2", "song3", "song4", "song5"])
AssertionError: Lists differ: ['song1', 'song2', 'song3', 'song4', 'song5'] != ['song2', 'song3', 'song4', 'song5']

First differing element 0:
'song1'
'song2'

First list contains 1 additional elements.
First extra element 4:
'song5'

- ['song1', 'song2', 'song3', 'song4', 'song5']
?  ---------

+ ['song2', 'song3', 'song4', 'song5']

======================================================================
FAIL: test_remove_song5 (ClassEval_61_0.MusicPlayerTestRemoveSong.test_remove_song5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 162, in test_remove_song5
    self.assertEqual(musicPlayer.playlist, ["song3", "song4", "song5"])
AssertionError: Lists differ: ['song1', 'song2', 'song3', 'song4', 'song5'] != ['song3', 'song4', 'song5']

First differing element 0:
'song1'
'song3'

First list contains 2 additional elements.
First extra element 3:
'song4'

- ['song1', 'song2', 'song3', 'song4', 'song5']
?  ------------------

+ ['song3', 'song4', 'song5']

----------------------------------------------------------------------
Ran 6 tests in 0.003s

FAILED (failures=5)
F.FFF
======================================================================
FAIL: test_play (ClassEval_61_0.MusicPlayerTestPlay.test_play)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 176, in test_play
    self.assertEqual(musicPlayer.play(), "song1")
AssertionError: None != 'song1'

======================================================================
FAIL: test_play_3 (ClassEval_61_0.MusicPlayerTestPlay.test_play_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 187, in test_play_3
    self.assertEqual(musicPlayer.play(),False)
AssertionError: None != False

======================================================================
FAIL: test_play_4 (ClassEval_61_0.MusicPlayerTestPlay.test_play_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 193, in test_play_4
    self.assertEqual(musicPlayer.play(), "song1")
AssertionError: None != 'song1'

======================================================================
FAIL: test_play_5 (ClassEval_61_0.MusicPlayerTestPlay.test_play_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 199, in test_play_5
    self.assertEqual(musicPlayer.play(), "song1")
AssertionError: None != 'song1'

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=4)
FFFFF
======================================================================
FAIL: test_stop (ClassEval_61_0.MusicPlayerTestStop.test_stop)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 206, in test_stop
    self.assertEqual(musicPlayer.stop(), True)
AssertionError: None != True

======================================================================
FAIL: test_stop_2 (ClassEval_61_0.MusicPlayerTestStop.test_stop_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 212, in test_stop_2
    self.assertEqual(musicPlayer.stop(), True)
AssertionError: None != True

======================================================================
FAIL: test_stop_3 (ClassEval_61_0.MusicPlayerTestStop.test_stop_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 217, in test_stop_3
    self.assertEqual(musicPlayer.stop(), False)
AssertionError: None != False

======================================================================
FAIL: test_stop_4 (ClassEval_61_0.MusicPlayerTestStop.test_stop_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 223, in test_stop_4
    self.assertEqual(musicPlayer.stop(), True)
AssertionError: None != True

======================================================================
FAIL: test_stop_5 (ClassEval_61_0.MusicPlayerTestStop.test_stop_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 229, in test_stop_5
    self.assertEqual(musicPlayer.stop(), True)
AssertionError: None != True

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_switch_song (ClassEval_61_0.MusicPlayerTestSwitchSong.test_switch_song)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 236, in test_switch_song
    self.assertEqual(musicPlayer.switch_song(), True)
AssertionError: None != True

======================================================================
FAIL: test_switch_song2 (ClassEval_61_0.MusicPlayerTestSwitchSong.test_switch_song2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 242, in test_switch_song2
    self.assertEqual(musicPlayer.switch_song(), False)
AssertionError: None != False

======================================================================
FAIL: test_switch_song3 (ClassEval_61_0.MusicPlayerTestSwitchSong.test_switch_song3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 248, in test_switch_song3
    self.assertEqual(musicPlayer.switch_song(), False)
AssertionError: None != False

======================================================================
FAIL: test_switch_song4 (ClassEval_61_0.MusicPlayerTestSwitchSong.test_switch_song4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 253, in test_switch_song4
    self.assertEqual(musicPlayer.switch_song(), False)
AssertionError: None != False

======================================================================
FAIL: test_switch_song5 (ClassEval_61_0.MusicPlayerTestSwitchSong.test_switch_song5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 258, in test_switch_song5
    self.assertEqual(musicPlayer.switch_song(), False)
AssertionError: None != False

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_previous_song (ClassEval_61_0.MusicPlayerTestPreviousSong.test_previous_song)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 265, in test_previous_song
    self.assertEqual(musicPlayer.previous_song(), True)
AssertionError: None != True

======================================================================
FAIL: test_previous_song2 (ClassEval_61_0.MusicPlayerTestPreviousSong.test_previous_song2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 271, in test_previous_song2
    self.assertEqual(musicPlayer.previous_song(), False)
AssertionError: None != False

======================================================================
FAIL: test_previous_song3 (ClassEval_61_0.MusicPlayerTestPreviousSong.test_previous_song3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 277, in test_previous_song3
    self.assertEqual(musicPlayer.previous_song(), True)
AssertionError: None != True

======================================================================
FAIL: test_previous_song4 (ClassEval_61_0.MusicPlayerTestPreviousSong.test_previous_song4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 282, in test_previous_song4
    self.assertEqual(musicPlayer.previous_song(), False)
AssertionError: None != False

======================================================================
FAIL: test_previous_song5 (ClassEval_61_0.MusicPlayerTestPreviousSong.test_previous_song5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 287, in test_previous_song5
    self.assertEqual(musicPlayer.previous_song(), False)
AssertionError: None != False

----------------------------------------------------------------------
Ran 5 tests in 0.004s

FAILED (failures=5)
.FFFF
======================================================================
FAIL: test_set_volume2 (ClassEval_61_0.MusicPlayerTestSetVolume.test_set_volume2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 298, in test_set_volume2
    self.assertEqual(musicPlayer.volume, 100)
AssertionError: 50 != 100

======================================================================
FAIL: test_set_volume3 (ClassEval_61_0.MusicPlayerTestSetVolume.test_set_volume3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 303, in test_set_volume3
    self.assertEqual(musicPlayer.volume, 0)
AssertionError: 50 != 0

======================================================================
FAIL: test_set_volume4 (ClassEval_61_0.MusicPlayerTestSetVolume.test_set_volume4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 307, in test_set_volume4
    self.assertEqual(musicPlayer.set_volume(101), False)
AssertionError: None != False

======================================================================
FAIL: test_set_volume5 (ClassEval_61_0.MusicPlayerTestSetVolume.test_set_volume5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 312, in test_set_volume5
    self.assertEqual(musicPlayer.set_volume(-1), False)
AssertionError: None != False

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
FFFFF
======================================================================
FAIL: test_shuffle (ClassEval_61_0.MusicPlayerTestShuffle.test_shuffle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 319, in test_shuffle
    self.assertEqual(musicPlayer.shuffle(), True)
AssertionError: None != True

======================================================================
FAIL: test_shuffle_2 (ClassEval_61_0.MusicPlayerTestShuffle.test_shuffle_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 325, in test_shuffle_2
    self.assertEqual(musicPlayer.shuffle(), False)
AssertionError: None != False

======================================================================
FAIL: test_shuffle_3 (ClassEval_61_0.MusicPlayerTestShuffle.test_shuffle_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 331, in test_shuffle_3
    self.assertEqual(musicPlayer.shuffle(), True)
AssertionError: None != True

======================================================================
FAIL: test_shuffle_4 (ClassEval_61_0.MusicPlayerTestShuffle.test_shuffle_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 337, in test_shuffle_4
    self.assertEqual(musicPlayer.shuffle(), True)
AssertionError: None != True

======================================================================
FAIL: test_shuffle_5 (ClassEval_61_0.MusicPlayerTestShuffle.test_shuffle_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 343, in test_shuffle_5
    self.assertEqual(musicPlayer.shuffle(), True)
AssertionError: None != True

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F
======================================================================
FAIL: test_main (ClassEval_61_0.MusicPlayerTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_61_0.py", line 350, in test_main
    self.assertEqual(musicPlayer.play(), "song1")
AssertionError: None != 'song1'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
F.FFFF
======================================================================
FAIL: test_add_dish_1 (ClassEval_67_0.OrderTestAddDish.test_add_dish_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 82, in test_add_dish_1
    self.assertTrue(result)
AssertionError: None is not true

======================================================================
FAIL: test_add_dish_3 (ClassEval_67_0.OrderTestAddDish.test_add_dish_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 112, in test_add_dish_3
    self.assertTrue(result)
AssertionError: None is not true

======================================================================
FAIL: test_add_dish_4 (ClassEval_67_0.OrderTestAddDish.test_add_dish_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 127, in test_add_dish_4
    self.assertTrue(result)
AssertionError: None is not true

======================================================================
FAIL: test_add_dish_5 (ClassEval_67_0.OrderTestAddDish.test_add_dish_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 142, in test_add_dish_5
    self.assertTrue(result)
AssertionError: None is not true

======================================================================
FAIL: test_add_dish_6 (ClassEval_67_0.OrderTestAddDish.test_add_dish_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 158, in test_add_dish_6
    self.assertTrue(result)
AssertionError: None is not true

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_calculate_total_1 (ClassEval_67_0.OrderTestCalculateTotal.test_calculate_total_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 173, in test_calculate_total_1
    self.assertEqual(50, result)
AssertionError: 50 != None

======================================================================
FAIL: test_calculate_total_2 (ClassEval_67_0.OrderTestCalculateTotal.test_calculate_total_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 179, in test_calculate_total_2
    self.assertEqual(48, result)
AssertionError: 48 != None

======================================================================
FAIL: test_calculate_total_3 (ClassEval_67_0.OrderTestCalculateTotal.test_calculate_total_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 185, in test_calculate_total_3
    self.assertEqual(25, result)
AssertionError: 25 != None

======================================================================
FAIL: test_calculate_total_4 (ClassEval_67_0.OrderTestCalculateTotal.test_calculate_total_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 191, in test_calculate_total_4
    self.assertEqual(75, result)
AssertionError: 75 != None

======================================================================
FAIL: test_calculate_total_5 (ClassEval_67_0.OrderTestCalculateTotal.test_calculate_total_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 197, in test_calculate_total_5
    self.assertEqual(100, result)
AssertionError: 100 != None

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
F.FFF
======================================================================
FAIL: test_checkout_1 (ClassEval_67_0.OrderTestCheckout.test_checkout_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 213, in test_checkout_1
    self.assertEqual(50, result)
AssertionError: 50 != None

======================================================================
FAIL: test_checkout_3 (ClassEval_67_0.OrderTestCheckout.test_checkout_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 235, in test_checkout_3
    self.assertEqual(25, result)
AssertionError: 25 != None

======================================================================
FAIL: test_checkout_4 (ClassEval_67_0.OrderTestCheckout.test_checkout_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 251, in test_checkout_4
    self.assertEqual(75, result)
AssertionError: 75 != None

======================================================================
FAIL: test_checkout_5 (ClassEval_67_0.OrderTestCheckout.test_checkout_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 267, in test_checkout_5
    self.assertEqual(125, result)
AssertionError: 125 != None

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=4)
F
======================================================================
FAIL: test_order (ClassEval_67_0.OrderTest.test_order)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_67_0.py", line 293, in test_order
    self.assertEqual(50, result)
AssertionError: 50 != None

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_get_page_1 (ClassEval_68_0.PageUtilTestGetPage.test_get_page_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 69, in test_get_page_1
    self.assertEqual(actual_page, expected_page)
AssertionError: None != [1, 2, 3]

======================================================================
FAIL: test_get_page_2 (ClassEval_68_0.PageUtilTestGetPage.test_get_page_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 75, in test_get_page_2
    self.assertEqual(actual_page, expected_page)
AssertionError: None != [4, 5, 6]

======================================================================
FAIL: test_get_page_3 (ClassEval_68_0.PageUtilTestGetPage.test_get_page_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 81, in test_get_page_3
    self.assertEqual(actual_page, expected_page)
AssertionError: None != [7, 8, 9]

======================================================================
FAIL: test_get_page_4 (ClassEval_68_0.PageUtilTestGetPage.test_get_page_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 87, in test_get_page_4
    self.assertEqual(actual_page, expected_page)
AssertionError: None != [10]

======================================================================
FAIL: test_get_page_5 (ClassEval_68_0.PageUtilTestGetPage.test_get_page_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 93, in test_get_page_5
    self.assertEqual(actual_page, empty_page)
AssertionError: None != []

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_get_page_info_1 (ClassEval_68_0.PageUtilTestGetPageInfo.test_get_page_info_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 114, in test_get_page_info_1
    self.assertEqual(actual_info, expected_info)
AssertionError: None != {'current_page': 2, 'per_page': 3, 'total[84 chars], 6]}

======================================================================
FAIL: test_get_page_info_2 (ClassEval_68_0.PageUtilTestGetPageInfo.test_get_page_info_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 128, in test_get_page_info_2
    self.assertEqual(actual_info, expected_info)
AssertionError: None != {'current_page': 1, 'per_page': 3, 'total[85 chars], 3]}

======================================================================
FAIL: test_get_page_info_3 (ClassEval_68_0.PageUtilTestGetPageInfo.test_get_page_info_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 142, in test_get_page_info_3
    self.assertEqual(actual_info, expected_info)
AssertionError: None != {'current_page': 3, 'per_page': 3, 'total[84 chars], 9]}

======================================================================
FAIL: test_get_page_info_4 (ClassEval_68_0.PageUtilTestGetPageInfo.test_get_page_info_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 156, in test_get_page_info_4
    self.assertEqual(actual_info, expected_info)
AssertionError: None != {'current_page': 4, 'per_page': 3, 'total[80 chars][10]}

======================================================================
FAIL: test_get_page_info_5 (ClassEval_68_0.PageUtilTestGetPageInfo.test_get_page_info_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 162, in test_get_page_info_5
    self.assertEqual(actual_info, empty_info)
AssertionError: None != {}

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_search_1 (ClassEval_68_0.PageUtilTestSearch.test_search_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 180, in test_search_1
    self.assertEqual(actual_results, expected_results)
AssertionError: None != {'keyword': '1', 'total_results': 2, 'total_pages': 1, 'results': [1, 10]}

======================================================================
FAIL: test_search_2 (ClassEval_68_0.PageUtilTestSearch.test_search_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 191, in test_search_2
    self.assertEqual(actual_results, expected_results)
AssertionError: None != {'keyword': '2', 'total_results': 1, 'total_pages': 1, 'results': [2]}

======================================================================
FAIL: test_search_3 (ClassEval_68_0.PageUtilTestSearch.test_search_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 202, in test_search_3
    self.assertEqual(actual_results, expected_results)
AssertionError: None != {'keyword': '3', 'total_results': 1, 'total_pages': 1, 'results': [3]}

======================================================================
FAIL: test_search_4 (ClassEval_68_0.PageUtilTestSearch.test_search_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 213, in test_search_4
    self.assertEqual(actual_results, expected_results)
AssertionError: None != {'keyword': '4', 'total_results': 1, 'total_pages': 1, 'results': [4]}

======================================================================
FAIL: test_search_5 (ClassEval_68_0.PageUtilTestSearch.test_search_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 224, in test_search_5
    self.assertEqual(actual_results, expected_results)
AssertionError: None != {'keyword': '11', 'total_results': 0, 'total_pages': 0, 'results': []}

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
F
======================================================================
FAIL: test_pageutil (ClassEval_68_0.PageUtilTest.test_pageutil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_68_0.py", line 237, in test_pageutil
    self.assertEqual(actual_page, expected_page)
AssertionError: None != [1, 2, 3]

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
FFFFFF
======================================================================
FAIL: test_add_item_1 (ClassEval_75_0.ShoppingCartTestAddItem.test_add_item_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 71, in test_add_item_1
    self.assertEqual(shoppingcart.items, {"apple": {"price": 1, "quantity": 5}})
AssertionError: {} != {'apple': {'price': 1, 'quantity': 5}}
- {}
+ {'apple': {'price': 1, 'quantity': 5}}

======================================================================
FAIL: test_add_item_2 (ClassEval_75_0.ShoppingCartTestAddItem.test_add_item_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 76, in test_add_item_2
    self.assertEqual(shoppingcart.items, {"apple": {"price": 1, "quantity": 1}})
AssertionError: {} != {'apple': {'price': 1, 'quantity': 1}}
- {}
+ {'apple': {'price': 1, 'quantity': 1}}

======================================================================
FAIL: test_add_item_3 (ClassEval_75_0.ShoppingCartTestAddItem.test_add_item_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 81, in test_add_item_3
    self.assertEqual(shoppingcart.items, {"aaa": {"price": 1, "quantity": 1}})
AssertionError: {} != {'aaa': {'price': 1, 'quantity': 1}}
- {}
+ {'aaa': {'price': 1, 'quantity': 1}}

======================================================================
FAIL: test_add_item_4 (ClassEval_75_0.ShoppingCartTestAddItem.test_add_item_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 86, in test_add_item_4
    self.assertEqual(shoppingcart.items, {"bbb": {"price": 1, "quantity": 1}})
AssertionError: {} != {'bbb': {'price': 1, 'quantity': 1}}
- {}
+ {'bbb': {'price': 1, 'quantity': 1}}

======================================================================
FAIL: test_add_item_5 (ClassEval_75_0.ShoppingCartTestAddItem.test_add_item_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 91, in test_add_item_5
    self.assertEqual(shoppingcart.items, {"ccc": {"price": 1, "quantity": 1}})
AssertionError: {} != {'ccc': {'price': 1, 'quantity': 1}}
- {}
+ {'ccc': {'price': 1, 'quantity': 1}}

======================================================================
FAIL: test_add_item_6 (ClassEval_75_0.ShoppingCartTestAddItem.test_add_item_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 97, in test_add_item_6
    self.assertEqual(shoppingcart.items, {"apple": {"price": 1, "quantity": 5}})
AssertionError: {} != {'apple': {'price': 1, 'quantity': 5}}
- {}
+ {'apple': {'price': 1, 'quantity': 5}}

----------------------------------------------------------------------
Ran 6 tests in 0.004s

FAILED (failures=6)
FFFFFF
======================================================================
FAIL: test_remove_item_1 (ClassEval_75_0.ShoppingCartTestRemoveItem.test_remove_item_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 105, in test_remove_item_1
    self.assertEqual(shoppingcart.items, {"apple": {"price": 1, "quantity": 2}})
AssertionError: {} != {'apple': {'price': 1, 'quantity': 2}}
- {}
+ {'apple': {'price': 1, 'quantity': 2}}

======================================================================
FAIL: test_remove_item_2 (ClassEval_75_0.ShoppingCartTestRemoveItem.test_remove_item_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 111, in test_remove_item_2
    self.assertEqual(shoppingcart.items, {"apple": {"price": 1, "quantity": 4}})
AssertionError: {} != {'apple': {'price': 1, 'quantity': 4}}
- {}
+ {'apple': {'price': 1, 'quantity': 4}}

======================================================================
FAIL: test_remove_item_3 (ClassEval_75_0.ShoppingCartTestRemoveItem.test_remove_item_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 117, in test_remove_item_3
    self.assertEqual(shoppingcart.items, {"apple": {"price": 1, "quantity": 4}})
AssertionError: {} != {'apple': {'price': 1, 'quantity': 4}}
- {}
+ {'apple': {'price': 1, 'quantity': 4}}

======================================================================
FAIL: test_remove_item_4 (ClassEval_75_0.ShoppingCartTestRemoveItem.test_remove_item_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 123, in test_remove_item_4
    self.assertEqual(shoppingcart.items, {"apple": {"price": 1, "quantity": 3}})
AssertionError: {} != {'apple': {'price': 1, 'quantity': 3}}
- {}
+ {'apple': {'price': 1, 'quantity': 3}}

======================================================================
FAIL: test_remove_item_5 (ClassEval_75_0.ShoppingCartTestRemoveItem.test_remove_item_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 129, in test_remove_item_5
    self.assertEqual(shoppingcart.items, {"apple": {"price": 1, "quantity": 1}})
AssertionError: {} != {'apple': {'price': 1, 'quantity': 1}}
- {}
+ {'apple': {'price': 1, 'quantity': 1}}

======================================================================
FAIL: test_remove_item_6 (ClassEval_75_0.ShoppingCartTestRemoveItem.test_remove_item_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 135, in test_remove_item_6
    self.assertEqual(shoppingcart.items, {"apple": {"price": 1, "quantity": 5}})
AssertionError: {} != {'apple': {'price': 1, 'quantity': 5}}
- {}
+ {'apple': {'price': 1, 'quantity': 5}}

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=6)
FFFFF
======================================================================
FAIL: test_view_items_1 (ClassEval_75_0.ShoppingCartTestViewItems.test_view_items_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 142, in test_view_items_1
    self.assertEqual(shoppingcart.view_items(), {"apple": {"price": 1, "quantity": 5}})
AssertionError: None != {'apple': {'price': 1, 'quantity': 5}}

======================================================================
FAIL: test_view_items_2 (ClassEval_75_0.ShoppingCartTestViewItems.test_view_items_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 147, in test_view_items_2
    self.assertEqual(shoppingcart.view_items(), {"apple": {"price": 1, "quantity": 4}})
AssertionError: None != {'apple': {'price': 1, 'quantity': 4}}

======================================================================
FAIL: test_view_items_3 (ClassEval_75_0.ShoppingCartTestViewItems.test_view_items_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 152, in test_view_items_3
    self.assertEqual(shoppingcart.view_items(), {"apple": {"price": 1, "quantity": 3}})
AssertionError: None != {'apple': {'price': 1, 'quantity': 3}}

======================================================================
FAIL: test_view_items_4 (ClassEval_75_0.ShoppingCartTestViewItems.test_view_items_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 157, in test_view_items_4
    self.assertEqual(shoppingcart.view_items(), {"apple": {"price": 1, "quantity": 2}})
AssertionError: None != {'apple': {'price': 1, 'quantity': 2}}

======================================================================
FAIL: test_view_items_5 (ClassEval_75_0.ShoppingCartTestViewItems.test_view_items_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 162, in test_view_items_5
    self.assertEqual(shoppingcart.view_items(), {"apple": {"price": 1, "quantity": 1}})
AssertionError: None != {'apple': {'price': 1, 'quantity': 1}}

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_total_price_1 (ClassEval_75_0.ShoppingCartTestTotalPrice.test_total_price_1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 170, in test_total_price_1
    self.assertEqual(shoppingcart.total_price(), 11.0)
AssertionError: None != 11.0

======================================================================
FAIL: test_total_price_2 (ClassEval_75_0.ShoppingCartTestTotalPrice.test_total_price_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 177, in test_total_price_2
    self.assertEqual(shoppingcart.total_price(), 8.0)
AssertionError: None != 8.0

======================================================================
FAIL: test_total_price_3 (ClassEval_75_0.ShoppingCartTestTotalPrice.test_total_price_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 183, in test_total_price_3
    self.assertEqual(shoppingcart.total_price(), 3.0)
AssertionError: None != 3.0

======================================================================
FAIL: test_total_price_4 (ClassEval_75_0.ShoppingCartTestTotalPrice.test_total_price_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 189, in test_total_price_4
    self.assertEqual(shoppingcart.total_price(), 4.0)
AssertionError: None != 4.0

======================================================================
FAIL: test_total_price_5 (ClassEval_75_0.ShoppingCartTestTotalPrice.test_total_price_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 195, in test_total_price_5
    self.assertEqual(shoppingcart.total_price(), 5.0)
AssertionError: None != 5.0

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
F
======================================================================
FAIL: test_shoppingcart (ClassEval_75_0.ShoppingCartTest.test_shoppingcart)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_75_0.py", line 202, in test_shoppingcart
    self.assertEqual(shoppingcart.items, {"apple": {"price": 1, "quantity": 5}})
AssertionError: {} != {'apple': {'price': 1, 'quantity': 5}}
- {}
+ {'apple': {'price': 1, 'quantity': 5}}

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
FFFFF
======================================================================
FAIL: test_add_item (ClassEval_94_0.VendingMachineTestAddItem.test_add_item)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 103, in test_add_item
    self.assertEqual(vendingMachine.inventory, {'Coke': {'price': 1.25, 'quantity': 10}})
AssertionError: {} != {'Coke': {'price': 1.25, 'quantity': 10}}
- {}
+ {'Coke': {'price': 1.25, 'quantity': 10}}

======================================================================
FAIL: test_add_item_2 (ClassEval_94_0.VendingMachineTestAddItem.test_add_item_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 109, in test_add_item_2
    self.assertEqual(vendingMachine.inventory, {'Coke': {'price': 1.25, 'quantity': 20}})
AssertionError: {} != {'Coke': {'price': 1.25, 'quantity': 20}}
- {}
+ {'Coke': {'price': 1.25, 'quantity': 20}}

======================================================================
FAIL: test_add_item_3 (ClassEval_94_0.VendingMachineTestAddItem.test_add_item_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 115, in test_add_item_3
    self.assertEqual(vendingMachine.inventory, {'Coke': {'price': 1.25, 'quantity': 10}, 'Pizza': {'price': 1.25, 'quantity': 10}})
AssertionError: {} != {'Coke': {'price': 1.25, 'quantity': 10}, [36 chars] 10}}
- {}
+ {'Coke': {'price': 1.25, 'quantity': 10},
+  'Pizza': {'price': 1.25, 'quantity': 10}}

======================================================================
FAIL: test_add_item_4 (ClassEval_94_0.VendingMachineTestAddItem.test_add_item_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 122, in test_add_item_4
    self.assertEqual(vendingMachine.inventory, {'Coke': {'price': 1.25, 'quantity': 10}, 'Pizza': {'price': 1.25, 'quantity': 20}})
AssertionError: {} != {'Coke': {'price': 1.25, 'quantity': 10}, [36 chars] 20}}
- {}
+ {'Coke': {'price': 1.25, 'quantity': 10},
+  'Pizza': {'price': 1.25, 'quantity': 20}}

======================================================================
FAIL: test_add_item_5 (ClassEval_94_0.VendingMachineTestAddItem.test_add_item_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 130, in test_add_item_5
    self.assertEqual(vendingMachine.inventory, {'Coke': {'price': 1.25, 'quantity': 20}, 'Pizza': {'price': 1.25, 'quantity': 20}})
AssertionError: {} != {'Coke': {'price': 1.25, 'quantity': 20}, [36 chars] 20}}
- {}
+ {'Coke': {'price': 1.25, 'quantity': 20},
+  'Pizza': {'price': 1.25, 'quantity': 20}}

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_insert_coin (ClassEval_94_0.VendingMachineTestInsertCoin.test_insert_coin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 135, in test_insert_coin
    self.assertEqual(vendingMachine.insert_coin(1.25), 1.25)
AssertionError: None != 1.25

======================================================================
FAIL: test_insert_coin_2 (ClassEval_94_0.VendingMachineTestInsertCoin.test_insert_coin_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 139, in test_insert_coin_2
    self.assertEqual(vendingMachine.insert_coin(2.5), 2.5)
AssertionError: None != 2.5

======================================================================
FAIL: test_insert_coin_3 (ClassEval_94_0.VendingMachineTestInsertCoin.test_insert_coin_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 145, in test_insert_coin_3
    self.assertEqual(vendingMachine.balance, 2.50)
AssertionError: 0 != 2.5

======================================================================
FAIL: test_insert_coin_4 (ClassEval_94_0.VendingMachineTestInsertCoin.test_insert_coin_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 153, in test_insert_coin_4
    self.assertEqual(vendingMachine.balance, 5.0)
AssertionError: 1.25 != 5.0

======================================================================
FAIL: test_insert_coin_5 (ClassEval_94_0.VendingMachineTestInsertCoin.test_insert_coin_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 162, in test_insert_coin_5
    self.assertEqual(vendingMachine.balance, 6.25)
AssertionError: 1.25 != 6.25

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_purchase_item (ClassEval_94_0.VendingMachineTestPurchaseItem.test_purchase_item)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 169, in test_purchase_item
    self.assertEqual(vendingMachine.purchase_item('Coke'), 0.0)
AssertionError: None != 0.0

======================================================================
FAIL: test_purchase_item_2 (ClassEval_94_0.VendingMachineTestPurchaseItem.test_purchase_item_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 176, in test_purchase_item_2
    self.assertEqual(vendingMachine.purchase_item('Pizza'), False)
AssertionError: None != False

======================================================================
FAIL: test_purchase_item_3 (ClassEval_94_0.VendingMachineTestPurchaseItem.test_purchase_item_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 183, in test_purchase_item_3
    self.assertEqual(vendingMachine.purchase_item('Coke'), False)
AssertionError: None != False

======================================================================
FAIL: test_purchase_item_4 (ClassEval_94_0.VendingMachineTestPurchaseItem.test_purchase_item_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 190, in test_purchase_item_4
    self.assertEqual(vendingMachine.purchase_item('Coke'), False)
AssertionError: None != False

======================================================================
FAIL: test_purchase_item_5 (ClassEval_94_0.VendingMachineTestPurchaseItem.test_purchase_item_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 197, in test_purchase_item_5
    self.assertEqual(vendingMachine.purchase_item('Pizza'), 0.0)
AssertionError: None != 0.0

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_restock_item (ClassEval_94_0.VendingMachineTestRestockItem.test_restock_item)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 204, in test_restock_item
    self.assertEqual(vendingMachine.restock_item('Coke', 10), True)
AssertionError: None != True

======================================================================
FAIL: test_restock_item_2 (ClassEval_94_0.VendingMachineTestRestockItem.test_restock_item_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 210, in test_restock_item_2
    self.assertEqual(vendingMachine.restock_item('Pizza', 10), False)
AssertionError: None != False

======================================================================
FAIL: test_restock_item_3 (ClassEval_94_0.VendingMachineTestRestockItem.test_restock_item_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 216, in test_restock_item_3
    self.assertEqual(vendingMachine.restock_item('Coke', 10), True)
AssertionError: None != True

======================================================================
FAIL: test_restock_item_4 (ClassEval_94_0.VendingMachineTestRestockItem.test_restock_item_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 222, in test_restock_item_4
    self.assertEqual(vendingMachine.restock_item('Pizza', 10), True)
AssertionError: None != True

======================================================================
FAIL: test_restock_item_5 (ClassEval_94_0.VendingMachineTestRestockItem.test_restock_item_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 228, in test_restock_item_5
    self.assertEqual(vendingMachine.restock_item('Pizza', 0), True)
AssertionError: None != True

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
FFFFF
======================================================================
FAIL: test_display_items (ClassEval_94_0.VendingMachineTestDisplayItems.test_display_items)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 234, in test_display_items
    self.assertEqual(vendingMachine.display_items(), 'Coke - $1.25 [10]')
AssertionError: None != 'Coke - $1.25 [10]'

======================================================================
FAIL: test_display_items_2 (ClassEval_94_0.VendingMachineTestDisplayItems.test_display_items_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 238, in test_display_items_2
    self.assertEqual(vendingMachine.display_items(), False)
AssertionError: None != False

======================================================================
FAIL: test_display_items_3 (ClassEval_94_0.VendingMachineTestDisplayItems.test_display_items_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 243, in test_display_items_3
    self.assertEqual(vendingMachine.display_items(),"Coke - $1.25 [10]\nPizza - $1.25 [10]")
AssertionError: None != 'Coke - $1.25 [10]\nPizza - $1.25 [10]'

======================================================================
FAIL: test_display_items_4 (ClassEval_94_0.VendingMachineTestDisplayItems.test_display_items_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 248, in test_display_items_4
    self.assertEqual(vendingMachine.display_items(), 'Coke - $1.25 [0]')
AssertionError: None != 'Coke - $1.25 [0]'

======================================================================
FAIL: test_display_items_5 (ClassEval_94_0.VendingMachineTestDisplayItems.test_display_items_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 253, in test_display_items_5
    self.assertEqual(vendingMachine.display_items(), 'Coke - $1.25 [0]\nPizza - $1.25 [10]')
AssertionError: None != 'Coke - $1.25 [0]\nPizza - $1.25 [10]'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=5)
FF
======================================================================
FAIL: test_main (ClassEval_94_0.VendingMachineTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 258, in test_main
    self.assertEqual(vendingMachine.display_items(), False)
AssertionError: None != False

======================================================================
FAIL: test_main_2 (ClassEval_94_0.VendingMachineTestMain.test_main_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_94_0.py", line 272, in test_main_2
    self.assertEqual(vendingMachine.purchase_item('Coke'), False)
AssertionError: None != False

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=2)
FFFFFF
======================================================================
FAIL: test_query (ClassEval_96_0.WeatherSystemTestQuery.test_query)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 84, in test_query
    self.assertEqual(weatherSystem.query(weather_list), (27, 'sunny'))
AssertionError: None != (27, 'sunny')

======================================================================
FAIL: test_query_2 (ClassEval_96_0.WeatherSystemTestQuery.test_query_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 100, in test_query_2
    self.assertEqual(weatherSystem.query(weather_list), False)
AssertionError: None != False

======================================================================
FAIL: test_query_3 (ClassEval_96_0.WeatherSystemTestQuery.test_query_3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 116, in test_query_3
    self.assertEqual(weatherSystem.query(weather_list, 'fahrenheit'), (73.4, 'cloudy'))
AssertionError: None != (73.4, 'cloudy')

======================================================================
FAIL: test_query_4 (ClassEval_96_0.WeatherSystemTestQuery.test_query_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 132, in test_query_4
    self.assertEqual(weatherSystem.query(weather_list, 'celsius'), (23.000000000000004, 'cloudy'))
AssertionError: None != (23.000000000000004, 'cloudy')

======================================================================
FAIL: test_query_5 (ClassEval_96_0.WeatherSystemTestQuery.test_query_5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 148, in test_query_5
    self.assertEqual(weatherSystem.query(weather_list, tmp_units='celsius'), (26.999999999999996, 'sunny'))
AssertionError: None != (26.999999999999996, 'sunny')

======================================================================
FAIL: test_query_6 (ClassEval_96_0.WeatherSystemTestQuery.test_query_6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 164, in test_query_6
    self.assertEqual(weatherSystem.query(weather_list, tmp_units='fahrenheit'), (80.6, 'sunny'))
AssertionError: None != (80.6, 'sunny')

----------------------------------------------------------------------
Ran 6 tests in 0.002s

FAILED (failures=6)
FF.F.
======================================================================
FAIL: test_set_city (ClassEval_96_0.WeatherSystemTestSetCity.test_set_city)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 171, in test_set_city
    self.assertEqual(weatherSystem.city, 'Beijing')
AssertionError: 'New York' != 'Beijing'
- New York
+ Beijing


======================================================================
FAIL: test_set_city_2 (ClassEval_96_0.WeatherSystemTestSetCity.test_set_city_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 176, in test_set_city_2
    self.assertEqual(weatherSystem.city, 'Shanghai')
AssertionError: 'New York' != 'Shanghai'
- New York
+ Shanghai


======================================================================
FAIL: test_set_city_4 (ClassEval_96_0.WeatherSystemTestSetCity.test_set_city_4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 186, in test_set_city_4
    self.assertNotEqual(weatherSystem.city, 'New York')
AssertionError: 'New York' == 'New York'

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=3)
FF...
======================================================================
FAIL: test_celsius_to_fahrenheit (ClassEval_96_0.WeatherSystemTestCelsiusToFahrenheit.test_celsius_to_fahrenheit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 198, in test_celsius_to_fahrenheit
    self.assertEqual(weatherSystem.celsius_to_fahrenheit(), 80.6)
AssertionError: None != 80.6

======================================================================
FAIL: test_celsius_to_fahrenheit_2 (ClassEval_96_0.WeatherSystemTestCelsiusToFahrenheit.test_celsius_to_fahrenheit_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 203, in test_celsius_to_fahrenheit_2
    self.assertEqual(weatherSystem.celsius_to_fahrenheit(), 73.4)
AssertionError: None != 73.4

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
FF...
======================================================================
FAIL: test_fahrenheit_to_celsius (ClassEval_96_0.WeatherSystemTestFahrenheitToCelsius.test_fahrenheit_to_celsius)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 225, in test_fahrenheit_to_celsius
    self.assertEqual(weatherSystem.fahrenheit_to_celsius(), 26.999999999999996)
AssertionError: None != 26.999999999999996

======================================================================
FAIL: test_fahrenheit_to_celsius_2 (ClassEval_96_0.WeatherSystemTestFahrenheitToCelsius.test_fahrenheit_to_celsius_2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 230, in test_fahrenheit_to_celsius_2
    self.assertEqual(weatherSystem.fahrenheit_to_celsius(), 23.000000000000004)
AssertionError: None != 23.000000000000004

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2)
F
======================================================================
FAIL: test_main (ClassEval_96_0.WeatherSystemTestMain.test_main)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/snigdhaghoshdastidar/Desktop/CS540/classeval_evaluation/ClassEval_96_0.py", line 263, in test_main
    self.assertEqual(weatherSystem.query(weather_list), (27, 'sunny'))
AssertionError: None != (27, 'sunny')

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
